// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_PACKETS: u32 = 4;

pub const CODING_WINDOW: u32 = 1000;

pub const MAX_GENERATION_SIZE: u32 = 4;

pub fn create_packet(src: u32, dst: u32, payload: u32, seq: u32) -> u32 {
    return (((((src & 0xFF) << 24) | ((dst & 0xFF) << 16)) | ((payload & 0xFF) << 8)) | (seq & 0xFF));
}

pub fn get_packet_src(packet: u32) -> u32 {
    return ((packet >> 24) & 0xFF);
}

pub fn get_packet_dst(packet: u32) -> u32 {
    return ((packet >> 16) & 0xFF);
}

pub fn get_packet_payload(packet: u32) -> u32 {
    return ((packet >> 8) & 0xFF);
}

pub fn get_packet_seq(packet: u32) -> u32 {
    return (packet & 0xFF);
}

pub fn create_coded_packet(coeff: u32, payload: u32, generation: u32, seq: u32) -> u32 {
    return (((((coeff & 0xF) << 28) | ((payload & 0xFF) << 20)) | ((generation & 0xFF) << 12)) | (seq & 0xFFF));
}

pub fn get_coeff_vector(coded: u32) -> u32 {
    return ((coded >> 28) & 0xF);
}

pub fn get_coded_payload(coded: u32) -> u32 {
    return ((coded >> 20) & 0xFF);
}

pub fn get_generation(coded: u32) -> u32 {
    return ((coded >> 12) & 0xFF);
}

pub fn get_coded_seq(coded: u32) -> u32 {
    return (coded & 0xFFF);
}

pub fn xor_packets(pkt1: u32, pkt2: u32) -> u32 {
    return (pkt1 ^ pkt2);
}

pub fn create_xoded_native(pkt1: u32, pkt2: u32, generation: u32, seq: u32) -> u32 {
    let;
    coded_payload = xor_packets(get_packet_payload(pkt1), get_packet_payload(pkt2));
    let;
    coeff = 0b11;
    return create_coded_packet(coeff, coded_payload, generation, seq);
}

pub fn decode_xoded_packet(coded: u32, known_pkt: u32) -> u32 {
    let;
    coded_payload = get_coded_payload(coded);
    let;
    known_payload = get_packet_payload(known_pkt);
    let;
    decoded_payload = (coded_payload ^ known_payload);
    return create_packet(get_packet_src(known_pkt), get_packet_dst(known_pkt), decoded_payload, get_coded_seq(coded));
}

pub fn same_generation(pkt1: u32, pkt2: u32) -> bool {
    let;
    seq1 = get_packet_seq(pkt1);
    let;
    seq2 = get_packet_seq(pkt2);
    let;
    gen1 = (seq1 / MAX_GENERATION_SIZE);
    let;
    gen2 = (seq2 / MAX_GENERATION_SIZE);
    return (gen1 == gen2);
}

pub fn get_generation_id(packet: u32) -> u32 {
    let;
    seq = get_packet_seq(packet);
    return (seq / MAX_GENERATION_SIZE);
}

pub fn is_coding_beneficial(pkt1: u32, pkt2: u32, next_hop1: u32, next_hop2: u32) -> bool {
    return (next_hop1 != next_hop2);
}

pub fn linear_code_packets(pkt1: u32, pkt2: u32, coeff1: u32, coeff2: u32) -> u32 {
    let;
    result = 0;
    if ((coeff1 & 1) == 1) {
        result = (result ^ pkt1);
    }
    if ((coeff2 & 1) == 1) {
        result = (result ^ pkt2);
    }
    return result;
}

pub fn create_coded_generation(p0: u32, p1: u32, p2: u32, p3: u32) -> u64 {
    return ((((() << 48) | (() << 32)) | (() << 16)) | ());
}

pub fn get_coded_packet_gen(gen: u64, index: u32) -> u32 {
    if (index == 0) {
        return ();
    }
    if (index == 1) {
        return ();
    }
    if (index == 2) {
        return ();
    }
    return ();
}

pub fn count_generation_packets(gen: u64) -> u32 {
    let;
    count = 0;
    if (get_coded_packet_gen(gen, 0) != 0) {
        count = (count + 1);
    }
    if (get_coded_packet_gen(gen, 1) != 0) {
        count = (count + 1);
    }
    if (get_coded_packet_gen(gen, 2) != 0) {
        count = (count + 1);
    }
    if (get_coded_packet_gen(gen, 3) != 0) {
        count = (count + 1);
    }
    return count;
}

pub fn is_generation_decodable(gen: u64, original_count: u32) -> u32 {
    let;
    if (coded_count >= original_count) {
        return 1;
    }
    return 0;
}

pub fn calculate_coding_gain(original: u32, coded: u32) -> u32 {
    if (coded == 0) {
        return 0;
    }
    return (original - coded);
}

