// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const QUEUE_SIZE: u8 = 8;

pub fn get_count(state: u32) -> u8 {
    return ();
}

pub fn is_full(state: u32) -> bool {
    return (get_count(state) >= QUEUE_SIZE);
}

pub fn is_empty(state: u32) -> bool {
    return (get_count(state) == 0);
}

pub fn increment_index(idx: u8) -> u8 {
    if (idx >= 7) {
        return 0;
    } else {
        return (idx + 1);
    }
}

pub fn enqueue(state: u32, data: u32) -> u32 {
    if is_full(state) {
        return state;
    }
}

pub fn dequeue(state: u32) -> u32 {
    if is_empty(state) {
        return state;
    }
}

pub fn size(state: u32) -> u8 {
    return get_count(state);
}

pub fn clear() -> u32 {
    return 0;
}

