// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_PATHS: u32 = 4;

pub const BATTERY_WEIGHT: u32 = 7;

pub const HOP_WEIGHT: u32 = 3;

pub const CRITICAL_BATTERY: u32 = 20;

pub fn create_energy_cost(tx_power: u32, rx_power: u32, processing: u32, hop_count: u32) -> u32 {
    return (((((tx_power & 0xFF) << 24) | ((rx_power & 0xFF) << 16)) | ((processing & 0xFF) << 8)) | (hop_count & 0xFF));
}

pub fn get_tx_power(cost: u32) -> u32 {
    return ((cost >> 24) & 0xFF);
}

pub fn get_rx_power(cost: u32) -> u32 {
    return ((cost >> 16) & 0xFF);
}

pub fn get_processing_cost(cost: u32) -> u32 {
    return ((cost >> 8) & 0xFF);
}

pub fn get_hop_count_cost(cost: u32) -> u32 {
    return (cost & 0xFF);
}

pub fn create_path_energy(battery_levels: u32, total_cost: u32, path_valid: u32, energy_score: u32) -> u32 {
    return (((((battery_levels & 0xFF) << 24) | ((total_cost & 0xFF) << 16)) | ((path_valid & 0x1) << 15)) | (energy_score & 0x7FFF));
}

pub fn get_battery_levels(energy: u32) -> u32 {
    return ((energy >> 24) & 0xFF);
}

pub fn get_total_cost(energy: u32) -> u32 {
    return ((energy >> 16) & 0xFF);
}

pub fn get_path_valid(energy: u32) -> u32 {
    return ((energy >> 15) & 0x1);
}

pub fn get_energy_score(energy: u32) -> u32 {
    return (energy & 0x7FFF);
}

pub fn create_energy_array(e0: u32, e1: u32, e2: u32, e3: u32) -> u64 {
    return ((((() << 48) | (() << 32)) | (() << 16)) | ());
}

pub fn get_path_energy(array: u64, index: u32) -> u32 {
    if (index == 0) {
        return ();
    }
    if (index == 1) {
        return ();
    }
    if (index == 2) {
        return ();
    }
    return ();
}

pub fn calculate_total_energy_cost(cost: u32) -> u32 {
    let;
    tx = get_tx_power(cost);
    let;
    rx = get_rx_power(cost);
    let;
    proc = get_processing_cost(cost);
    let;
    hops = get_hop_count_cost(cost);
    let;
    per_hop = ((tx + rx) + proc);
    return (per_hop * hops);
}

pub fn calculate_energy_score(battery: u32, cost: u32) -> u32 {
    let;
    total_cost = calculate_total_energy_cost(cost);
    if (total_cost == 0) {
        return (battery * 10);
    }
    let;
    score = ((battery * 100) / total_cost);
    if (score > 32767) {
        score = 32767;
    }
    return score;
}

pub fn is_path_viable(energy: u32) -> bool {
    let;
    battery = get_battery_levels(energy);
    let;
    valid = get_path_valid(energy);
    return ((valid == 1) && (battery > CRITICAL_BATTERY));
}

pub fn find_energy_optimal_path(energy_array: u64) -> u32 {
    let;
    best_path = 0xFF;
    let;
    if is_path_viable(get_path_energy(energy_array, 0)) {
        let;
        score = get_energy_score(get_path_energy(energy_array, 0));
        if (score > best_score) {
            best_score = score;
            best_path = 0;
        }
    }
    if is_path_viable(get_path_energy(energy_array, 1)) {
        let;
        score = get_energy_score(get_path_energy(energy_array, 1));
        if (score > best_score) {
            best_score = score;
            best_path = 1;
        }
    }
    if is_path_viable(get_path_energy(energy_array, 2)) {
        let;
        score = get_energy_score(get_path_energy(energy_array, 2));
        if (score > best_score) {
            best_score = score;
            best_path = 2;
        }
    }
    if is_path_viable(get_path_energy(energy_array, 3)) {
        let;
        score = get_energy_score(get_path_energy(energy_array, 3));
        if (score > best_score) {
            best_score = score;
            best_path = 3;
        }
    }
    return best_path;
}

pub fn find_min_cost_path(energy_array: u64) -> u32 {
    let;
    best_path = 0xFF;
    let;
    if is_path_viable(get_path_energy(energy_array, 0)) {
        let;
        cost = get_total_cost(get_path_energy(energy_array, 0));
        if (cost < best_cost) {
            best_cost = cost;
            best_path = 0;
        }
    }
    if is_path_viable(get_path_energy(energy_array, 1)) {
        let;
        cost = get_total_cost(get_path_energy(energy_array, 1));
        if (cost < best_cost) {
            best_cost = cost;
            best_path = 1;
        }
    }
    if is_path_viable(get_path_energy(energy_array, 2)) {
        let;
        cost = get_total_cost(get_path_energy(energy_array, 2));
        if (cost < best_cost) {
            best_cost = cost;
            best_path = 2;
        }
    }
    if is_path_viable(get_path_energy(energy_array, 3)) {
        let;
        cost = get_total_cost(get_path_energy(energy_array, 3));
        if (cost < best_cost) {
            best_cost = cost;
            best_path = 3;
        }
    }
    return best_path;
}

pub fn select_balanced_path(energy_array: u64, current_path: u32) -> u32 {
    let;
    best_path = current_path;
    let;
    if is_path_viable(get_path_energy(energy_array, 0)) {
        let;
        battery = get_battery_levels(get_path_energy(energy_array, 0));
        if (battery > best_battery) {
            best_battery = battery;
            best_path = 0;
        }
    }
    if is_path_viable(get_path_energy(energy_array, 1)) {
        let;
        battery = get_battery_levels(get_path_energy(energy_array, 1));
        if (battery > best_battery) {
            best_battery = battery;
            best_path = 1;
        }
    }
    if is_path_viable(get_path_energy(energy_array, 2)) {
        let;
        battery = get_battery_levels(get_path_energy(energy_array, 2));
        if (battery > best_battery) {
            best_battery = battery;
            best_path = 2;
        }
    }
    if is_path_viable(get_path_energy(energy_array, 3)) {
        let;
        battery = get_battery_levels(get_path_energy(energy_array, 3));
        if (battery > best_battery) {
            best_battery = battery;
            best_path = 3;
        }
    }
    return best_path;
}

pub fn estimate_path_lifetime(energy: u32, drain_rate: u32) -> u32 {
    let;
    battery = get_battery_levels(energy);
    if (drain_rate == 0) {
        return 0xFF;
    }
    return (battery / drain_rate);
}

