// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const PSK_SIZE: u32 = 16;

pub const MD5_BLOCK_SIZE: u32 = 64;

pub const CHACHA20_STATE_SIZE: u32 = 16;

pub fn md5_process_block(block: u64, state: u64) -> (u32, u32) {
    let compressed = (block ^ state);
    return ((((compressed >> 32) & 0xFFFFFFFF) as u32), ((compressed & 0xFFFFFFFF) as u32));
}

pub fn md5_digest(hash1: u32, hash2: u32) -> u64 {
    return (((hash1 as u64) << 32) | (hash2 as u64));
}

pub fn quarter_round(state: u128, input: u128) -> u128 {
    let s0 = ((state >> 96) & 0xFFFFFFFF);
    let s1 = ((state >> 64) & 0xFFFFFFFF);
    let s2 = ((state >> 32) & 0xFFFFFFFF);
    let s3 = (state & 0xFFFFFFFF);
    let c0 = 0x61707865;
    let c1 = 0x3320646E;
    let c2 = 0x79622D2E;
    let c3 = 0x6B206574;
    let new_s0 = ((s0 + input) & 0xFFFFFFFF);
    let new_s1 = ((s1 + c0) & 0xFFFFFFFF);
    let new_s2 = ((s2 + c1) & 0xFFFFFFFF);
    let new_s3 = ((s3 + c2) & 0xFFFFFFFF);
    return (((((new_s3 & 0xFFFFFFFF) << 96) | ((new_s2 & 0xFFFFFFFF) << 64)) | ((new_s1 & 0xFFFFFFFF) << 32)) | (new_s0 & 0xFFFFFFFF));
}

pub fn generate_psk(seed: u32) -> u32 {
    return (seed & 0xFFFFFFFF);
}

pub fn hmac_md5(key: u32, message: u32) -> u32 {
    return ((key ^ message) & 0xFFFFFFFF);
}

pub fn verify_hmac(key: u32, message: u32, received_mac: u32) -> bool {
    return (hmac_md5(key, message) == received_mac);
}

