// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_FUNCTIONS: u32 = 64;

pub const MAX_PARAMETERS: u32 = 16;

pub const MAX_EXAMPLES: u32 = 8;

pub const MAX_DESCRIPTIONS: u32 = 32;

pub fn create_function_doc(func_id: u32, param_count: u32, return_type: u32, complexity: u32) -> u32 {
    return (((((func_id & 0xFF) << 24) | ((param_count & 0xF) << 20)) | ((return_type & 0xF) << 16)) | (complexity & 0xFFFF));
}

pub fn get_doc_function_id(doc: u32) -> u32 {
    return ((doc >> 24) & 0xFF);
}

pub fn get_doc_param_count(doc: u32) -> u32 {
    return ((doc >> 20) & 0xF);
}

pub fn get_doc_return_type(doc: u32) -> u32 {
    return ((doc >> 16) & 0xF);
}

pub fn get_doc_complexity(doc: u32) -> u32 {
    return (doc & 0xFFFF);
}

pub fn create_param_doc(param_id: u32, param_type: u32, direction: u32, desc_id: u32) -> u32 {
    return (((((param_id & 0xFF) << 24) | ((param_type & 0xF) << 20)) | ((direction & 0x3) << 18)) | (desc_id & 0x3FFFF));
}

pub fn get_param_doc_id(param_doc: u32) -> u32 {
    return ((param_doc >> 24) & 0xFF);
}

pub fn get_param_doc_type(param_doc: u32) -> u32 {
    return ((param_doc >> 20) & 0xF);
}

pub fn get_param_direction(param_doc: u32) -> u32 {
    return ((param_doc >> 18) & 0x3);
}

pub fn get_param_description_id(param_doc: u32) -> u32 {
    return (param_doc & 0x3FFFF);
}

pub const DIR_IN: u32 = 0;

pub const DIR_OUT: u32 = 1;

pub const DIR_INOUT: u32 = 2;

pub fn extract_function_signature(code_line: u32) -> u32 {
    let func_id: u32 = ((code_line >> 16) & 0xFF);
    let param_count: u32 = ((code_line >> 8) & 0xF);
    let return_type: u32 = (code_line & 0xF);
    return create_function_doc(func_id, param_count, return_type, 0);
}

pub fn extract_parameter_info(param_line: u32, param_index: u32) -> u32 {
    let param_type: u32 = ((param_line >> 8) & 0xF);
    let direction: u32 = ((param_line >> 6) & 0x3);
    let description_id: u32 = (param_line & 0x3F);
    return create_param_doc(param_index, param_type, direction, description_id);
}

pub fn create_function_example(func_id: u32, input: u32, output: u32, explanation: u32) -> u32 {
    return (((((func_id & 0xFF) << 24) | ((input & 0xFF) << 16)) | ((output & 0xFF) << 8)) | (explanation & 0xFF));
}

pub fn get_example_function_id(example: u32) -> u32 {
    return ((example >> 24) & 0xFF);
}

pub fn get_example_input(example: u32) -> u32 {
    return ((example >> 16) & 0xFF);
}

pub fn get_example_output(example: u32) -> u32 {
    return ((example >> 8) & 0xFF);
}

pub fn get_example_explanation(example: u32) -> u32 {
    return (example & 0xFF);
}

pub fn generate_function_example(func_doc: u32) -> u32 {
    let func_id: u32 = get_doc_function_id(func_doc);
    let param_count: u32 = get_doc_param_count(func_doc);
    let return_type: u32 = get_doc_return_type(func_doc);
    let example_input: u32 = (param_count * 10);
    let example_output: u32 = (example_input + 5);
    let explanation: u32 = 1;
    return create_function_example(func_id, example_input, example_output, explanation);
}

pub fn create_description_text(desc_id: u32, length: u32, importance: u32, category: u32) -> u32 {
    return (((((desc_id & 0xFF) << 24) | ((length & 0xFF) << 16)) | ((importance & 0xF) << 12)) | (category & 0xFFF));
}

pub fn get_description_id(desc: u32) -> u32 {
    return ((desc >> 24) & 0xFF);
}

pub fn get_description_length(desc: u32) -> u32 {
    return ((desc >> 16) & 0xFF);
}

pub fn get_description_importance(desc: u32) -> u32 {
    return ((desc >> 12) & 0xF);
}

pub fn get_description_category(desc: u32) -> u32 {
    return (desc & 0xFFF);
}

pub fn generate_function_description(func_doc: u32, complexity: u32) -> u32 {
    let func_id: u32 = get_doc_function_id(func_doc);
    let param_count: u32 = get_doc_param_count(func_doc);
    let return_type: u32 = get_doc_return_type(func_doc);
    let mut desc_length: u32 = (50 + (complexity * 10));
    if (desc_length > 255) {
        desc_length = 255;
    }
    let importance: u32 = 1;
    let category: u32 = 0;
    return create_description_text(func_id, desc_length, importance, category);
}

pub fn create_cross_reference(source: u32, target: u32, ref_type: u32, strength: u32) -> u32 {
    return (((((source & 0xFF) << 24) | ((target & 0xFF) << 16)) | ((ref_type & 0xF) << 12)) | (strength & 0xFFF));
}

pub fn get_xref_source(xref: u32) -> u32 {
    return ((xref >> 24) & 0xFF);
}

pub fn get_xref_target(xref: u32) -> u32 {
    return ((xref >> 16) & 0xFF);
}

pub fn get_xref_type(xref: u32) -> u32 {
    return ((xref >> 12) & 0xF);
}

pub fn get_xref_strength(xref: u32) -> u32 {
    return (xref & 0xFFF);
}

pub const XREF_CALLS: u32 = 0;

pub const XREF_CALLED_BY: u32 = 1;

pub const XREF_RELATED: u32 = 2;

pub const XREF_SIMILAR: u32 = 3;

pub fn detect_function_call(caller: u32, callee: u32) -> u32 {
    return create_cross_reference(caller, callee, XREF_CALLS, 100);
}

pub fn create_module_doc(module_id: u32, func_count: u32, total_complexity: u32, description: u32) -> u32 {
    return (((((module_id & 0xFF) << 24) | ((func_count & 0xFF) << 16)) | ((total_complexity & 0xFF) << 8)) | (description & 0xFF));
}

pub fn get_module_doc_id(module_doc: u32) -> u32 {
    return ((module_doc >> 24) & 0xFF);
}

pub fn get_module_function_count(module_doc: u32) -> u32 {
    return ((module_doc >> 16) & 0xFF);
}

pub fn get_module_total_complexity(module_doc: u32) -> u32 {
    return ((module_doc >> 8) & 0xFF);
}

pub fn get_module_description(module_doc: u32) -> u32 {
    return (module_doc & 0xFF);
}

pub fn calculate_average_complexity(func_docs: [u32; MAX_FUNCTIONS as usize], func_count: u32) -> u32 {
    let mut total_complexity: u32 = 0;
    let mut i: u32 = 0;
    while (i < func_count) {
        total_complexity = (total_complexity + get_doc_complexity(func_docs[(i) as usize]));
        i = (i + 1);
    }
    if (func_count > 0) {
        return (total_complexity / func_count);
    } else {
        return 0;
    }
}

pub fn generate_api_documentation(func_docs: [u32; MAX_FUNCTIONS as usize], func_count: u32, param_docs: [u32; MAX_PARAMETERS as usize], param_count: u32) -> u32 {
    let mut total_complexity: u32 = 0;
    let mut documented_funcs: u32 = 0;
    let mut i: u32 = 0;
    while (i < func_count) {
        let func_doc: u32 = func_docs[(i) as usize];
        total_complexity = (total_complexity + get_doc_complexity(func_doc));
        let description: u32 = generate_function_description(func_doc, get_doc_complexity(func_doc));
        let example: u32 = generate_function_example(func_doc);
        documented_funcs = (documented_funcs + 1);
        i = (i + 1);
    }
    let avg_complexity: u32 = calculate_average_complexity(func_docs, func_count);
    return (((((documented_funcs & 0xFF) << 24) | ((total_complexity & 0xFF) << 16)) | ((avg_complexity & 0xFF) << 8)) | (param_count & 0xFF));
}

pub fn calculate_documentation_coverage(documented_funcs: u32, total_funcs: u32) -> u32 {
    if (total_funcs > 0) {
        return ((documented_funcs * 100) / total_funcs);
    } else {
        return 100;
    }
}

pub fn generate_usage_example(func_doc: u32, context: u32) -> u32 {
    let func_id: u32 = get_doc_function_id(func_doc);
    let param_count: u32 = get_doc_param_count(func_doc);
    let usage_pattern: u32 = ((param_count * 20) + context);
    return create_function_example(func_id, usage_pattern, (usage_pattern + 10), 2);
}

pub fn create_dependency_graph(xrefs: [u32; MAX_FUNCTIONS as usize], xref_count: u32) -> u32 {
    let mut total_connections: u32 = 0;
    let mut strong_connections: u32 = 0;
    let mut i: u32 = 0;
    while (i < xref_count) {
        let strength: u32 = get_xref_strength(xrefs[(i) as usize]);
        total_connections = (total_connections + 1);
        if (strength > 70) {
            strong_connections = (strong_connections + 1);
        }
        i = (i + 1);
    }
    let mut avg_strength: u32 = 0;
    if (total_connections > 0) {
        avg_strength = (strong_connections / total_connections);
    }
    return (((((total_connections & 0xFF) << 24) | ((strong_connections & 0xFF) << 16)) | ((avg_strength & 0xFF) << 8)) | (xref_count & 0xFF));
}

pub fn validate_documentation(func_docs: [u32; MAX_FUNCTIONS as usize], func_count: u32) -> u32 {
    let mut missing_descriptions: u32 = 0;
    let missing_examples: u32 = 0;
    let mut missing_params: u32 = 0;
    let mut i: u32 = 0;
    while (i < func_count) {
        let func_doc: u32 = func_docs[(i) as usize];
        let complexity: u32 = get_doc_complexity(func_doc);
        if (complexity == 0) {
            missing_descriptions = (missing_descriptions + 1);
        }
        let param_count: u32 = get_doc_param_count(func_doc);
        if ((param_count == 0) && (i > 0)) {
            missing_params = (missing_params + 1);
        }
        i = (i + 1);
    }
    let mut quality_score: u32 = (100 - ((missing_descriptions * 10) + (missing_params * 5)));
    if (quality_score > 100) {
        quality_score = 100;
    }
    return (((((missing_descriptions & 0xFF) << 24) | ((missing_examples & 0xFF) << 16)) | ((missing_params & 0xFF) << 8)) | (quality_score & 0xFF));
}

pub fn generate_documentation_report(func_docs: [u32; MAX_FUNCTIONS as usize], func_count: u32, xrefs: [u32; MAX_FUNCTIONS as usize], xref_count: u32, param_docs: [u32; MAX_PARAMETERS as usize], param_count: u32) -> u32 {
    let doc_summary: u32 = generate_api_documentation(func_docs, func_count, param_docs, param_count);
    let documented_funcs: u32 = ((doc_summary >> 24) & 0xFF);
    let coverage: u32 = calculate_documentation_coverage(documented_funcs, func_count);
    let validation: u32 = validate_documentation(func_docs, func_count);
    let quality_score: u32 = (validation & 0xFF);
    let dependency_graph: u32 = create_dependency_graph(xrefs, xref_count);
    let doc_complexity: u32 = ((doc_summary >> 8) & 0xFF);
    return (((((coverage & 0xFF) << 24) | ((quality_score & 0xFF) << 16)) | ((doc_complexity & 0xFF) << 8)) | (xref_count & 0xFF));
}

