// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/app.html"
    | "/background.js"
    | "/content-scripts/auth.js"
    | "/content-scripts/content.js"
    | "/content-scripts/glow.js"
    | "/content-scripts/selection.js"
    | "/geist-mono/GeistMono-Italic[wght].woff2"
    | "/geist-mono/GeistMono[wght].woff2"
    | "/geist/Geist-Italic[wght].woff2"
    | "/geist/Geist[wght].woff2"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/sidepanel.html"
    | "/wxt.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
