// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_MODULES: u32 = 16;

pub const MAX_MESSAGES: u32 = 32;

pub const MAX_EVENTS: u32 = 64;

pub const INTEGRATION_VERSION: u32 = 1;

pub fn create_module_registration(module_id: u32, module_type: u32, priority: u32, status: u32) -> u32 {
    return (((((module_id & 0xFF) << 24) | ((module_type & 0xF) << 20)) | ((priority & 0xF) << 16)) | (status & 0xFFFF));
}

pub fn get_registered_module_id(registration: u32) -> u32 {
    return ((registration >> 24) & 0xFF);
}

pub fn get_registered_module_type(registration: u32) -> u32 {
    return ((registration >> 20) & 0xF);
}

pub fn get_registered_module_priority(registration: u32) -> u32 {
    return ((registration >> 16) & 0xF);
}

pub fn get_registered_module_status(registration: u32) -> u32 {
    return (registration & 0xFFFF);
}

pub const TYPE_NETWORK: u32 = 0;

pub const TYPE_TESTING: u32 = 1;

pub const type_documentation: u32 = 2;

pub const TYPE_VISUALIZATION: u32 = 3;

pub const TYPE_SIMULATION: u32 = 4;

pub const TYPE_PROFILING: u32 = 5;

pub const STATUS_IDLE: u32 = 0;

pub const STATUS_ACTIVE: u32 = 1;

pub const STATUS_BUSY: u32 = 2;

pub const STATUS_ERROR: u32 = 3;

pub const STATUS_OFFLINE: u32 = 4;

pub fn create_integration_message(msg_id: u32, source: u32, dest: u32, msg_type: u32) -> u32 {
    return (((((msg_id & 0xFF) << 24) | ((source & 0xFF) << 16)) | ((dest & 0xFF) << 8)) | (msg_type & 0xFF));
}

pub fn get_integration_message_id(message: u32) -> u32 {
    return ((message >> 24) & 0xFF);
}

pub fn get_integration_message_source(message: u32) -> u32 {
    return ((message >> 16) & 0xFF);
}

pub fn get_integration_message_dest(message: u32) -> u32 {
    return ((message >> 8) & 0xFF);
}

pub fn get_integration_message_type(message: u32) -> u32 {
    return (message & 0xFF);
}

pub const MSG_DATA: u32 = 0;

pub const MSG_CONTROL: u32 = 1;

pub const MSG_STATUS: u32 = 2;

pub const MSG_ERROR: u32 = 3;

pub const MSG_EVENT: u32 = 4;

pub fn send_message(modules: [u32; MAX_MODULES as usize], message: u32) -> u32 {
    let dest: u32 = get_integration_message_dest(message);
    let msg_type: u32 = get_integration_message_type(message);
    let mut i: u32 = 0;
    while (i < MAX_MODULES) {
        let module_id: u32 = get_registered_module_id(modules[(i) as usize]);
        if (module_id == dest) {
            let status: u32 = get_registered_module_status(modules[(i) as usize]);
            if ((status == STATUS_ACTIVE) || (status == STATUS_BUSY)) {
                return 1;
            } else {
                return 0;
            }
        }
        i = (i + 1);
    }
    return 0;
}

pub fn receive_message(messages: [u32; MAX_MESSAGES as usize], message_count: u32, module_id: u32) -> u32 {
    let mut i: u32 = 0;
    while (i < message_count) {
        let dest: u32 = get_integration_message_dest(messages[(i) as usize]);
        if (dest == module_id) {
            return i;
        }
        i = (i + 1);
    }
    return MAX_MESSAGES;
}

pub fn create_event(event_id: u32, event_type: u32, source: u32, data: u32) -> u32 {
    return (((((event_id & 0xFF) << 24) | ((event_type & 0xF) << 20)) | ((source & 0xFF) << 12)) | (data & 0xFFF));
}

pub fn get_event_id(event: u32) -> u32 {
    return ((event >> 24) & 0xFF);
}

pub fn get_event_type(event: u32) -> u32 {
    return ((event >> 20) & 0xF);
}

pub fn get_event_source(event: u32) -> u32 {
    return ((event >> 12) & 0xFF);
}

pub fn get_event_data(event: u32) -> u32 {
    return (event & 0xFFF);
}

pub const EVENT_MODULE_LOADED: u32 = 0;

pub const EVENT_MODULE_UNLOADED: u32 = 1;

pub const EVENT_TEST_COMPLETED: u32 = 2;

pub const EVENT_SIMULATION_STEP: u32 = 3;

pub const EVENT_VISUALIZATION_UPDATE: u32 = 4;

pub fn subscribe_to_event(module_id: u32, event_type: u32, subscriptions: [u32; MAX_EVENTS as usize]) -> u32 {
    let subscription_id: u32 = ((module_id * 10) + event_type);
    let mut i: u32 = 0;
    while (i < MAX_EVENTS) {
        if (subscriptions[(i) as usize] == 0) {
            subscriptions[(i) as usize] = create_event(subscription_id, event_type, module_id, 0);
            return 1;
        }
        i = (i + 1);
    }
    return 0;
}

pub fn publish_event(event: u32, subscriptions: [u32; MAX_EVENTS as usize], modules: [u32; MAX_MODULES as usize]) -> u32 {
    let event_type: u32 = get_event_type(event);
    let mut notified_count: u32 = 0;
    let mut i: u32 = 0;
    while (i < MAX_EVENTS) {
        let sub_event_type: u32 = get_event_type(subscriptions[(i) as usize]);
        if (sub_event_type == event_type) {
            let source: u32 = get_event_source(subscriptions[(i) as usize]);
            let module_id: u32 = source;
            let msg: u32 = create_integration_message(i, 0, module_id, MSG_EVENT);
            if (send_message(modules, msg) == 1) {
                notified_count = (notified_count + 1);
            }
        }
        i = (i + 1);
    }
    return notified_count;
}

pub fn create_state_sync(module_id: u32, state_version: u32, state_data: u32, checksum: u32) -> u32 {
    return (((((module_id & 0xFF) << 24) | ((state_version & 0xFF) << 16)) | ((state_data & 0xFF) << 8)) | (checksum & 0xFF));
}

pub fn get_sync_module_id(sync: u32) -> u32 {
    return ((sync >> 24) & 0xFF);
}

pub fn get_sync_state_version(sync: u32) -> u32 {
    return ((sync >> 16) & 0xFF);
}

pub fn get_sync_state_data(sync: u32) -> u32 {
    return ((sync >> 8) & 0xFF);
}

pub fn get_sync_checksum(sync: u32) -> u32 {
    return (sync & 0xFF);
}

pub fn synchronize_states(modules: [u32; MAX_MODULES as usize], module_count: u32, sync_requests: u32) -> u32 {
    let mut synced_count: u32 = 0;
    let mut i: u32 = 0;
    while (i < module_count) {
        let module_id: u32 = get_registered_module_id(modules[(i) as usize]);
        let status: u32 = get_registered_module_status(modules[(i) as usize]);
        if ((status == STATUS_ACTIVE) && (sync_requests > 0)) {
            let state_version: u32 = 1;
            let state_data: u32 = (i * 10);
            let checksum: u32 = ((state_data + state_version) & 0xFF);
            let sync: u32 = create_state_sync(module_id, state_version, state_data, checksum);
            synced_count = (synced_count + 1);
        }
        i = (i + 1);
    }
    return synced_count;
}

pub fn create_error_propagation(source_id: u32, error_code: u32, severity: u32, timestamp: u32) -> u32 {
    return (((((source_id & 0xFF) << 24) | ((error_code & 0xFF) << 16)) | ((severity & 0xF) << 12)) | (timestamp & 0xFFF));
}

pub fn get_error_source(error: u32) -> u32 {
    return ((error >> 24) & 0xFF);
}

pub fn get_error_code(error: u32) -> u32 {
    return ((error >> 16) & 0xFF);
}

pub fn get_error_severity(error: u32) -> u32 {
    return ((error >> 12) & 0xF);
}

pub fn get_error_timestamp(error: u32) -> u32 {
    return (error & 0xFFF);
}

pub const SEVERITY_INFO: u32 = 0;

pub const SEVERITY_WARNING: u32 = 1;

pub const SEVERITY_ERROR: u32 = 2;

pub const SEVERITY_CRITICAL: u32 = 3;

pub fn propagate_error(error: u32, modules: [u32; MAX_MODULES as usize], module_count: u32) -> u32 {
    let severity: u32 = get_error_severity(error);
    let mut notified_count: u32 = 0;
    let mut i: u32 = 0;
    while (i < module_count) {
        let module_type: u32 = get_registered_module_type(modules[(i) as usize]);
        if (severity == SEVERITY_CRITICAL) {
            let msg: u32 = create_integration_message(0, 0, i, MSG_ERROR);
            if (send_message(modules, msg) == 1) {
                notified_count = (notified_count + 1);
            }
        } else {
            if ((severity == SEVERITY_WARNING) || (severity == SEVERITY_ERROR)) {
                if ((module_type == TYPE_TESTING) || (module_type == TYPE_SIMULATION)) {
                    let msg: u32 = create_integration_message(0, 0, i, MSG_ERROR);
                    if (send_message(modules, msg) == 1) {
                        notified_count = (notified_count + 1);
                    }
                }
            }
        }
        i = (i + 1);
    }
    return notified_count;
}

pub fn load_module(module_id: u32, module_type: u32, priority: u32, modules: [u32; MAX_MODULES as usize]) -> u32 {
    let mut i: u32 = 0;
    while (i < MAX_MODULES) {
        if (get_registered_module_id(modules[(i) as usize]) == 0) {
            modules[(i) as usize] = create_module_registration(module_id, module_type, priority, STATUS_IDLE);
            return 1;
        }
        i = (i + 1);
    }
    return 0;
}

pub fn unload_module(module_id: u32, modules: [u32; MAX_MODULES as usize]) -> u32 {
    let mut i: u32 = 0;
    while (i < MAX_MODULES) {
        let registered_id: u32 = get_registered_module_id(modules[(i) as usize]);
        if (registered_id == module_id) {
            modules[(i) as usize] = 0;
            return 1;
        }
        i = (i + 1);
    }
    return 0;
}

pub fn create_dependency(module_id: u32, depends_on: u32, dependency_type: u32, required: u32) -> u32 {
    return (((((module_id & 0xFF) << 24) | ((depends_on & 0xFF) << 16)) | ((dependency_type & 0xF) << 12)) | (required & 0xFFF));
}

pub fn get_dependency_module_id(dep: u32) -> u32 {
    return ((dep >> 24) & 0xFF);
}

pub fn get_dependency_depends_on(dep: u32) -> u32 {
    return ((dep >> 16) & 0xFF);
}

pub fn get_dependency_type(dep: u32) -> u32 {
    return ((dep >> 12) & 0xF);
}

pub fn get_dependency_required(dep: u32) -> u32 {
    return (dep & 0xFFF);
}

pub fn check_dependencies(module_id: u32, dependencies: [u32; MAX_MODULES as usize], loaded_modules: [u32; MAX_MODULES as usize], module_count: u32) -> u32 {
    let mut satisfied: u32 = 1;
    let mut i: u32 = 0;
    while (i < MAX_MODULES) {
        let dep_module_id: u32 = get_dependency_module_id(dependencies[(i) as usize]);
        if (dep_module_id == module_id) {
            let depends_on: u32 = get_dependency_depends_on(dependencies[(i) as usize]);
            let required: u32 = get_dependency_required(dependencies[(i) as usize]);
            if (required == 1) {
                let mut j: u32 = 0;
                let mut found: u32 = 0;
                while (j < module_count) {
                    let loaded_id: u32 = get_registered_module_id(loaded_modules[(j) as usize]);
                    if (loaded_id == depends_on) {
                        found = 1;
                        break;
                    }
                    j = (j + 1);
                }
                if (found == 0) {
                    satisfied = 0;
                }
            }
        }
        i = (i + 1);
    }
    return satisfied;
}

pub fn create_resource_request(module_id: u32, resource_type: u32, amount: u32, priority: u32) -> u32 {
    return (((((module_id & 0xFF) << 24) | ((resource_type & 0xF) << 20)) | ((amount & 0xFF) << 12)) | (priority & 0xFFF));
}

pub fn get_resource_request_module(req: u32) -> u32 {
    return ((req >> 24) & 0xFF);
}

pub fn get_resource_request_type(req: u32) -> u32 {
    return ((req >> 20) & 0xF);
}

pub fn get_resource_request_amount(req: u32) -> u32 {
    return ((req >> 12) & 0xFF);
}

pub fn get_resource_request_priority(req: u32) -> u32 {
    return (req & 0xFFF);
}

pub const RESOURCE_CPU: u32 = 0;

pub const RESOURCE_MEMORY: u32 = 1;

pub const RESOURCE_BANDWIDTH: u32 = 2;

pub const RESOURCE_STORAGE: u32 = 3;

pub fn allocate_resources(requests: [u32; MAX_MESSAGES as usize], request_count: u32, available_resources: u32) -> u32 {
    let mut total_requested: u32 = 0;
    let mut allocated_count: u32 = 0;
    let mut i: u32 = 0;
    while (i < request_count) {
        let amount: u32 = get_resource_request_amount(requests[(i) as usize]);
        total_requested = (total_requested + amount);
        i = (i + 1);
    }
    if (total_requested <= available_resources) {
        return total_requested;
    } else {
        let mut allocated: u32 = 0;
        let mut j: u32 = 0;
        while ((j < request_count) && (allocated < available_resources)) {
            let amount: u32 = get_resource_request_amount(requests[(j) as usize]);
            let priority: u32 = get_resource_request_priority(requests[(j) as usize]);
            if ((priority > 7) && ((allocated + amount) <= available_resources)) {
                allocated = (allocated + amount);
                allocated_count = (allocated_count + 1);
            }
            j = (j + 1);
        }
        return allocated;
    }
}

pub fn create_integration_report(loaded_modules: u32, active_messages: u32, events_processed: u32, errors_handled: u32) -> u32 {
    return (((((loaded_modules & 0xFF) << 24) | ((active_messages & 0xFF) << 16)) | ((events_processed & 0xFF) << 8)) | (errors_handled & 0xFF));
}

pub fn generate_integration_stats(modules: [u32; MAX_MODULES as usize], module_count: u32, messages: [u32; MAX_MESSAGES as usize], message_count: u32, events: [u32; MAX_EVENTS as usize], event_count: u32) -> u32 {
    let mut active_modules: u32 = 0;
    let mut active_messages: u32 = 0;
    let mut events_processed: u32 = 0;
    let errors_handled: u32 = 0;
    let mut i: u32 = 0;
    while (i < module_count) {
        let status: u32 = get_registered_module_status(modules[(i) as usize]);
        if ((status == STATUS_ACTIVE) || (status == STATUS_BUSY)) {
            active_modules = (active_modules + 1);
        }
        i = (i + 1);
    }
    let mut j: u32 = 0;
    while (j < message_count) {
        active_messages = (active_messages + 1);
        j = (j + 1);
    }
    let mut k: u32 = 0;
    while (k < event_count) {
        events_processed = (events_processed + 1);
        k = (k + 1);
    }
    return create_integration_report(active_modules, active_messages, events_processed, errors_handled);
}

pub fn validate_integration_health(modules: [u32; MAX_MODULES as usize], module_count: u32) -> u32 {
    let mut active_count: u32 = 0;
    let mut error_count: u32 = 0;
    let mut i: u32 = 0;
    while (i < module_count) {
        let status: u32 = get_registered_module_status(modules[(i) as usize]);
        if (status == STATUS_ACTIVE) {
            active_count = (active_count + 1);
        } else {
            if (status == STATUS_ERROR) {
                error_count = (error_count + 1);
            }
        }
        i = (i + 1);
    }
    let mut active_percentage: u32 = 0;
    if (module_count > 0) {
        active_percentage = ((active_count * 100) / module_count);
    }
    return (((active_percentage & 0xFF) << 24) | ((error_count & 0xFF) << 16));
}

