// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_NODES: u32 = 8;

pub const HISTORY_SIZE: u32 = 16;

pub const CONGESTION_THRESHOLD: u32 = 80;

pub const WARNING_THRESHOLD: u32 = 70;

pub const PREDICTION_WINDOW: u32 = 5;

pub fn create_load_metrics(bandwidth: u32, cpu: u32, packets: u32, queue: u32) -> u32 {
    return (((((bandwidth & 0xFF) << 24) | ((cpu & 0xFF) << 16)) | ((packets & 0xFF) << 8)) | (queue & 0xFF));
}

pub fn get_bandwidth_usage(metrics: u32) -> u32 {
    return ((metrics >> 24) & 0xFF);
}

pub fn get_cpu_usage(metrics: u32) -> u32 {
    return ((metrics >> 16) & 0xFF);
}

pub fn get_packet_rate(metrics: u32) -> u32 {
    return ((metrics >> 8) & 0xFF);
}

pub fn get_queue_depth(metrics: u32) -> u32 {
    return (metrics & 0xFF);
}

pub fn create_prediction(load: u32, confidence: u32, trend: u32, horizon: u32) -> u32 {
    return (((((load & 0xFF) << 24) | ((confidence & 0xFF) << 16)) | ((trend & 0x3) << 14)) | (horizon & 0x3FFF));
}

pub fn get_predicted_load(prediction: u32) -> u32 {
    return ((prediction >> 24) & 0xFF);
}

pub fn get_confidence(prediction: u32) -> u32 {
    return ((prediction >> 16) & 0xFF);
}

pub fn get_trend(prediction: u32) -> u32 {
    return ((prediction >> 14) & 0x3);
}

pub fn get_time_horizon(prediction: u32) -> u32 {
    return (prediction & 0x3FFF);
}

pub fn calculate_moving_average(history: Vec<>, count: u32) -> u32 {
    let;
    sum;
    let;
    i;
    while (i < count) {
        let;
        metrics = history[i];
        sum = (sum + get_bandwidth_usage(metrics));
        i = (i + 1);
    }
    if (count > 0) {
        return (sum / count);
    } else {
        return 0;
    }
}

pub fn detect_trend(history: Vec<>, count: u32) -> u32 {
    if (count < 3) {
        return 0;
    }
    let;
    recent;
    let;
    previous;
    let;
    diff;
    if (recent > previous) {
        diff = (recent - previous);
    } else {
        diff = (previous - recent);
    }
    if (diff > 20) {
        if (recent > previous) {
            return 1;
        } else {
            return 2;
        }
    } else {
        return 0;
    }
}

pub fn predict_load(history: Vec<>, count: u32) -> u32 {
    if (count == 0) {
        return 0;
    }
    let;
    current;
    let;
    trend;
    let;
    avg;
    let;
    predicted;
    if (trend == 1) {
        let;
        increase;
        predicted = (current + increase);
    } else {
        if (trend == 2) {
            let;
            decrease;
            if (current > decrease) {
                predicted = (current - decrease);
            } else {
                predicted = 0;
            }
        }
    }
    if (predicted > 100) {
        predicted = 100;
    }
    return predicted;
}

pub fn calculate_confidence(history: Vec<>, count: u32) -> u32 {
    if (count < 3) {
        return 20;
    }
    let;
    variance;
    let;
    avg;
    let;
    i;
    while (i < count) {
        let;
        value;
        let;
        diff;
        if (value > avg) {
            diff = (value - avg);
        } else {
            diff = (avg - value);
        }
        variance = (variance + diff);
        i = (i + 1);
    }
    let;
    avg_variance;
    if (count > 0) {
        avg_variance = (variance / count);
    }
    if (avg_variance > 30) {
        return 30;
    } else {
        if (avg_variance > 20) {
            return 50;
        } else {
            if (avg_variance > 10) {
                return 70;
            } else {
                return 90;
            }
        }
    }
}

pub fn create_load_prediction(history: Vec<>, count: u32) -> u32 {
    let;
    predicted;
    let;
    confidence;
    let;
    trend;
    let;
    horizon;
    return create_prediction(predicted, confidence, trend, horizon);
}

pub fn is_congestion_predicted(prediction: u32) -> u32 {
    let;
    load;
    let;
    confidence;
    if ((confidence > 50) && (load >= CONGESTION_THRESHOLD)) {
        return 1;
    } else {
        return 0;
    }
}

pub fn is_warning_predicted(prediction: u32) -> u32 {
    let;
    load;
    let;
    confidence;
    if ((confidence > 50) && (load >= WARNING_THRESHOLD)) {
        return 1;
    } else {
        return 0;
    }
}

pub fn calculate_network_load(node_metrics: Vec<>, node_count: u32) -> u32 {
    let;
    total_load;
    let;
    i;
    while (i < node_count) {
        let;
        load;
        total_load = (total_load + load);
        i = (i + 1);
    }
    if (node_count > 0) {
        return (total_load / node_count);
    } else {
        return 0;
    }
}

pub fn find_most_loaded_node(node_metrics: Vec<>, node_count: u32) -> u32 {
    let;
    max_load;
    let;
    max_node;
    let;
    i;
    while (i < node_count) {
        let;
        load;
        if (load > max_load) {
            max_load = load;
            max_node = i;
        }
        i = (i + 1);
    }
    return max_node;
}

pub fn find_least_loaded_node(node_metrics: Vec<>, node_count: u32) -> u32 {
    let;
    min_load;
    let;
    min_node;
    let;
    i;
    while (i < node_count) {
        let;
        load;
        if (load < min_load) {
            min_load = load;
            min_node = i;
        }
        i = (i + 1);
    }
    return min_node;
}

pub fn calculate_load_imbalance(node_metrics: Vec<>, node_count: u32) -> u32 {
    let;
    max_load;
    let;
    min_load;
    let;
    i;
    while (i < node_count) {
        let;
        load;
        if (load > max_load) {
            max_load = load;
        }
        if (load < min_load) {
            min_load = load;
        }
        i = (i + 1);
    }
    if (min_load == 0) {
        return max_load;
    }
    let;
    imbalance;
    return imbalance;
}

pub fn recommend_rerouting(prediction: u32, current_node: u32, node_metrics: Vec<>, node_count: u32) -> u32 {
    if !(is_congestion_predicted(prediction)) {
        return current_node;
    }
    let;
    least_loaded;
    if (least_loaded != current_node) {
        return least_loaded;
    } else {
        return current_node;
    }
}

