// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_PATHS: u32 = 4;

pub const METRIC_LATENCY: u32 = 0;

pub const METRIC_HOPS: u32 = 1;

pub const METRIC_BANDWIDTH: u32 = 2;

pub const UPDATE_INTERVAL: u32 = 5000;

pub fn create_path_metrics(latency: u32, hops: u32, bandwidth: u32, load: u32) -> u32 {
    return (((((latency & 0xFF) << 24) | ((hops & 0xFF) << 16)) | ((bandwidth & 0xFF) << 8)) | (load & 0xFF));
}

pub fn get_latency(metrics: u32) -> u32 {
    return ((metrics >> 24) & 0xFF);
}

pub fn get_hops(metrics: u32) -> u32 {
    return ((metrics >> 16) & 0xFF);
}

pub fn get_bandwidth(metrics: u32) -> u32 {
    return ((metrics >> 8) & 0xFF);
}

pub fn get_load(metrics: u32) -> u32 {
    return (metrics & 0xFF);
}

pub fn create_selection_state(primary: u32, backup: u32, metric_type: u32, last_update: u32) -> u32 {
    return (((((primary & 0x3) << 30) | ((backup & 0x3) << 28)) | ((metric_type & 0x3) << 26)) | (last_update & 0xFFFFFF));
}

pub fn get_primary_path(state: u32) -> u32 {
    return ((state >> 30) & 0x3);
}

pub fn get_backup_path(state: u32) -> u32 {
    return ((state >> 28) & 0x3);
}

pub fn get_metric_type(state: u32) -> u32 {
    return ((state >> 26) & 0x3);
}

pub fn get_last_update(state: u32) -> u32 {
    return (state & 0xFFFFFF);
}

pub fn create_path_metrics_array(m0: u32, m1: u32, m2: u32, m3: u32) -> u64 {
    return ((((() << 48) | (() << 32)) | (() << 16)) | ());
}

pub fn get_path_metrics(array: u64, index: u32) -> u32 {
    if (index == 0) {
        return ();
    }
    if (index == 1) {
        return ();
    }
    if (index == 2) {
        return ();
    }
    return ();
}

pub fn calculate_score(metrics: u32, metric_type: u32) -> u32 {
    if (metric_type == METRIC_LATENCY) {
        let;
        latency = get_latency(metrics);
        if (latency == 0) {
            return 255;
        }
        return (255 / latency);
    } else {
        if (metric_type == METRIC_HOPS) {
            let;
            hops = get_hops(metrics);
            if (hops == 0) {
                return 255;
            }
            return (255 / hops);
        } else {
            if (metric_type == METRIC_BANDWIDTH) {
                return get_bandwidth(metrics);
            }
        }
    }
    return 0;
}

pub fn find_best_path(metrics_array: u64, metric_type: u32) -> u32 {
    let;
    best_path = 0xFF;
    let;
    if (calculate_score(get_path_metrics(metrics_array, 0), metric_type) > best_score) {
        best_score = calculate_score(get_path_metrics(metrics_array, 0), metric_type);
        best_path = 0;
    }
    if (calculate_score(get_path_metrics(metrics_array, 1), metric_type) > best_score) {
        best_score = calculate_score(get_path_metrics(metrics_array, 1), metric_type);
        best_path = 1;
    }
    if (calculate_score(get_path_metrics(metrics_array, 2), metric_type) > best_score) {
        best_score = calculate_score(get_path_metrics(metrics_array, 2), metric_type);
        best_path = 2;
    }
    if (calculate_score(get_path_metrics(metrics_array, 3), metric_type) > best_score) {
        best_score = calculate_score(get_path_metrics(metrics_array, 3), metric_type);
        best_path = 3;
    }
    return best_path;
}

pub fn needs_update(state: u32, current_time: u32) -> bool {
    let;
    last = get_last_update(state);
    let;
    elapsed = (current_time - last);
    return (elapsed >= UPDATE_INTERVAL);
}

pub fn update_selection(state: u32, primary: u32, backup: u32, current_time: u32) -> u32 {
    let;
    metric_type = get_metric_type(state);
    return create_selection_state(primary, backup, metric_type, current_time);
}

pub fn change_metric_type(state: u32, new_metric: u32) -> u32 {
    let;
    primary = get_primary_path(state);
    let;
    backup = get_backup_path(state);
    let;
    last = get_last_update(state);
    return create_selection_state(primary, backup, new_metric, last);
}

pub fn is_path_congested(metrics: u32) -> bool {
    return (get_load(metrics) > 80);
}

pub fn find_least_congested(metrics_array: u64) -> u32 {
    let;
    best_path = 0;
    let;
    if (get_load(get_path_metrics(metrics_array, 1)) < best_load) {
        best_load = get_load(get_path_metrics(metrics_array, 1));
        best_path = 1;
    }
    if (get_load(get_path_metrics(metrics_array, 2)) < best_load) {
        best_load = get_load(get_path_metrics(metrics_array, 2));
        best_path = 2;
    }
    if (get_load(get_path_metrics(metrics_array, 3)) < best_load) {
        best_load = get_load(get_path_metrics(metrics_array, 3));
        best_path = 3;
    }
    return best_path;
}

