// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_NODES: u32 = 32;

pub const MAX_EVENTS: u32 = 128;

pub const MAX_PACKETS: u32 = 64;

pub const SIMULATION_TICK_MS: u32 = 10;

pub fn create_sim_event(event_id: u32, timestamp: u32, event_type: u32, node_id: u32) -> u32 {
    return (((((event_id & 0xFF) << 24) | ((timestamp & 0xFFFF) << 8)) | ((event_type & 0xF) << 4)) | (node_id & 0xF));
}

pub fn get_event_id(event: u32) -> u32 {
    return ((event >> 24) & 0xFF);
}

pub fn get_event_timestamp(event: u32) -> u32 {
    return ((event >> 8) & 0xFFFF);
}

pub fn get_event_type(event: u32) -> u32 {
    return ((event >> 4) & 0xF);
}

pub fn get_event_node_id(event: u32) -> u32 {
    return (event & 0xF);
}

pub const EVENT_PACKET_SEND: u32 = 0;

pub const EVENT_PACKET_RECV: u32 = 1;

pub const EVENT_NODE_FAILURE: u32 = 2;

pub const EVENT_LINK_FAILURE: u32 = 3;

pub const EVENT_TIMER_EXPIRE: u32 = 4;

pub const EVENT_STATE_CHANGE: u32 = 5;

pub fn create_node_state(node_id: u32, status: u32, energy: u32, position: u32) -> u32 {
    return (((((node_id & 0xF) << 28) | ((status & 0xF) << 24)) | ((energy & 0xFF) << 16)) | (position & 0xFFFF));
}

pub fn get_node_id(state: u32) -> u32 {
    return ((state >> 28) & 0xF);
}

pub fn get_node_status(state: u32) -> u32 {
    return ((state >> 24) & 0xF);
}

pub fn get_node_energy(state: u32) -> u32 {
    return ((state >> 16) & 0xFF);
}

pub fn get_node_position(state: u32) -> u32 {
    return (state & 0xFFFF);
}

pub const NODE_ACTIVE: u32 = 0;

pub const NODE_INACTIVE: u32 = 1;

pub const NODE_FAILED: u32 = 2;

pub const NODE_SLEEPING: u32 = 3;

pub fn update_node_status(state: u32, new_status: u32) -> u32 {
    let node_id: u32 = get_node_id(state);
    let energy: u32 = get_node_energy(state);
    let position: u32 = get_node_position(state);
    return create_node_state(node_id, new_status, energy, position);
}

pub fn update_node_energy(state: u32, energy_delta: u32) -> u32 {
    let node_id: u32 = get_node_id(state);
    let status: u32 = get_node_status(state);
    let energy: u32 = get_node_energy(state);
    let position: u32 = get_node_position(state);
    let mut new_energy: u32 = energy;
    if (energy_delta > energy) {
        new_energy = 0;
    } else {
        new_energy = (energy - energy_delta);
    }
    let mut new_status: u32 = status;
    if ((new_energy == 0) && (status == NODE_ACTIVE)) {
        new_status = NODE_FAILED;
    }
    return create_node_state(node_id, new_status, new_energy, position);
}

pub fn create_link_state(source: u32, dest: u32, quality: u32, latency: u32) -> u32 {
    return (((((source & 0xF) << 28) | ((dest & 0xF) << 24)) | ((quality & 0xFF) << 16)) | (latency & 0xFFFF));
}

pub fn get_link_source(link: u32) -> u32 {
    return ((link >> 28) & 0xF);
}

pub fn get_link_dest(link: u32) -> u32 {
    return ((link >> 24) & 0xF);
}

pub fn get_link_quality(link: u32) -> u32 {
    return ((link >> 16) & 0xFF);
}

pub fn get_link_latency(link: u32) -> u32 {
    return (link & 0xFFFF);
}

pub fn update_link_quality(link: u32, new_quality: u32) -> u32 {
    let source: u32 = get_link_source(link);
    let dest: u32 = get_link_dest(link);
    let latency: u32 = get_link_latency(link);
    return create_link_state(source, dest, new_quality, latency);
}

pub fn is_link_operational(link: u32) -> u32 {
    let quality: u32 = get_link_quality(link);
    if (quality >= 30) {
        return 1;
    } else {
        return 0;
    }
}

pub fn create_packet(packet_id: u32, source: u32, dest: u32, size: u32, sequence: u32) -> u32 {
    return ((((((packet_id & 0xFF) << 24) | ((source & 0xF) << 20)) | ((dest & 0xF) << 16)) | ((size & 0xFF) << 8)) | (sequence & 0xFF));
}

pub fn get_packet_id(packet: u32) -> u32 {
    return ((packet >> 24) & 0xFF);
}

pub fn get_packet_source(packet: u32) -> u32 {
    return ((packet >> 20) & 0xF);
}

pub fn get_packet_dest(packet: u32) -> u32 {
    return ((packet >> 16) & 0xF);
}

pub fn get_packet_size(packet: u32) -> u32 {
    return ((packet >> 8) & 0xFF);
}

pub fn get_packet_sequence(packet: u32) -> u32 {
    return (packet & 0xFF);
}

pub fn calculate_transmission_time(packet: u32, link: u32) -> u32 {
    let size: u32 = get_packet_size(packet);
    let latency: u32 = get_link_latency(link);
    let transmission_time: u32 = (latency + (size / 10));
    return transmission_time;
}

pub fn create_sim_state(current_time: u32, event_count: u32, node_count: u32) -> u32 {
    return ((((current_time & 0xFFFF) << 16) | ((event_count & 0xFF) << 8)) | (node_count & 0xFF));
}

pub fn get_sim_time(state: u32) -> u32 {
    return ((state >> 16) & 0xFFFF);
}

pub fn get_sim_event_count(state: u32) -> u32 {
    return ((state >> 8) & 0xFF);
}

pub fn get_sim_node_count(state: u32) -> u32 {
    return (state & 0xFF);
}

pub fn advance_simulation(state: u32, time_delta: u32) -> u32 {
    let current_time: u32 = get_sim_time(state);
    let event_count: u32 = get_sim_event_count(state);
    let node_count: u32 = get_sim_node_count(state);
    let new_time: u32 = (current_time + time_delta);
    return create_sim_state(new_time, event_count, node_count);
}

pub fn process_event(event: u32, node_states: [u32; MAX_NODES as usize], link_states: [u32; MAX_NODES as usize]) -> u32 {
    let event_type: u32 = get_event_type(event);
    let node_id: u32 = get_event_node_id(event);
    if (event_type == EVENT_PACKET_SEND) {
        return 1;
    } else {
        if (event_type == EVENT_PACKET_RECV) {
            return 1;
        } else {
            if (event_type == EVENT_NODE_FAILURE) {
                let current_state: u32 = node_states[(node_id) as usize];
                node_states[(node_id) as usize] = update_node_status(current_state, NODE_FAILED);
                return 1;
            } else {
                if (event_type == EVENT_LINK_FAILURE) {
                    return 1;
                } else {
                    if (event_type == EVENT_TIMER_EXPIRE) {
                        return 1;
                    } else {
                        return 0;
                    }
                }
            }
        }
    }
}

pub fn create_sim_stats(sent: u32, recv: u32, dropped: u32, latency: u32) -> u32 {
    return (((((sent & 0xFF) << 24) | ((recv & 0xFF) << 16)) | ((dropped & 0xFF) << 8)) | (latency & 0xFF));
}

pub fn get_packets_sent(stats: u32) -> u32 {
    return ((stats >> 24) & 0xFF);
}

pub fn get_packets_recv(stats: u32) -> u32 {
    return ((stats >> 16) & 0xFF);
}

pub fn get_packets_dropped(stats: u32) -> u32 {
    return ((stats >> 8) & 0xFF);
}

pub fn get_total_latency(stats: u32) -> u32 {
    return (stats & 0xFF);
}

pub fn calculate_delivery_ratio(stats: u32) -> u32 {
    let sent: u32 = get_packets_sent(stats);
    let recv: u32 = get_packets_recv(stats);
    if (sent > 0) {
        return ((recv * 100) / sent);
    } else {
        return 0;
    }
}

pub fn calculate_average_latency(stats: u32) -> u32 {
    let recv: u32 = get_packets_recv(stats);
    let total_latency: u32 = get_total_latency(stats);
    if (recv > 0) {
        return (total_latency / recv);
    } else {
        return 0;
    }
}

pub fn create_topology(node_count: u32, density: u32) -> u32 {
    let mut link_count: u32 = ((node_count * density) / 100);
    if (link_count > ((node_count * (node_count - 1)) / 2)) {
        link_count = ((node_count * (node_count - 1)) / 2);
    }
    return link_count;
}

pub fn inject_fault(fault_type: u32, target_id: u32, node_states: [u32; MAX_NODES as usize]) -> u32 {
    if (fault_type == EVENT_NODE_FAILURE) {
        let current_state: u32 = node_states[(target_id) as usize];
        node_states[(target_id) as usize] = update_node_status(current_state, NODE_FAILED);
        return 1;
    } else {
        if (fault_type == EVENT_LINK_FAILURE) {
            return 1;
        } else {
            return 0;
        }
    }
}

pub fn run_simulation_step(state: u32, events: [u32; MAX_EVENTS as usize], event_count: u32, node_states: [u32; MAX_NODES as usize], link_states: [u32; MAX_NODES as usize]) -> u32 {
    let current_time: u32 = get_sim_time(state);
    let mut processed_count: u32 = 0;
    let mut i: u32 = 0;
    while (i < event_count) {
        let event_time: u32 = get_event_timestamp(events[(i) as usize]);
        if (event_time <= current_time) {
            process_event(events[(i) as usize], node_states, link_states);
            processed_count = (processed_count + 1);
        }
        i = (i + 1);
    }
    let new_state: u32 = advance_simulation(state, SIMULATION_TICK_MS);
    return create_sim_state(get_sim_time(new_state), (get_sim_event_count(new_state) - processed_count), get_sim_node_count(new_state));
}

pub fn generate_simulation_report(stats: u32, duration: u32, node_count: u32) -> u32 {
    let delivery_ratio: u32 = calculate_delivery_ratio(stats);
    let avg_latency: u32 = calculate_average_latency(stats);
    return (((((delivery_ratio & 0xFF) << 24) | ((avg_latency & 0xFF) << 16)) | ((duration & 0xFF) << 8)) | (node_count & 0xFF));
}

