# W8 — Competitor watch (DePIN mesh + PUF/FPGA silicon)
> phi^2 + phi^-2 = 3
Date: 2026-07-05

Scope: source-cited competitor watch across two axes. Axis A bounds Tri-Net's Transport/Coverage (DePIN mesh / decentralized wireless) arm; Axis B bounds Tri-Net's Proof-of-FPGA / silicon-anchor arm. Every value carries a markdown link to a source fetched this session. Values that could not be confirmed from a fetched primary/secondary source are marked `n.a.`

---

## Axis A — DePIN mesh / decentralized wireless

| # | Entity | Primary product | Most recent public datapoint (date + what) | Token / business model | Differentiator from Tri-Net (overlapping arm) | Open threat to Tri-Net (specific mechanism) | Source (best support for datapoint) |
|---|--------|-----------------|--------------------------------------------|------------------------|----------------------------------------------|---------------------------------------------|-------------------------------------|
| 1 | **Helium Network (Nova Labs)** | Crypto-incentivized "patchwork" of cellular/IoT hotspots; carrier data-offload service ([Fortune](https://fortune.com/2026/06/02/andrew-yang-business-acquires-helium-mobile/)) | **2026-06-02:** Noble Mobile (Andrew Yang) acquiring Helium Mobile; Nova Labs retains the data-offloading business and pivots to carrier offload after closing a multi-year deal with a large U.S. carrier at end of 2025 ([Fortune](https://fortune.com/2026/06/02/andrew-yang-business-acquires-helium-mobile/)) | HNT/MOBILE token rewards to hotspot operators, under Helium DAO; Nova Labs monetizes via B2B data-offload deals with mobile network operators ([Fortune](https://fortune.com/2026/06/02/andrew-yang-business-acquires-helium-mobile/)); Helium Mobile posting ~$2.2M/mo revenue ([Syndica](https://blog.syndica.io/deep-dive-solana-depin-february-2026/)) | Helium is licensed-spectrum cellular + Wi-Fi offload for consumer phones; Tri-Net is 5.8 GHz UAV/drone mesh with SDR radios + silicon compute proof. Helium has no silicon-attestation anchor. | Proven carrier-offload PMF (multi-year U.S. carrier deal, $14M cumulative Helium Mobile revenue since Jan 2025) means Helium already monetizes real coverage at scale; it could extend offload/coverage incentives into edge-compute DePIN and out-distribute Tri-Net on operator relationships and node density before Tri-Net's mesh reaches critical mass ([Fortune](https://fortune.com/2026/06/02/andrew-yang-business-acquires-helium-mobile/), [Syndica](https://blog.syndica.io/deep-dive-solana-depin-february-2026/)) | [Fortune, 2026-06-02](https://fortune.com/2026/06/02/andrew-yang-business-acquires-helium-mobile/) |
| 2 | **Althea Network** | Althea L1 blockchain for machine-to-machine (M2M) micro-payments; router firmware for telecom routing/billing on mesh/last-mile ISPs ([Althea forum](https://forum.althea.net/t/development-update-althea-l1-token-unlock/729)) | **2025-10-14:** "Cardinal" upgrade adds stablecoin-only fee path + iFi DEX governance for M2M devices; follows **2025-09-08** governance vote enabling ALTHEA transfers/EVM gas (chain "unlocked") ([Althea blog](https://blog.althea.net/althea-update-cardinal/), [Althea forum](https://forum.althea.net/t/development-update-althea-l1-token-unlock/729)) | ALTHEA gas token + per-bandwidth M2M micro-payments between routers; "Liquid Infrastructure" brings ISP revenue on-chain; iFi DEX fees via governance ([Althea forum](https://forum.althea.net/t/development-update-althea-l1-token-unlock/729), [Althea blog](https://blog.althea.net/althea-update-cardinal/)) | Althea is a per-packet billing/settlement layer for last-mile ISP routers (fiber/Wi-Fi), not a physical RF mesh; it sells the payment rails, not the radio or silicon-proof. Tri-Net owns the RF+silicon stack. | Althea's out-of-the-box "appliance exit" firmware and stablecoin M2M rails could become the default settlement layer any mesh (incl. Tri-Net-style networks) plugs into — capturing the economic/billing slice of decentralized wireless without owning hardware, undercutting Tri-Net's need for a bespoke token economy ([Althea forum](https://forum.althea.net/t/development-update-althea-l1-token-unlock/729)) | [Althea blog "Cardinal", 2025-10-14](https://blog.althea.net/althea-update-cardinal/) |
| 3 | **WeatherXM** | Community-powered weather-sensor DePIN; hyperlocal weather data sold to enterprises ([WeatherXM docs](https://docs.weatherxm.com/tokenomics)) | **Nov 2025:** "Targeted Rollouts" crowdfunding launched — 1,500 NFTs on Base (1 station = 4 NFTs, $100 mint) to fund/deploy new stations; 933 NFTs minted by 203 holders raising ~$81k in the referenced rollout ([WeatherXM Rollouts](https://rollouts.weatherxm.com/)) | WXM ERC-20 (100M capped supply, 10-yr emissions, 55% station rewards); enterprises must acquire WXM to license data; annual Commercial Data License auctions paid in WXM (100,000 WXM per license) ([WeatherXM docs](https://docs.weatherxm.com/tokenomics), [WeatherXM blog](https://blog.weatherxm.com/we-acquired-one-of-the-2025-weatherxm-commercial-data-licenses-bb9487bf33f0)) | WeatherXM's sensor arm is passive environmental telemetry (weather), not an active RF transport/coverage mesh; no drone/UAV mobility and no silicon-attestation. Overlaps Tri-Net only as a "sensor-arm analogue." | Its NFT-crowdfunded station-deployment playbook and data-license auction model are a proven template for bootstrapping physical-sensor DePIN density and enterprise demand; if extended to RF/coverage sensing it could occupy the "verifiable physical-data" market slot Tri-Net wants for edge compute ([WeatherXM Rollouts](https://rollouts.weatherxm.com/), [WeatherXM blog](https://blog.weatherxm.com/we-acquired-one-of-the-2025-weatherxm-commercial-data-licenses-bb9487bf33f0)) | [WeatherXM Targeted Rollouts](https://rollouts.weatherxm.com/) |
| 4 | **XNET** | Neutral-host, carrier-grade decentralized Wi-Fi / 5G offload network (Passpoint) for MSPs/ISPs ([XNET blog](https://xnetmobile.com/blog)) | **Feb 2026:** data offload jumped 32% to 107 TB — first month above 100 TB — per Syndica; AT&T customers can access XNET's 1,300+ commercial-location Passpoint Wi-Fi network ([Syndica](https://blog.syndica.io/deep-dive-solana-depin-february-2026/), [XNET blog](https://xnetmobile.com/blog)) | $XNET token rewards deployers/node operators; deflationary tokenomics (XIP-10/XIP-11 mint-and-burn from offload revenue); enterprise offload contracts with carriers ([Syndica](https://blog.syndica.io/deep-dive-solana-depin-february-2026/)) | XNET is fixed-venue carrier-grade Wi-Fi/CBRS offload (hotels, stadiums, campuses) via Passpoint; Tri-Net is mobile 5.8 GHz drone mesh with silicon compute proof. XNET has no PUF/attestation identity layer. | XNET's "flip a switch" activation on existing venue infrastructure (Cambium partnership) plus AT&T reach lets it scale coverage nodes far faster and cheaper than Tri-Net's bespoke SDR hardware, capturing the neutral-host coverage slot with real carrier offload revenue ([Syndica](https://blog.syndica.io/deep-dive-solana-depin-february-2026/), [XNET blog](https://xnetmobile.com/blog)) | [Syndica Solana DePIN Feb 2026](https://blog.syndica.io/deep-dive-solana-depin-february-2026/) |
| 5 | **Pollen Mobile / DIMO** | Pollen: plug-and-play decentralized private cellular (small-cell radios, up to 170 Mbps DL). DIMO: decentralized automotive/vehicle data protocol ([Pollen Mobile](https://www.pollenmobile.io), [DIMO news](https://dimo.org/news)) | **DIMO 2025-11-07:** bridge exploit drained ~30M DIMO (~3% supply) via compromised dev key; core network unaffected. Pollen freshest verifiable item: "The Next Phase For Pollen Mobile: Paid Data" (no dated primary source; date `n.a.`) ([CoinMarketCap DIMO](https://coinmarketcap.com/cmc-ai/dimo/latest-updates/), [Pollen Mobile](https://www.pollenmobile.io)) | Pollen: mobile-coverage DePIN (own/operate radios, "coverage on demand"), token rewards for deployers (details `n.a.` from primary). DIMO: DIMO token rewards drivers for vehicle data; API/data-licensing to enterprises; developer console/WaaS ([Pollen Mobile](https://www.pollenmobile.io), [CoinMarketCap DIMO](https://coinmarketcap.com/cmc-ai/dimo/latest-updates/)) | Pollen is user-owned private small-cell coverage (no silicon-proof); DIMO is a vehicle-data DePIN (telematics, not RF transport). Neither has UAV mesh, ETX routing, or FPGA/PUF attestation. | DIMO's automaker courtship + developer console/API monetization could lock up the "verified physical-device data + on-chain identity" market for vehicles; combined with Pollen's cheap plug-and-play coverage radios, they normalize "own your node + monetize data" DePIN UX and set buyer expectations Tri-Net must beat — but DIMO's Nov-2025 bridge exploit shows the same key-compromise/sybil risk Tri-Net's PUF identity is meant to solve ([CoinMarketCap DIMO](https://coinmarketcap.com/cmc-ai/dimo/latest-updates/), [Pollen Mobile](https://www.pollenmobile.io)) | [CoinMarketCap DIMO updates](https://coinmarketcap.com/cmc-ai/dimo/latest-updates/) |
| 6 | **GEODNET** | Decentralized GNSS/RTK network — centimeter-accurate positioning from 21,000+ community base stations across 160 countries ([CoinGabbar](https://www.coingabbar.com/en/crypto-currency-news/geodnet-token-listing-coinbase-june-2026-geod-price-today)) | **2026-06-23:** GEOD spot trading went live on Coinbase (GEOD-USD, 9 AM PT); network at 20,000+ base stations, ~$200K weekly on-chain revenue; $8M GEOD purchase led by Multicoin ([CoinGabbar](https://www.coingabbar.com/en/crypto-currency-news/geodnet-token-listing-coinbase-june-2026-geod-price-today), [Distill](https://www.distillintelligence.com/news/geodnet)) | GEOD token: operators earn GEOD for validated correction data; **80% of network revenue funds GEOD buyback-and-burn** (deflationary); ~$7.8M annualized revenue; RTK hardware sales + subscriptions via HYFIX store ([CoinGabbar](https://www.coingabbar.com/en/crypto-currency-news/geodnet-token-listing-coinbase-june-2026-geod-price-today), [Our Crypto Talk](https://ourcryptotalk.com/news/geodnet-official-store-launch-rtk)) | GEODNET is a positioning/correction-data DePIN (GNSS RTK), not RF transport or compute; no drone mesh, no silicon-attestation. Overlaps Tri-Net only as a mature "physical-infrastructure with real revenue" benchmark. | GEODNET is the clearest proof that a DePIN with genuine enterprise revenue + revenue-funded token buyback/burn can list on a Tier-1 exchange and scale to 20k+ nodes; it sets the bar for "real utility + sustainable tokenomics" that Tri-Net's fair-launch/halving model will be judged against, and could bundle precise-positioning into drone/UAV navigation — Tri-Net's own domain ([CoinGabbar](https://www.coingabbar.com/en/crypto-currency-news/geodnet-token-listing-coinbase-june-2026-geod-price-today), [Distill](https://www.distillintelligence.com/news/geodnet)) | [CoinGabbar GEOD Coinbase, 2026-06-23](https://www.coingabbar.com/en/crypto-currency-news/geodnet-token-listing-coinbase-june-2026-geod-price-today) |

### Read-outs — Axis A (biggest threat vector)

The sharpest threat to Tri-Net's Transport/Coverage arm is **Helium/Nova Labs' proven carrier data-offload business** ([Fortune](https://fortune.com/2026/06/02/andrew-yang-business-acquires-helium-mobile/)). By spinning off consumer Helium Mobile to Noble Mobile and focusing on B2B offload deals with large U.S. carriers, Nova Labs has demonstrated the one thing Tri-Net has not: that a decentralized coverage network can sign real, multi-year revenue contracts with incumbent operators, on top of ~$14M cumulative Helium Mobile revenue since Jan 2025 ([Fortune](https://fortune.com/2026/06/02/andrew-yang-business-acquires-helium-mobile/), [Syndica](https://blog.syndica.io/deep-dive-solana-depin-february-2026/)). The secondary threat is **XNET's asset-light "flip a switch" venue activation** ([XNET blog](https://xnetmobile.com/blog)), which scales coverage nodes far faster and cheaper than Tri-Net's custom AD9361 SDR hardware, while **GEODNET** proves the market rewards DePIN with actual enterprise revenue and revenue-funded token burns — the exact economic legitimacy test Tri-Net's 0%-premine/halving token must pass ([CoinGabbar](https://www.coingabbar.com/en/crypto-currency-news/geodnet-token-listing-coinbase-june-2026-geod-price-today)). None of these competitors have a silicon-attestation moat, which remains Tri-Net's clearest differentiator on this axis.

---

## Axis B — FPGA / PUF / silicon-attestation vendors

| # | Entity | Primary product | Most recent public datapoint (date + what) | Token / business model | Differentiator from Tri-Net (overlapping arm) | Open threat to Tri-Net (specific mechanism) | Source (best support for datapoint) |
|---|--------|-----------------|--------------------------------------------|------------------------|----------------------------------------------|---------------------------------------------|-------------------------------------|
| 7 | **Intrinsic ID (now Synopsys)** | SRAM-PUF IP for generating on-chip unique identifiers / root keys in SoCs ([Synopsys](https://news.synopsys.com/2024-03-20-Synopsys-Expands-Semiconductor-IP-Portfolio-With-Acquisition-of-Intrinsic-ID)) | **2024-03-20:** Synopsys completed acquisition of Intrinsic ID; PUF IP folded into Synopsys' semiconductor IP portfolio; PUF center of excellence established in Eindhoven ([Synopsys](https://news.synopsys.com/2024-03-20-Synopsys-Expands-Semiconductor-IP-Portfolio-With-Acquisition-of-Intrinsic-ID)) | Semiconductor IP licensing (license fees + royalties), now inside Synopsys' DesignWare/IP business; deal terms undisclosed, "not material" to Synopsys ([Synopsys](https://news.synopsys.com/2024-03-20-Synopsys-Expands-Semiconductor-IP-Portfolio-With-Acquisition-of-Intrinsic-ID)) | Intrinsic ID/Synopsys sells PUF as licensable SoC IP to chipmakers for device identity/key gen — a component sold to silicon vendors. Tri-Net uses FPGA-PUF attestation as a network-level sybil-resistance primitive with a token economy, not as IP for sale. | As part of Synopsys (the dominant EDA/IP vendor), SRAM-PUF becomes a near-default, broadly-licensed identity primitive in commodity SoCs; if PUF-based device identity ships ubiquitously in standard chips, Tri-Net's "Proof-of-FPGA" ceases to be a differentiator and its custom FPGA-attestation could be undercut by cheaper, standardized silicon identity already in every device ([Synopsys](https://news.synopsys.com/2024-03-20-Synopsys-Expands-Semiconductor-IP-Portfolio-With-Acquisition-of-Intrinsic-ID)) | [Synopsys press, 2024-03-20](https://news.synopsys.com/2024-03-20-Synopsys-Expands-Semiconductor-IP-Portfolio-With-Acquisition-of-Intrinsic-ID) |
| 8 | **PUFsecurity** | PUF-based hardware root-of-trust IP: PUFrt (Root of Trust), PUFcc (crypto coprocessor), PUFhsm, PUF-PQC (subsidiary of eMemory) ([PUFsecurity](https://www.pufsecurity.com/about-us/)) | **2026-01-16:** PUF-PQC (with eMemory) achieved NIST FIPS 205 (SLH-DSA) + SP 800-208 certification, completing full coverage of NIST PQC standards (adds to prior FIPS 203/204) ([eMemory](https://www.ememory.com.tw/en-US/News/News?guid=26011610540360), [PUFsecurity](https://www.pufsecurity.com/category/company-news/)) | Security IP licensing (license + royalty) built on eMemory's NeoPUF; embeds into third-party SoCs; **2025-10-31** PUFrt anchored Silicon Labs Series 3 SoC to industry-first PSA Certified Level 4 ([PUFsecurity](https://www.pufsecurity.com/category/company-news/)) | PUFsecurity licenses NeoPUF root-of-trust + PQC IP into chips (BMC SoCs, SSD controllers, IoT); it sells attestation-as-IP. Tri-Net builds a DePIN sybil-resistance layer + Trinity ASIC on top of PUF, not IP-for-license. | PUFsecurity's NIST-certified PUF-PQC + PSA-L4 root-of-trust makes standardized, quantum-safe silicon identity available off-the-shelf to any chipmaker; a competing DePIN could license PUFrt/PUF-PQC and reach certified, quantum-resilient device attestation faster than Tri-Net can tape out its custom Trinity ASIC (projected 2026-12-16), neutralizing Tri-Net's silicon-anchor lead ([eMemory](https://www.ememory.com.tw/en-US/News/News?guid=26011610540360), [PUFsecurity](https://www.pufsecurity.com/category/company-news/)) | [eMemory/PUFsecurity PUF-PQC NIST, 2026-01-16](https://www.ememory.com.tw/en-US/News/News?guid=26011610540360) |
| 9 | **Verayo** | (Historical) Silicon-PUF ("Silicon DNA") authentication/key-generation IP, incl. FPGA/ASIC/RFID; PUF invented at MIT by Srini Devadas ([PR Newswire](https://www.prnewswire.com/news-releases/verayo-puf-ip-on-xilinx-zynq-ultrascale-mpsoc-devices-addresses-security-demands-300357805.html)) | **Status: OUT OF BUSINESS** — PitchBook lists Verayo as "Out of Business" (out-of-business event dated 01-Jan-2019); Semiconductor Engineering (2020) reports the company "appears to have closed down," website blank ([PitchBook](https://pitchbook.com/profiles/company/55111-87), [Semiconductor Engineering](https://semiengineering.com/pufs-promise-better-security/)) | (Historical) PUF IP licensing + PUF-enabled RFID chip sales; funded by Khosla Ventures, raised ~$3.05M; had licensed PUF IP into Xilinx Zynq UltraScale+ MPSoC ([PitchBook](https://pitchbook.com/profiles/company/55111-87), [PR Newswire](https://www.prnewswire.com/news-releases/verayo-puf-ip-on-xilinx-zynq-ultrascale-mpsoc-devices-addresses-security-demands-300357805.html)) | Verayo pioneered arbiter/"strong" PUF for FPGAs and RFID authentication, closest in spirit to Tri-Net's FPGA-PUF concept — but it is defunct, so it is a cautionary precedent, not an active competitor. Strong-PUF never proved commercially secure enough at scale ([Semiconductor Engineering](https://semiengineering.com/pufs-promise-better-security/)). | Minimal direct threat (defunct). The relevant lesson: Verayo's failure shows FPGA/strong-PUF authentication as a standalone business is hard to sustain commercially — a risk flag for Tri-Net if Proof-of-FPGA is treated as the product rather than as one primitive inside a broader DePIN economy ([PitchBook](https://pitchbook.com/profiles/company/55111-87), [Semiconductor Engineering](https://semiengineering.com/pufs-promise-better-security/)) | [PitchBook Verayo (Out of Business)](https://pitchbook.com/profiles/company/55111-87) |
| 10 | **eMemory Technology** | Logic-based NVM IP (NeoFuse OTP, NeoBit) + PUF security IP (NeoPUF); parent of PUFsecurity; supplies 2,400+ foundries/fabless firms ([eMemory](https://www.ememory.com.tw/en-US/News/News?guid=26011610540360)) | **2026-05:** Q1 2026 earnings — PUF-based revenue licensing up 21.5% QoQ / **606.9% YoY**; partnering with **Intel Foundry to implement PUF-based IP on Intel 18A** for U.S. gov't supply-chain security ([Quartr](https://quartr.com/companies/ememory-technology-inc_15790), [Yahoo Finance](https://finance.yahoo.com/markets/stocks/articles/ememory-technology-inc-roco-3529-030030531.html)) | Semiconductor IP licensing + per-chip royalties (NeoFuse 59.8% of Q1 rev, NeoBit 20%, PUF-based 12.2%, MTP 8%); publicly traded (TPEx/ROCO:3529) ([Quartr](https://quartr.com/companies/ememory-technology-inc_15790)) | eMemory is the foundational NVM+PUF IP licensor whose NeoPUF underpins PUFsecurity; it sells silicon-identity IP to the entire foundry ecosystem. Tri-Net consumes PUF as a network primitive; eMemory would be a supplier/rival at the IP layer, not a DePIN. | With PUF-based IP already in 20+ SSD controllers, mainstream BMC chips, and now targeting Intel 18A, eMemory is making hardware root-of-trust a ubiquitous, foundry-standard feature; if silicon identity is baked into virtually all advanced-node chips, Tri-Net's bespoke Proof-of-FPGA/Trinity ASIC loses scarcity value and any competitor can source certified silicon identity as a commodity ([Quartr](https://quartr.com/companies/ememory-technology-inc_15790), [Yahoo Finance](https://finance.yahoo.com/markets/stocks/articles/ememory-technology-inc-roco-3529-030030531.html)) | [Quartr eMemory Q1 2026](https://quartr.com/companies/ememory-technology-inc_15790) |

### Read-outs — Axis B (biggest threat vector)

The dominant threat to Tri-Net's silicon-anchor arm is **the commoditization of PUF-based device identity by the eMemory / PUFsecurity / Synopsys(Intrinsic ID) bloc** ([eMemory](https://www.ememory.com.tw/en-US/News/News?guid=26011610540360), [Synopsys](https://news.synopsys.com/2024-03-20-Synopsys-Expands-Semiconductor-IP-Portfolio-With-Acquisition-of-Intrinsic-ID)). eMemory's PUF licensing grew ~607% YoY and is now targeting Intel 18A, while PUFsecurity's PUF-PQC holds full NIST PQC certification (FIPS 203/204/205 + SP 800-208) and PSA Level 4 ([Quartr](https://quartr.com/companies/ememory-technology-inc_15790), [eMemory](https://www.ememory.com.tw/en-US/News/News?guid=26011610540360)). The mechanism of harm is standardization: if certified, quantum-safe silicon root-of-trust ships as a licensable, foundry-standard block in commodity SoCs, then any rival DePIN can license the same attestation off-the-shelf and reach it *before* Tri-Net's custom Trinity ASIC tapes out (projected 2026-12-16) — collapsing Tri-Net's "silicon anchor for compute proof" from a moat into a table-stakes feature. **Verayo** is the cautionary tail: the original FPGA/strong-PUF authentication startup is defunct ([PitchBook](https://pitchbook.com/profiles/company/55111-87)), underscoring that Proof-of-FPGA survives only as one primitive inside Tri-Net's broader DePIN economy, not as a standalone product.

---

## Method

**URLs fetched (this session):**
- https://fortune.com/2026/06/02/andrew-yang-business-acquires-helium-mobile/ — Helium/Nova Labs/Noble Mobile acquisition (fetched OK)
- https://www.coingabbar.com/en/crypto-currency-news/geodnet-token-listing-coinbase-june-2026-geod-price-today — GEODNET Coinbase listing (fetched OK)
- https://www.distillintelligence.com/news/geodnet — GEODNET funding/base stations/revenue (fetched OK)
- https://blog.althea.net/althea-update-cardinal/ — Althea Cardinal upgrade (fetched OK)
- https://announcements.weatherxm.com/ — WeatherXM announcements (fetched OK; no 2026 items on index)
- https://www.pollenmobile.io — Pollen Mobile product/status (fetched OK; no dated news)
- https://blog.weatherxm.com/ — WeatherXM blog index (fetched OK; latest post "Preparing for the Next Era of $WXM," May 20)
- https://xnetmobile.com/blog — XNET blog (fetched OK; post dates not exposed on page)
- https://dimo.org/news — DIMO news (fetched OK; latest visible item July 2025)
- https://www.ememory.com.tw/en-US/News/News?guid=26011610540360 — eMemory/PUFsecurity PUF-PQC NIST FIPS 205 (fetched OK)
- https://www.pufsecurity.com/category/company-news/ — PUFsecurity company news list (fetched OK)
- Search-surfaced content used with in-text citation (via search_web result bodies, then corroborated): Synopsys press release (news.synopsys.com/2024-03-20...), PitchBook Verayo profile, Semiconductor Engineering PUF article, Syndica Solana DePIN Feb 2026, CoinMarketCap DIMO updates, Quartr eMemory Q1 2026, Yahoo Finance eMemory Q1 2026 call, WeatherXM Rollouts (rollouts.weatherxm.com), WeatherXM docs/blog data-license posts, PR Newswire Verayo/Xilinx.

**Could not fetch / not confirmed:**
- https://blog.weatherxm.com/preparing-for-the-next-era-of-wxm/ — returned 404 (Medium). WeatherXM's freshest fully-primary datapoint was taken from the Rollouts site (Nov 2025) and docs instead.
- WeatherXM "2026 Data License Auction Winners" precise winners — only surfaced via a Reddit thread (not cited per rules); the auction *mechanism* and WXM licensing model were confirmed from WeatherXM docs and the company's own 2025 license-acquisition blog post. Exact 2026 winner list: `n.a.` from primary.
- Pollen Mobile token/tokenomics and a dated 2026 news item — no dated primary source located; marked `n.a.`
- XNET exact publication dates for individual blog posts — not exposed on the blog page; offload metrics/date sourced from Syndica (Feb 2026) instead.

phi^2 + phi^-2 = 3
