// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_BLOCKS: u32 = 16;

pub const BLOCK_SIZE: u32 = 32;

pub const COMPRESSION_THRESHOLD: u32 = 8;

pub const DICTIONARY_SIZE: u32 = 8;

pub fn create_block_info(orig_size: u32, comp_size: u32, method: u32, quality: u32) -> u32 {
    return (((((orig_size & 0xFF) << 24) | ((comp_size & 0xFF) << 16)) | ((method & 0x3) << 14)) | (quality & 0x3FFF));
}

pub fn get_original_size(info: u32) -> u32 {
    return ((info >> 24) & 0xFF);
}

pub fn get_compressed_size(info: u32) -> u32 {
    return ((info >> 16) & 0xFF);
}

pub fn get_compression_method(info: u32) -> u32 {
    return ((info >> 14) & 0x3);
}

pub fn get_compression_quality(info: u32) -> u32 {
    return (info & 0x3FFF);
}

pub const METHOD_NONE: u32 = 0;

pub const METHOD_RLE: u32 = 1;

pub const METHOD_DICTIONARY: u32 = 2;

pub const METHOD_DELTA: u32 = 3;

pub fn calculate_compression_ratio(original: u32, compressed: u32) -> u32 {
    if (compressed > 0) {
        return ((original * 100) / compressed);
    } else {
        return 100;
    }
}

pub fn compress_rle(data: u32, length: u32) -> u32 {
    let mut compressed: u32 = 0;
    let mut count: u32 = 0;
    let mut current: u32 = (data & 0xF);
    let mut i: u32 = 0;
    while ((i < length) && (i < 8)) {
        let value: u32 = ((data >> (i * 4)) & 0xF);
        if (value == current) {
            count = (count + 1);
        } else {
            compressed = ((compressed << 4) | count);
            compressed = ((compressed << 4) | current);
            current = value;
            count = 1;
        }
        i = (i + 1);
    }
    compressed = ((compressed << 4) | count);
    compressed = ((compressed << 4) | current);
    return compressed;
}

pub fn decompress_rle(compressed: u32) -> u32 {
    let mut decompressed: u32 = 0;
    let mut pos: u32 = 0;
    while (pos < 32) {
        let count: u32 = ((compressed >> pos) & 0xF);
        let value: u32 = ((compressed >> (pos + 4)) & 0xF);
        let mut i: u32 = 0;
        while ((i < count) && (i < 8)) {
            decompressed = ((decompressed << 4) | value);
            i = (i + 1);
        }
        pos = (pos + 8);
    }
    return decompressed;
}

pub fn compress_dictionary(data: u32, dictionary: [u32; DICTIONARY_SIZE as usize]) -> u32 {
    let mut best_match: u32 = 0;
    let mut best_score: u32 = 0;
    let mut i: u32 = 0;
    while (i < DICTIONARY_SIZE) {
        let dict_value: u32 = dictionary[(i) as usize];
        let mut score: u32 = 0;
        let mut j: u32 = 0;
        while (j < 8) {
            let data_nibble: u32 = ((data >> (j * 4)) & 0xF);
            let dict_nibble: u32 = ((dict_value >> (j * 4)) & 0xF);
            if (data_nibble == dict_nibble) {
                score = (score + 1);
            }
            j = (j + 1);
        }
        if (score > best_score) {
            best_score = score;
            best_match = i;
        }
        i = (i + 1);
    }
    return best_match;
}

pub fn decompress_dictionary(index: u32, dictionary: [u32; DICTIONARY_SIZE as usize]) -> u32 {
    if (index < DICTIONARY_SIZE) {
        return dictionary[(index) as usize];
    } else {
        return 0;
    }
}

pub fn compress_delta(data: u32, previous: u32) -> u32 {
    let mut delta: u32 = 0;
    if (data > previous) {
        delta = (data - previous);
    } else {
        delta = (previous - data);
    }
    if (delta < 16) {
        return delta;
    } else {
        if (delta < 256) {
            return (0x10 | (delta & 0xFF));
        } else {
            return (0x20 | (delta & 0xFFF));
        }
    }
}

pub fn decompress_delta(encoded: u32, previous: u32) -> u32 {
    let encoding_type: u32 = ((encoded >> 4) & 0x3);
    let value: u32 = (encoded & 0xF);
    if (encoding_type == 0) {
        if (previous > value) {
            return (previous - value);
        } else {
            return (previous + value);
        }
    } else {
        if (encoding_type == 1) {
            let delta: u32 = (encoded & 0xFF);
            if (previous > delta) {
                return (previous - delta);
            } else {
                return (previous + delta);
            }
        } else {
            let delta: u32 = (encoded & 0xFFF);
            if (previous > delta) {
                return (previous - delta);
            } else {
                return (previous + delta);
            }
        }
    }
}

pub fn choose_compression_method(data: u32, previous: u32, dictionary: [u32; DICTIONARY_SIZE as usize]) -> u32 {
    let data_nibbles: u32 = 8;
    let rle_compressed: u32 = compress_rle(data, data_nibbles);
    let rle_ratio: u32 = calculate_compression_ratio(data_nibbles, rle_compressed);
    let delta_compressed: u32 = compress_delta(data, previous);
    let mut delta_size: u32 = 0;
    if (delta_compressed < 16) {
        delta_size = 1;
    } else {
        if (delta_compressed < 256) {
            delta_size = 2;
        } else {
            delta_size = 3;
        }
    }
    let delta_ratio: u32 = calculate_compression_ratio(data_nibbles, delta_size);
    if ((rle_ratio > delta_ratio) && (rle_ratio > 120)) {
        return METHOD_RLE;
    } else {
        if (delta_ratio > 120) {
            return METHOD_DELTA;
        } else {
            return METHOD_NONE;
        }
    }
}

pub fn compress_block(data: u32, previous: u32, dictionary: [u32; DICTIONARY_SIZE as usize]) -> u32 {
    let method: u32 = choose_compression_method(data, previous, dictionary);
    let mut compressed: u32 = 0;
    let mut compressed_size: u32 = 8;
    if (method == METHOD_RLE) {
        compressed = compress_rle(data, 8);
        compressed_size = 4;
    } else {
        if (method == METHOD_DELTA) {
            compressed = compress_delta(data, previous);
            if (compressed < 16) {
                compressed_size = 1;
            } else {
                if (compressed < 256) {
                    compressed_size = 2;
                } else {
                    compressed_size = 3;
                }
            }
        } else {
            compressed = data;
            compressed_size = 8;
        }
    }
    return create_block_info(8, compressed_size, method, compressed_size);
}

pub fn decompress_block(compressed_data: u32, method: u32, previous: u32, dictionary: [u32; DICTIONARY_SIZE as usize]) -> u32 {
    if (method == METHOD_RLE) {
        return decompress_rle(compressed_data);
    } else {
        if (method == METHOD_DELTA) {
            return decompress_delta(compressed_data, previous);
        } else {
            if (method == METHOD_DICTIONARY) {
                return decompress_dictionary(compressed_data, dictionary);
            } else {
                return compressed_data;
            }
        }
    }
}

pub fn calculate_total_savings(blocks: [u32; MAX_BLOCKS as usize], count: u32) -> u32 {
    let mut total_original: u32 = 0;
    let mut total_compressed: u32 = 0;
    let mut i: u32 = 0;
    while (i < count) {
        total_original = (total_original + get_original_size(blocks[(i) as usize]));
        total_compressed = (total_compressed + get_compressed_size(blocks[(i) as usize]));
        i = (i + 1);
    }
    if (total_compressed > 0) {
        return (((total_original - total_compressed) * 100) / total_original);
    } else {
        return 0;
    }
}

pub fn update_dictionary(dictionary: [u32; DICTIONARY_SIZE as usize], new_entry: u32, index: u32) -> u32 {
    if (index < DICTIONARY_SIZE) {
        dictionary[(index) as usize] = new_entry;
        return 1;
    } else {
        return 0;
    }
}

pub fn find_pattern(data: u32, pattern: u32) -> u32 {
    let mask: u32 = 0xFFFFFFFF;
    let mut i: u32 = 0;
    while (i < 32) {
        let shifted: u32 = ((data >> i) & mask);
        if (shifted == pattern) {
            return i;
        }
        i = (i + 4);
    }
    return 32;
}

pub fn calculate_compression_speed(original_size: u32, compressed_size: u32, time_ms: u32) -> u32 {
    if (time_ms > 0) {
        return ((original_size * 1000) / time_ms);
    } else {
        return 0;
    }
}

