// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const RECOVERY_COOLDOWN: u32 = 5000;

pub const MAX_RECOVERY_ATTEMPTS: u32 = 3;

pub const RECOVERY_SUCCESS: u32 = 1;

pub const RECOVERY_FAILED: u32 = 0;

pub fn create_recovery_state(attempts: u32, last_attempt: u32, in_progress: u32, success_count: u32) -> u32 {
    return (((((attempts & 0xFF) << 24) | ((last_attempt & 0xFF) << 16)) | ((in_progress & 0x1) << 8)) | (success_count & 0xFF));
}

pub fn get_attempts(state: u32) -> u32 {
    return ((state >> 24) & 0xFF);
}

pub fn get_last_attempt(state: u32) -> u32 {
    return ((state >> 16) & 0xFF);
}

pub fn get_in_progress(state: u32) -> u32 {
    return ((state >> 8) & 0x1);
}

pub fn get_success_count(state: u32) -> u32 {
    return (state & 0xFF);
}

pub fn can_recover(state: u32, current_time: u32) -> bool {
    let;
    let;
    last = get_last_attempt(state);
    let;
    if (attempts >= MAX_RECOVERY_ATTEMPTS) {
        return false;
    }
    if (in_progress == 1) {
        return false;
    }
    let;
    elapsed = (current_time - last);
    return (elapsed >= RECOVERY_COOLDOWN);
}

pub fn start_recovery(state: u32, current_time: u32) -> u32 {
    let;
    attempts = get_attempts(state);
    let;
    success_count = get_success_count(state);
    return create_recovery_state(attempts, current_time, 1, success_count);
}

pub fn complete_recovery_success(state: u32) -> u32 {
    let;
    attempts = get_attempts(state);
    let;
    last = get_last_attempt(state);
    let;
    success_count = get_success_count(state);
    return create_recovery_state(attempts, last, 0, (success_count + 1));
}

pub fn complete_recovery_failure(state: u32) -> u32 {
    let;
    attempts = get_attempts(state);
    let;
    last = get_last_attempt(state);
    let;
    success_count = get_success_count(state);
    return create_recovery_state((attempts + 1), last, 0, success_count);
}

pub fn reset_recovery(state: u32) -> u32 {
    return create_recovery_state(0, 0, 0, 0);
}

pub fn is_recovery_failed(state: u32) -> bool {
    return (get_attempts(state) >= MAX_RECOVERY_ATTEMPTS);
}

pub fn create_network_state(healthy_nodes: u32, total_nodes: u32, degraded_links: u32, total_links: u32) -> u32 {
    return (((((healthy_nodes & 0xFF) << 24) | ((total_nodes & 0xFF) << 16)) | ((degraded_links & 0xFF) << 8)) | (total_links & 0xFF));
}

pub fn get_healthy_nodes(state: u32) -> u32 {
    return ((state >> 24) & 0xFF);
}

pub fn get_total_nodes(state: u32) -> u32 {
    return ((state >> 16) & 0xFF);
}

pub fn get_degraded_links(state: u32) -> u32 {
    return ((state >> 8) & 0xFF);
}

pub fn get_total_links(state: u32) -> u32 {
    return (state & 0xFF);
}

pub fn network_health_percent(state: u32) -> u32 {
    let;
    healthy = get_healthy_nodes(state);
    let;
    total = get_total_nodes(state);
    if (total == 0) {
        return 100;
    }
    return ((healthy * 100) / total);
}

pub fn is_network_healthy(state: u32) -> bool {
    return (network_health_percent(state) >= 75);
}

pub fn is_network_degraded(state: u32) -> bool {
    let;
    health = network_health_percent(state);
    return ((health >= 50) && (health < 75));
}

pub fn is_network_critical(state: u32) -> bool {
    return (network_health_percent(state) < 50);
}

pub fn should_initiate_healing(recovery_state: u32, network_state: u32, current_time: u32) -> u32 {
    if is_network_healthy(network_state) {
        return 0;
    }
    if can_recover(recovery_state, current_time) {
        return 1;
    }
    return 2;
}

pub fn update_network_after_recovery(network_state: u32, nodes_recovered: u32, links_restored: u32) -> u32 {
    let;
    healthy = (get_healthy_nodes(network_state) + nodes_recovered);
    let;
    total = get_total_nodes(network_state);
    let;
    degraded = (get_degraded_links(network_state) - links_restored);
    let;
    total_links = get_total_links(network_state);
    return create_network_state(healthy, total, degraded, total_links);
}

