// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const VAL_PENDING: u32 = 0;

pub const VAL_RUNNING: u32 = 1;

pub const VAL_PASSED: u32 = 2;

pub const VAL_FAILED: u32 = 3;

pub const TEST_SIMULATION: u32 = 1;

pub const TEST_BIT_ACCURATE: u32 = 2;

pub const TEST_FPGA_BOARD: u32 = 3;

pub const TEST_REAL_WORLD: u32 = 4;

pub fn create_test_result(state: u32, test_type: u32, errors: u32, iterations: u32) -> u32 {
    return (((((state & 0x3) << 30) | ((test_type & 0xF) << 26)) | ((errors & 0x3FF) << 16)) | (iterations & 0xFFFF));
}

pub fn extract_state(result: u32) -> u32 {
    return ((result >> 30) & 0x3);
}

pub fn extract_test_type(result: u32) -> u32 {
    return ((result >> 26) & 0xF);
}

pub fn extract_errors(result: u32) -> u32 {
    return ((result >> 16) & 0x3FF);
}

pub fn extract_iterations(result: u32) -> u32 {
    return (result & 0xFFFF);
}

pub fn calculate_pass_rate(passed: u32, total: u32) -> u8 {
    if (total == 0) {
        return 0;
    }
}

pub fn test_passed(result: u32) -> bool {
    return ((extract_errors(result) == 0) && (extract_state(result) == VAL_PASSED));
}

pub fn bit_accurate(reference: u32, implementation: u32, tolerance_mask: u32) -> bool {
    return (((reference ^ implementation) & tolerance_mask) == 0);
}

pub fn fpga_board_ready(result: u32) -> bool {
    return ((extract_state(result) == VAL_PASSED) && (extract_test_type(result) == TEST_FPGA_BOARD));
}

pub fn create_packet_capture(src: u32, dst: u32, payload: u32, timestamp: u32) -> u32 {
    return (((((src & 0xFF) << 24) | ((dst & 0xFF) << 16)) | ((payload & 0xFF) << 8)) | (timestamp & 0xFF));
}

pub fn extract_capture_src(capture: u32) -> u32 {
    return ((capture >> 24) & 0xFF);
}

pub fn extract_capture_dst(capture: u32) -> u32 {
    return ((capture >> 16) & 0xFF);
}

pub fn extract_capture_payload(capture: u32) -> u32 {
    return ((capture >> 8) & 0xFF);
}

pub fn extract_capture_timestamp(capture: u32) -> u32 {
    return (capture & 0xFF);
}

pub fn create_performance_metric(metric_type: u32, value: u32, unit: u32) -> u32 {
    return ((((metric_type & 0xF) << 24) | ((value & 0xFFFFFF) << 4)) | (unit & 0xF));
}

pub fn extract_metric_type(metric: u32) -> u32 {
    return ((metric >> 24) & 0xF);
}

pub fn extract_metric_value(metric: u32) -> u32 {
    return ((metric >> 4) & 0xFFFFFF);
}

pub fn extract_metric_unit(metric: u32) -> u32 {
    return (metric & 0xF);
}

