// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const ST_IDLE: u8 = 0;

pub const ST_ENQUEUE: u8 = 1;

pub const ST_BUILD_HDR: u8 = 2;

pub const ST_TX_WAIT: u8 = 3;

pub const ST_ACKED: u8 = 4;

pub const ST_FAILED: u8 = 5;

pub const MAX_RETRIES: u8 = 5;

pub const BASE_RETRY_MS: u16 = 10;

pub const KIND_DATA: u8 = 1;

pub const VERSION: u8 = 1;

pub fn next_state(state: u8, frame_ready: bool, ack_received: bool, retries_exceeded: bool) -> u8 {
    if (state == ST_IDLE) {
        if frame_ready {
            return ST_ENQUEUE;
        } else {
            return ST_IDLE;
        }
    } else {
        if (state == ST_ENQUEUE) {
            return ST_BUILD_HDR;
        } else {
            if (state == ST_BUILD_HDR) {
                return ST_TX_WAIT;
            } else {
                if (state == ST_TX_WAIT) {
                    if ack_received {
                        return ST_ACKED;
                    } else {
                        if retries_exceeded {
                            return ST_FAILED;
                        } else {
                            return ST_TX_WAIT;
                        }
                    }
                } else {
                    if (state == ST_ACKED) {
                        return ST_IDLE;
                    } else {
                        if (state == ST_FAILED) {
                            return ST_IDLE;
                        } else {
                            return ST_IDLE;
                        }
                    }
                }
            }
        }
    }
}

pub fn retry_delay_ms(retry_count: u8, base_ms: u16) -> u16 {
    if (retry_count == 0) {
        return base_ms;
    } else {
        if (retry_count == 1) {
            return (base_ms * 2);
        } else {
            if (retry_count == 2) {
                return (base_ms * 4);
            } else {
                if (retry_count == 3) {
                    return (base_ms * 8);
                } else {
                    if (retry_count >= 4) {
                        return (base_ms * 16);
                    } else {
                        return base_ms;
                    }
                }
            }
        }
    }
}

pub fn is_retries_exceeded(retry_count: u8) -> bool {
    return (retry_count >= MAX_RETRIES);
}

pub fn increment_retry(retry_count: u8) -> u8 {
    if (retry_count >= MAX_RETRIES) {
        return MAX_RETRIES;
    } else {
        return (retry_count + 1);
    }
}

pub fn header_byte(kind: u8, src: u32, dst: u32, ttl: u8, idx: usize) -> u8 {
    if (idx == 0) {
        return VERSION;
    } else {
        if (idx == 1) {
            return kind;
        } else {
            if (idx == 2) {
                return ();
            } else {
                if (idx == 3) {
                    return ();
                } else {
                    if (idx == 4) {
                        return ();
                    } else {
                        if (idx == 5) {
                            return ();
                        } else {
                            if (idx == 6) {
                                return ();
                            } else {
                                if (idx == 7) {
                                    return ();
                                } else {
                                    if (idx == 8) {
                                        return ();
                                    } else {
                                        if (idx == 9) {
                                            return ();
                                        } else {
                                            if (idx == 10) {
                                                return ttl;
                                            } else {
                                                return 0;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

