// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const OPTIMISTIC: u8 = 230;

pub const DEAD_EPS: u8 = 38;

pub const ONE_FP: u16 = 256;

pub const ALPHA_HALF: u8 = 128;

pub fn alpha_from_window(window: u8) -> u8 {
    if (window == 10) {
        return 128;
    } else {
        return 160;
    }
}

pub fn bool_to_sample(b: bool) -> u8 {
    if b {
        return 255;
    } else {
        return 0;
    }
}

pub fn fp_mul(a: u8, b: u8) -> u8 {
    if ((a == 0) || (b == 0)) {
        return 0;
    }
    return ((((a as u16) * (b as u16)) >> 8) as u8);
}

pub fn ewma_update(est: u8, sample: u8, alpha: u8) -> u8 {
    if ((est == 255) && (sample == 255)) {
        return 255;
    }
    return (fp_mul(alpha, sample) + fp_mul(((ONE_FP - (alpha as u16)) as u8), est));
}

pub fn is_dead(ratio: u8) -> bool {
    return (ratio < DEAD_EPS);
}

pub fn calc_etx(forward: u8, reverse: u8) -> u16 {
    if (is_dead(forward) || is_dead(reverse)) {
        return 0xFFFF;
    }
    if ((forward >= 200) && (reverse >= 200)) {
        return ONE_FP;
    } else {
        if ((forward >= 100) && (reverse >= 200)) {
            return 512;
        } else {
            if ((forward >= 200) && (reverse >= 100)) {
                return 512;
            } else {
                if ((forward >= 50) && (reverse >= 50)) {
                    return 1024;
                } else {
                    return 2048;
                }
            }
        }
    }
}

