// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub fn get_sent(metrics: u32) -> u32 {
    return metrics;
}

pub fn inc_sent(metrics: u32) -> u32 {
    return (metrics + 1);
}

pub fn get_recv(metrics: u32) -> u32 {
    return metrics;
}

pub fn inc_recv(metrics: u32) -> u32 {
    return (metrics + 1);
}

pub fn get_success(metrics: u32) -> u32 {
    return metrics;
}

pub fn inc_success(metrics: u32) -> u32 {
    return (metrics + 1);
}

pub fn success_rate(sent: u32, success: u32) -> u8 {
    if (sent == 0) {
        return 100;
    }
    if (sent >= success) {
        return ();
    } else {
        return 0;
    }
}

