// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_ERRORS: u32 = 16;

pub const MAX_WARNINGS: u32 = 32;

pub const MAX_FUNCTIONS: u32 = 64;

pub const VIOLATION_THRESHOLD: u32 = 3;

pub fn create_validation_error(error_id: u32, error_type: u32, line: u32, severity: u32) -> u32 {
    return (((((error_id & 0xFF) << 24) | ((error_type & 0xF) << 20)) | ((line & 0xFF) << 12)) | (severity & 0xFFF));
}

pub fn get_error_id(error: u32) -> u32 {
    return ((error >> 24) & 0xFF);
}

pub fn get_error_type(error: u32) -> u32 {
    return ((error >> 20) & 0xF);
}

pub fn get_error_line(error: u32) -> u32 {
    return ((error >> 12) & 0xFF);
}

pub fn get_error_severity(error: u32) -> u32 {
    return (error & 0xFFF);
}

pub const ERROR_SYNTAX: u32 = 0;

pub const ERROR_TYPE_MISMATCH: u32 = 1;

pub const ERROR_CONSTRAINT_VIOLATION: u32 = 2;

pub const ERROR_UNDEFINED_SYMBOL: u32 = 3;

pub const ERROR_UNUSED_VARIABLE: u32 = 4;

pub const SEVERITY_ERROR: u32 = 0;

pub const SEVERITY_WARNING: u32 = 1;

pub const SEVERITY_INFO: u32 = 2;

pub fn create_function_signature(func_id: u32, params: u32, return_type: u32, visibility: u32) -> u32 {
    return (((((func_id & 0xFF) << 24) | ((params & 0xF) << 20)) | ((return_type & 0xF) << 16)) | (visibility & 0xFFFF));
}

pub fn get_sig_function_id(sig: u32) -> u32 {
    return ((sig >> 24) & 0xFF);
}

pub fn get_param_count(sig: u32) -> u32 {
    return ((sig >> 20) & 0xF);
}

pub fn get_return_type(sig: u32) -> u32 {
    return ((sig >> 16) & 0xF);
}

pub fn get_visibility(sig: u32) -> u32 {
    return (sig & 0xFFFF);
}

pub fn validate_function_signature(sig: u32) -> u32 {
    let;
    func_id;
    let;
    param_count;
    if (param_count > 8) {
        return create_validation_error(func_id, ERROR_CONSTRAINT_VIOLATION, 0, SEVERITY_ERROR);
    }
    let;
    return_type;
    if (return_type > 3) {
        return create_validation_error(func_id, ERROR_TYPE_MISMATCH, 0, SEVERITY_ERROR);
    }
    return 0;
}

pub fn create_constraint_check(constraint_id: u32, status: u32, description: u32, line: u32) -> u32 {
    return (((((constraint_id & 0xFF) << 24) | ((status & 0x3) << 22)) | ((description & 0xFF) << 14)) | (line & 0x3FFF));
}

pub fn get_constraint_id(check: u32) -> u32 {
    return ((check >> 24) & 0xFF);
}

pub fn get_constraint_status(check: u32) -> u32 {
    return ((check >> 22) & 0x3);
}

pub fn get_constraint_description(check: u32) -> u32 {
    return ((check >> 14) & 0xFF);
}

pub fn get_constraint_line(check: u32) -> u32 {
    return (check & 0x3FFF);
}

pub const CONSTRAINT_PASS: u32 = 0;

pub const CONSTRAINT_FAIL: u32 = 1;

pub const CONSTRAINT_SKIP: u32 = 2;

pub const CONSTRAINT_NO_FLOAT: u32 = 0;

pub const CONSTRAINT_NO_DYNAMIC_ARRAY: u32 = 1;

pub const CONSTRAINT_NO_BIGNUM: u32 = 2;

pub const CONSTRAINT_FIXED_SIZE_ONLY: u32 = 3;

pub const CONSTRAINT_INTEGER_ONLY: u32 = 4;

pub fn check_no_float_operations(line_content: u32) -> u32 {
    if ((line_content & 0xFFFF) == 0x666C) {
        return create_constraint_check(CONSTRAINT_NO_FLOAT, CONSTRAINT_FAIL, 1, 0);
    } else {
        return create_constraint_check(CONSTRAINT_NO_FLOAT, CONSTRAINT_PASS, 0, 0);
    }
}

pub fn check_no_dynamic_arrays(line_content: u32) -> u32 {
    if ((line_content & 0xFFFF) == 0x6D61) {
        return create_constraint_check(CONSTRAINT_NO_DYNAMIC_ARRAY, CONSTRAINT_FAIL, 2, 0);
    } else {
        return create_constraint_check(CONSTRAINT_NO_DYNAMIC_ARRAY, CONSTRAINT_PASS, 0, 0);
    }
}

pub fn check_integer_only(line_content: u32) -> u32 {
    let;
    has_float;
    if (has_float == 1) {
        return create_constraint_check(CONSTRAINT_INTEGER_ONLY, CONSTRAINT_FAIL, 4, 0);
    } else {
        return create_constraint_check(CONSTRAINT_INTEGER_ONLY, CONSTRAINT_PASS, 0, 0);
    }
}

pub fn create_type_check(var_id: u32, declared_type: u32, inferred_type: u32, line: u32) -> u32 {
    return (((((var_id & 0xFF) << 24) | ((declared_type & 0xF) << 20)) | ((inferred_type & 0xF) << 16)) | (line & 0xFFFF));
}

pub fn get_type_var_id(check: u32) -> u32 {
    return ((check >> 24) & 0xFF);
}

pub fn get_declared_type(check: u32) -> u32 {
    return ((check >> 20) & 0xF);
}

pub fn get_inferred_type(check: u32) -> u32 {
    return ((check >> 16) & 0xF);
}

pub fn get_type_line(check: u32) -> u32 {
    return (check & 0xFFFF);
}

pub fn perform_type_check(check: u32) -> u32 {
    let;
    declared;
    let;
    inferred;
    if (declared == inferred) {
        return 0;
    } else {
        return create_validation_error(get_type_var_id(check), ERROR_TYPE_MISMATCH, get_type_line(check), SEVERITY_ERROR);
    }
}

pub fn create_unused_check(var_id: u32, usage_count: u32, first_use: u32, last_use: u32) -> u32 {
    return (((((var_id & 0xFF) << 24) | ((usage_count & 0xFF) << 16)) | ((first_use & 0xFF) << 8)) | (last_use & 0xFF));
}

pub fn get_unused_var_id(check: u32) -> u32 {
    return ((check >> 24) & 0xFF);
}

pub fn get_usage_count(check: u32) -> u32 {
    return ((check >> 16) & 0xFF);
}

pub fn get_first_use(check: u32) -> u32 {
    return ((check >> 8) & 0xFF);
}

pub fn get_last_use(check: u32) -> u32 {
    return (check & 0xFF);
}

pub fn check_unused_variable(check: u32) -> u32 {
    let;
    usage_count;
    if (usage_count == 0) {
        return create_validation_error(get_unused_var_id(check), ERROR_UNUSED_VARIABLE, get_first_use(check), SEVERITY_WARNING);
    } else {
        return 0;
    }
}

pub fn create_validation_summary(errors: u32, warnings: u32, info: u32, status: u32) -> u32 {
    return (((((errors & 0xFF) << 24) | ((warnings & 0xFF) << 16)) | ((info & 0xFF) << 8)) | (status & 0xFF));
}

pub fn get_error_count(summary: u32) -> u32 {
    return ((summary >> 24) & 0xFF);
}

pub fn get_warning_count(summary: u32) -> u32 {
    return ((summary >> 16) & 0xFF);
}

pub fn get_info_count(summary: u32) -> u32 {
    return ((summary >> 8) & 0xFF);
}

pub fn get_validation_status(summary: u32) -> u32 {
    return (summary & 0xFF);
}

pub const VALIDATION_PASS: u32 = 0;

pub const VALIDATION_FAIL: u32 = 1;

pub const VALIDATION_WARNING: u32 = 2;

pub fn run_validation(errors: Vec<>, error_count: u32, warnings: Vec<>, warning_count: u32) -> u32 {
    let;
    total_errors;
    let;
    total_warnings;
    let;
    total_info;
    let;
    status;
    let;
    i;
    while (i < error_count) {
        let;
        severity;
        if (severity == SEVERITY_ERROR) {
            total_errors = (total_errors + 1);
        } else {
            if (severity == SEVERITY_WARNING) {
                total_warnings = (total_warnings + 1);
            } else {
                total_info = (total_info + 1);
            }
        }
        i = (i + 1);
    }
    i = 0;
    while (i < warning_count) {
        total_warnings = (total_warnings + 1);
        i = (i + 1);
    }
    if (total_errors > 0) {
        status = VALIDATION_FAIL;
    } else {
        if (total_warnings > VIOLATION_THRESHOLD) {
            status = VALIDATION_WARNING;
        }
    }
    return create_validation_summary(total_errors, total_warnings, total_info, status);
}

pub fn create_quality_metrics(complexity: u32, readability: u32, maintainability: u32, tech_debt: u32) -> u32 {
    return (((((complexity & 0xFF) << 24) | ((readability & 0xFF) << 16)) | ((maintainability & 0xFF) << 8)) | (tech_debt & 0xFF));
}

pub fn get_complexity(metrics: u32) -> u32 {
    return ((metrics >> 24) & 0xFF);
}

pub fn get_readability(metrics: u32) -> u32 {
    return ((metrics >> 16) & 0xFF);
}

pub fn get_maintainability(metrics: u32) -> u32 {
    return ((metrics >> 8) & 0xFF);
}

pub fn get_technical_debt(metrics: u32) -> u32 {
    return (metrics & 0xFF);
}

pub fn calculate_complexity(function_length: u32, branch_count: u32, loop_count: u32) -> u32 {
    let;
    complexity;
    if (function_length > 100) {
        complexity = (complexity + (function_length / 50));
    }
    if (complexity > 255) {
        complexity = 255;
    }
    return complexity;
}

pub fn is_quality_acceptable(metrics: u32) -> u32 {
    let;
    complexity;
    let;
    readability;
    let;
    maintainability;
    let;
    tech_debt;
    if (complexity > 20) {
        return 0;
    } else {
        if (readability < 60) {
            return 0;
        } else {
            if (maintainability < 60) {
                return 0;
            } else {
                if (tech_debt > 40) {
                    return 0;
                } else {
                    return 1;
                }
            }
        }
    }
}

pub fn generate_validation_report(summary: u32, metrics: u32, filename_id: u32) -> u32 {
    let;
    status;
    let;
    errors;
    let;
    warnings;
    let;
    quality_ok;
    return (((((status & 0xF) << 28) | ((errors & 0xFF) << 20)) | ((warnings & 0xFF) << 12)) | (quality_ok & 0xFFF));
}

