// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_NODES: u32 = 3;

pub const MAX_HOPS: u32 = 3;

pub const NODE_A: u32 = 1;

pub const NODE_B: u32 = 2;

pub const NODE_C: u32 = 3;

pub fn build_packet(src: u32, dst: u32, ttl: u8, payload: u8) -> u32 {
    return (((((src & 0xFF) << 24) | ((dst & 0xFF) << 16)) | (((ttl as u32) & 0xF) << 12)) | ((payload as u32) & 0xF));
}

pub fn extract_src(packet: u32) -> u32 {
    return ((packet >> 24) & 0xFF);
}

pub fn extract_dst(packet: u32) -> u32 {
    return ((packet >> 16) & 0xFF);
}

pub fn extract_ttl(packet: u32) -> u8 {
    return (((packet >> 12) & 0xF) as u8);
}

pub fn extract_payload(packet: u32) -> u8 {
    return ((packet & 0xF) as u8);
}

pub fn decrement_ttl(packet: u32) -> (u32, bool) {
    if (extract_ttl(packet) > 0) {
        return (((packet & 0xFFFF0FFF) | ((((extract_ttl(packet) - 1) as u32) & 0xF) << 12)), false);
    } else {
        return (packet, true);
    }
}

pub fn route_packet(src: u32, dst: u32, next_hop: u32) -> u32 {
    if ((src == NODE_A) && (dst == NODE_B)) {
        return NODE_B;
    } else {
        if ((src == NODE_A) && (dst == NODE_C)) {
            return NODE_B;
        } else {
            if ((src == NODE_B) && (dst == NODE_C)) {
                return NODE_C;
            } else {
                if ((src == NODE_B) && (dst == NODE_A)) {
                    return NODE_A;
                } else {
                    if ((src == NODE_C) && (dst == NODE_A)) {
                        return NODE_B;
                    } else {
                        if ((src == NODE_C) && (dst == NODE_B)) {
                            return NODE_B;
                        } else {
                            return 0;
                        }
                    }
                }
            }
        }
    }
}

pub fn tx_path(src: u32, dst: u32, payload: u8) -> u32 {
    return build_packet(src, dst, (MAX_HOPS as u8), payload);
}

pub fn rx_path(packet: u32) -> u8 {
    return extract_payload(packet);
}

pub fn forward_packet(packet: u32, current_node: u32) -> (u32, bool, u32) {
    let (forwarded, expired) = decrement_ttl(packet);
    if (expired == true) {
        return (forwarded, true, 0);
    }
    if (route_packet(current_node, extract_dst(forwarded), 0) == 0) {
        return (forwarded, false, 0);
    }
    return (forwarded, false, route_packet(current_node, extract_dst(forwarded), 0));
}

