// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_METRICS: u32 = 16;

pub const BASELINE_WINDOW: u32 = 8;

pub const ANOMALY_THRESHOLD: u32 = 30;

pub const SEVERITY_HIGH: u32 = 80;

pub const SEVERITY_MEDIUM: u32 = 50;

pub fn create_metric_reading(metric_id: u32, value: u32, timestamp: u32, confidence: u32) -> u32 {
    return (((((metric_id & 0xFF) << 24) | ((value & 0xFF) << 16)) | ((timestamp & 0xFF) << 8)) | (confidence & 0xFF));
}

pub fn get_metric_id(reading: u32) -> u32 {
    return ((reading >> 24) & 0xFF);
}

pub fn get_metric_value(reading: u32) -> u32 {
    return ((reading >> 16) & 0xFF);
}

pub fn get_timestamp(reading: u32) -> u32 {
    return ((reading >> 8) & 0xFF);
}

pub fn get_confidence(reading: u32) -> u32 {
    return (reading & 0xFF);
}

pub fn create_anomaly_report(metric_id: u32, severity: u32, anomaly_type: u32, confidence: u32) -> u32 {
    return (((((metric_id & 0xFF) << 24) | ((severity & 0xFF) << 16)) | ((anomaly_type & 0x3) << 14)) | (confidence & 0x3FFF));
}

pub fn get_anomaly_metric_id(report: u32) -> u32 {
    return ((report >> 24) & 0xFF);
}

pub fn get_severity(report: u32) -> u32 {
    return ((report >> 16) & 0xFF);
}

pub fn get_anomaly_type(report: u32) -> u32 {
    return ((report >> 14) & 0x3);
}

pub fn get_anomaly_confidence(report: u32) -> u32 {
    return (report & 0x3FFF);
}

pub const TYPE_SPIKE: u32 = 0;

pub const TYPE_DROP: u32 = 1;

pub const TYPE_PATTERN: u32 = 2;

pub const TYPE_TREND: u32 = 3;

pub fn calculate_baseline(history: Vec<>, count: u32) -> u32 {
    let;
    sum;
    let;
    valid_count;
    let;
    i;
    while (i < count) {
        let;
        value;
        sum = (sum + value);
        valid_count = (valid_count + 1);
        i = (i + 1);
    }
    if (valid_count > 0) {
        return (sum / valid_count);
    } else {
        return 0;
    }
}

pub fn calculate_variance(history: Vec<>, count: u32, baseline: u32) -> u32 {
    let;
    sum_diff;
    let;
    i;
    while (i < count) {
        let;
        value;
        let;
        diff;
        if (value > baseline) {
            diff = (value - baseline);
        } else {
            diff = (baseline - value);
        }
        sum_diff = (sum_diff + diff);
        i = (i + 1);
    }
    if (count > 0) {
        return (sum_diff / count);
    } else {
        return 0;
    }
}

pub fn detect_spike(current: u32, baseline: u32, variance: u32) -> u32 {
    if (current > baseline) {
        let;
        increase;
        if (variance > 0) {
            let;
            threshold;
            if (increase > threshold) {
                return 1;
            }
        } else {
            if (increase > ANOMALY_THRESHOLD) {
                return 1;
            }
        }
    }
    return 0;
}

pub fn detect_drop(current: u32, baseline: u32, variance: u32) -> u32 {
    if (current < baseline) {
        let;
        decrease;
        if (variance > 0) {
            let;
            threshold;
            if (decrease > threshold) {
                return 1;
            }
        } else {
            if (decrease > ANOMALY_THRESHOLD) {
                return 1;
            }
        }
    }
    return 0;
}

pub fn detect_pattern(history: Vec<>, count: u32) -> u32 {
    if (count < 4) {
        return 0;
    }
    let;
    pattern_count;
    let;
    i;
    while (i < (count - 2)) {
        let;
        val1;
        let;
        val2;
        let;
        val3;
        if (((val1 > val2) && (val2 < val3)) || ((val1 < val2) && (val2 > val3))) {
            pattern_count = (pattern_count + 1);
        }
        i = (i + 1);
    }
    if (pattern_count >= 2) {
        return 1;
    } else {
        return 0;
    }
}

pub fn detect_trend(history: Vec<>, count: u32) -> u32 {
    if (count < 4) {
        return 0;
    }
    let;
    increases;
    let;
    decreases;
    let;
    i;
    while (i < (count - 1)) {
        let;
        current;
        let;
        next;
        if (next > current) {
            increases = (increases + 1);
        } else {
            if (next < current) {
                decreases = (decreases + 1);
            }
        }
        i = (i + 1);
    }
    let;
    total;
    if (total > 0) {
        let;
        increase_ratio;
        let;
        decrease_ratio;
        if ((increase_ratio > 80) || (decrease_ratio > 80)) {
            return 1;
        }
    }
    return 0;
}

pub fn calculate_severity(current: u32, baseline: u32) -> u32 {
    let;
    diff;
    if (current > baseline) {
        diff = (current - baseline);
    } else {
        diff = (baseline - current);
    }
    if (diff > SEVERITY_HIGH) {
        return 90;
    } else {
        if (diff > SEVERITY_MEDIUM) {
            return 60;
        } else {
            return 30;
        }
    }
}

pub fn detect_anomaly(history: Vec<>, count: u32, current_reading: u32) -> u32 {
    if (count < BASELINE_WINDOW) {
        return 0;
    }
    let;
    baseline;
    let;
    variance;
    let;
    current;
    let;
    metric_id;
    let;
    anomaly_type;
    let;
    severity;
    if (detect_spike(current, baseline, variance) == 1) {
        anomaly_type = TYPE_SPIKE;
        severity = calculate_severity(current, baseline);
    } else {
        if (detect_drop(current, baseline, variance) == 1) {
            anomaly_type = TYPE_DROP;
            severity = calculate_severity(current, baseline);
        } else {
            if (detect_pattern(history, count) == 1) {
                anomaly_type = TYPE_PATTERN;
                severity = 50;
            } else {
                if (detect_trend(history, count) == 1) {
                    anomaly_type = TYPE_TREND;
                    severity = 40;
                }
            }
        }
    }
    if (anomaly_type != 0) {
        return create_anomaly_report(metric_id, severity, anomaly_type, 80);
    } else {
        return 0;
    }
}

pub fn is_critical_anomaly(report: u32) -> u32 {
    let;
    severity;
    if (severity >= SEVERITY_HIGH) {
        return 1;
    } else {
        return 0;
    }
}

pub fn get_anomaly_description(report: u32) -> u32 {
    let;
    anomaly_type;
    if (anomaly_type == TYPE_SPIKE) {
        return 1;
    } else {
        if (anomaly_type == TYPE_DROP) {
            return 2;
        } else {
            if (anomaly_type == TYPE_PATTERN) {
                return 3;
            } else {
                if (anomaly_type == TYPE_TREND) {
                    return 4;
                } else {
                    return 0;
                }
            }
        }
    }
}

pub fn correlate_metrics(metric1_id: u32, metric2_id: u32, history1: Vec<>, history2: Vec<>, count: u32) -> u32 {
    if (count < 4) {
        return 0;
    }
    let;
    same_direction;
    let;
    i;
    while (i < (count - 1)) {
        let;
        val1_current;
        let;
        val1_next;
        let;
        val2_current;
        let;
        val2_next;
        let;
        direction1;
        if (val1_next > val1_current) {
            direction1 = 1;
        } else {
            if (val1_next < val1_current) {
                direction1 = 2;
            }
        }
        let;
        direction2;
        if (val2_next > val2_current) {
            direction2 = 1;
        } else {
            if (val2_next < val2_current) {
                direction2 = 2;
            }
        }
        if ((direction1 == direction2) && (direction1 != 0)) {
            same_direction = (same_direction + 1);
        }
        i = (i + 1);
    }
    if (count > 1) {
        return ((same_direction * 100) / (count - 1));
    } else {
        return 0;
    }
}

pub fn detect_coordinated_attack(anomalies: Vec<>, count: u32) -> u32 {
    let;
    critical_count;
    let;
    i;
    while (i < count) {
        if (is_critical_anomaly(anomalies[i]) == 1) {
            critical_count = (critical_count + 1);
        }
        i = (i + 1);
    }
    if (critical_count >= 2) {
        return 1;
    } else {
        return 0;
    }
}

pub fn calculate_anomaly_confidence(report: u32, historical_confidence: u32) -> u32 {
    let;
    severity;
    let;
    base_confidence;
    let;
    weighted_confidence;
    if (weighted_confidence > 100) {
        return 100;
    } else {
        return weighted_confidence;
    }
}

