// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const STATE_COLD_START: u8 = 0;

pub const STATE_DISCOVERING: u8 = 1;

pub const STATE_CONNECTED: u8 = 2;

pub const STATE_PARTITIONED: u8 = 3;

pub const STATE_RECOVERING: u8 = 4;

pub fn create_node_state(state: u8, neighbors: u32, uptime: u32) -> u32 {
    return ((((() & 0xFF) << 24) | ((neighbors & 0xFF) << 16)) | (uptime & 0xFFFF));
}

pub fn node_state(state: u32) -> u8 {
    return ();
}

pub fn node_neighbors(state: u32) -> u32 {
    return ((state >> 16) & 0xFF);
}

pub fn node_uptime(state: u32) -> u32 {
    return (state & 0xFFFF);
}

pub fn cold_start() -> u32 {
    return create_node_state(STATE_COLD_START, 0, 0);
}

pub fn discover_neighbor(node_state: u32) -> u32 {
    if (node_state(node_state) == STATE_COLD_START) {
        return create_node_state(STATE_DISCOVERING, 0, node_uptime(node_state));
    } else {
        if (node_state(node_state) == STATE_DISCOVERING) {
            return create_node_state(STATE_CONNECTED, (node_neighbors(node_state) + 1), node_uptime(node_state));
        } else {
            return node_state;
        }
    }
}

pub fn simulate_partition(node_state: u32) -> u32 {
    if (node_state(node_state) == STATE_CONNECTED) {
        return create_node_state(STATE_PARTITIONED, 0, node_uptime(node_state));
    } else {
        return node_state;
    }
}

pub fn recover_from_partition(node_state: u32) -> u32 {
    if (node_state(node_state) == STATE_PARTITIONED) {
        return create_node_state(STATE_RECOVERING, 0, node_uptime(node_state));
    } else {
        return node_state;
    }
}

pub fn node_join(existing_node: u32) -> u32 {
    return create_node_state(node_state(existing_node), (node_neighbors(existing_node) + 1), node_uptime(existing_node));
}

pub fn node_leave(existing_node: u32) -> u32 {
    if (node_neighbors(existing_node) > 0) {
        return create_node_state(node_state(existing_node), (node_neighbors(existing_node) - 1), node_uptime(existing_node));
    } else {
        return existing_node;
    }
}

pub fn simulate_interference(node_state: u32, interference_level: u8) -> u32 {
    if (interference_level > 128) {
        return create_node_state(node_state(node_state), 0, node_uptime(node_state));
    } else {
        return node_state;
    }
}

pub fn battery_drain(uptime: u32, drain_rate: u32) -> u32 {
    if (uptime > (10000 / drain_rate)) {
        return 0;
    } else {
        return uptime;
    }
}

pub fn check_max_hops(ttl: u8, max_hops: u8) -> bool {
    return ((ttl > 0) && (ttl <= max_hops));
}

