// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_SAMPLES: u32 = 16;

pub const PATTERN_WINDOW: u32 = 8;

pub const ANOMALY_THRESHOLD: u32 = 50;

pub fn create_sample(value: u32, timestamp: u32, sequence: u32, valid: u32) -> u32 {
    return (((((value & 0xFF) << 24) | ((timestamp & 0xFF) << 16)) | ((sequence & 0xFF) << 8)) | (valid & 0x1));
}

pub fn get_sample_value(sample: u32) -> u32 {
    return ((sample >> 24) & 0xFF);
}

pub fn get_sample_timestamp(sample: u32) -> u32 {
    return ((sample >> 16) & 0xFF);
}

pub fn get_sample_sequence(sample: u32) -> u32 {
    return ((sample >> 8) & 0xFF);
}

pub fn get_sample_valid(sample: u32) -> u32 {
    return (sample & 0x1);
}

pub fn create_pattern_storage(samples: u32, pattern_count: u32, trend: u32, last_update: u32) -> u32 {
    return (((((samples & 0xFFFF) << 16) | ((pattern_count & 0xFF) << 8)) | (trend & 0x3)) | (last_update & 0x1));
}

pub fn get_pattern_samples(storage: u32) -> u32 {
    return ((storage >> 16) & 0xFFFF);
}

pub fn get_pattern_count(storage: u32) -> u32 {
    return ((storage >> 8) & 0xFF);
}

pub fn get_trend_direction(storage: u32) -> u32 {
    return (storage & 0x3);
}

pub fn create_sample_array(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, s5: u32, s6: u32, s7: u32, s8: u32, s9: u32, s10: u32, s11: u32, s12: u32, s13: u32, s14: u32, s15: u32) -> u64 {
    return (((((((((s0 as u64) << 56) | ((s1 as u64) << 48)) | ((s2 as u64) << 40)) | ((s3 as u64) << 32)) | ((s4 as u64) << 24)) | ((s5 as u64) << 16)) | ((s6 as u64) << 8)) | (s7 as u64));
}

pub fn get_sample_array_upper(array: u64) -> u64 {
    return ((array >> 32) >> 32);
}

pub fn get_sample_array_lower(array: u64) -> u64 {
    return (array & 0xFFFFFFFFFFFFFFFF);
}

pub fn get_sample_at(array: u64, index: u32) -> u32 {
    if (index < 8) {
        let lower = get_sample_array_lower(array);
        return (((lower >> ((7 - index) * 8)) & 0xFF) as u32);
    } else {
        let upper = get_sample_array_upper(array);
        return (((upper >> ((15 - index) * 8)) & 0xFF) as u32);
    }
}

pub fn calculate_moving_average(array: u64, window: u32) -> u32 {
    let mut sum = 0;
    let mut count = window;
    if (count > 16) {
        count = 16;
    }
    sum = (sum + get_sample_value(get_sample_at(array, 0)));
    sum = (sum + get_sample_value(get_sample_at(array, 1)));
    sum = (sum + get_sample_value(get_sample_at(array, 2)));
    sum = (sum + get_sample_value(get_sample_at(array, 3)));
    if (count > 4) {
        sum = (sum + get_sample_value(get_sample_at(array, 4)));
        sum = (sum + get_sample_value(get_sample_at(array, 5)));
        sum = (sum + get_sample_value(get_sample_at(array, 6)));
        sum = (sum + get_sample_value(get_sample_at(array, 7)));
    }
    if (count > 8) {
        sum = (sum + get_sample_value(get_sample_at(array, 8)));
        sum = (sum + get_sample_value(get_sample_at(array, 9)));
        sum = (sum + get_sample_value(get_sample_at(array, 10)));
        sum = (sum + get_sample_value(get_sample_at(array, 11)));
    }
    if (count > 12) {
        sum = (sum + get_sample_value(get_sample_at(array, 12)));
        sum = (sum + get_sample_value(get_sample_at(array, 13)));
        sum = (sum + get_sample_value(get_sample_at(array, 14)));
        sum = (sum + get_sample_value(get_sample_at(array, 15)));
    }
    return (sum / count);
}

pub fn detect_trend(array: u64, samples: u32) -> u32 {
    if (samples < 2) {
        return 0;
    }
    let first = get_sample_value(get_sample_at(array, 0));
    let last = get_sample_value(get_sample_at(array, (samples - 1)));
    if (last > (first + 5)) {
        return 1;
    } else {
        if (last < (first - 5)) {
            return 2;
        } else {
            return 0;
        }
    }
}

pub fn predict_next_value(array: u64, samples: u32) -> u32 {
    let trend = detect_trend(array, samples);
    let current = get_sample_value(get_sample_at(array, (samples - 1)));
    if (trend == 1) {
        return (current + 10);
    } else {
        if (trend == 2) {
            let mut predicted = (current - 10);
            if (predicted < 0) {
                predicted = 0;
            }
            return predicted;
        } else {
            return current;
        }
    }
}

pub fn is_anomalous(array: u64, samples: u32, current_value: u32) -> u32 {
    let predicted = predict_next_value(array, samples);
    if (predicted > current_value) {
        return (predicted - current_value);
    } else {
        return (current_value - predicted);
    }
}

pub fn detect_repeating_pattern(array: u64, samples: u32) -> u32 {
    if (samples < 4) {
        return 0;
    }
    let v0 = get_sample_value(get_sample_at(array, 0));
    let v1 = get_sample_value(get_sample_at(array, 1));
    let v2 = get_sample_value(get_sample_at(array, 2));
    let v3 = get_sample_value(get_sample_at(array, 3));
    if (((v0 == v2) && (v1 == v3)) && (v0 != v1)) {
        return 1;
    }
    if (samples >= 6) {
        let v4 = get_sample_value(get_sample_at(array, 4));
        let v5 = get_sample_value(get_sample_at(array, 5));
        if (((v0 == v3) && (v1 == v4)) && (v2 == v5)) {
            return 1;
        }
    }
    return 0;
}

pub fn calculate_variance(array: u64, samples: u32) -> u32 {
    if (samples < 2) {
        return 0;
    }
    let avg = calculate_moving_average(array, samples);
    let mut sum_sq_diff = 0;
    if (samples >= 1) {
        let diff = (get_sample_value(get_sample_at(array, 0)) - avg);
        sum_sq_diff = (sum_sq_diff + (diff * diff));
    }
    if (samples >= 2) {
        let diff = (get_sample_value(get_sample_at(array, 1)) - avg);
        sum_sq_diff = (sum_sq_diff + (diff * diff));
    }
    if (samples >= 3) {
        let diff = (get_sample_value(get_sample_at(array, 2)) - avg);
        sum_sq_diff = (sum_sq_diff + (diff * diff));
    }
    if (samples >= 4) {
        let diff = (get_sample_value(get_sample_at(array, 3)) - avg);
        sum_sq_diff = (sum_sq_diff + (diff * diff));
    }
    if (samples < 2) {
        return 0;
    }
    return (sum_sq_diff / samples);
}

