// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_NODES: u32 = 8;

pub const QUARANTINE_DURATION: u32 = 1000;

pub const VIOLATION_THRESHOLD: u32 = 3;

pub const TRUST_THRESHOLD: u32 = 30;

pub fn create_quarantine_state(node_id: u32, status: u32, start_time: u32, violations: u32) -> u32 {
    return (((((node_id & 0xFF) << 24) | ((status & 0x3) << 22)) | ((start_time & 0xFF) << 14)) | (violations & 0x3FFF));
}

pub fn get_quarantine_node_id(state: u32) -> u32 {
    return ((state >> 24) & 0xFF);
}

pub fn get_quarantine_status(state: u32) -> u32 {
    return ((state >> 22) & 0x3);
}

pub fn get_start_time(state: u32) -> u32 {
    return ((state >> 14) & 0xFF);
}

pub fn get_violation_count(state: u32) -> u32 {
    return (state & 0x3FFF);
}

pub const STATUS_NORMAL: u32 = 0;

pub const STATUS_QUARANTINED: u32 = 1;

pub const STATUS_SUSPENDED: u32 = 2;

pub const STATUS_BANNED: u32 = 3;

pub fn is_quarantined(state: u32) -> u32 {
    let;
    status;
    if (((status == STATUS_QUARANTINED) || (status == STATUS_SUSPENDED)) || (status == STATUS_BANNED)) {
        return 1;
    } else {
        return 0;
    }
}

pub fn quarantine_node(state: u32, current_time: u32) -> u32 {
    let;
    node_id;
    let;
    violations;
    return create_quarantine_state(node_id, STATUS_QUARANTINED, current_time, (violations + 1));
}

pub fn release_quarantine(state: u32) -> u32 {
    let;
    node_id;
    let;
    violations;
    return create_quarantine_state(node_id, STATUS_NORMAL, 0, violations);
}

pub fn suspend_node(state: u32, current_time: u32) -> u32 {
    let;
    node_id;
    let;
    violations;
    return create_quarantine_state(node_id, STATUS_SUSPENDED, current_time, (violations + 2));
}

pub fn ban_node(state: u32) -> u32 {
    let;
    node_id;
    return create_quarantine_state(node_id, STATUS_BANNED, 0, 0xFFFF);
}

pub fn should_release_quarantine(state: u32, current_time: u32) -> u32 {
    let;
    status;
    let;
    start_time;
    if (status == STATUS_QUARANTINED) {
        let;
        elapsed;
        if (elapsed >= QUARANTINE_DURATION) {
            return 1;
        }
    }
    return 0;
}

pub fn update_quarantine_state(state: u32, current_time: u32) -> u32 {
    if (should_release_quarantine(state, current_time) == 1) {
        return release_quarantine(state);
    } else {
        return state;
    }
}

pub fn create_violation_record(node_id: u32, violation_type: u32, severity: u32, timestamp: u32) -> u32 {
    return (((((node_id & 0xFF) << 24) | ((violation_type & 0xF) << 20)) | ((severity & 0xF) << 16)) | (timestamp & 0xFFFF));
}

pub fn get_violation_node_id(record: u32) -> u32 {
    return ((record >> 24) & 0xFF);
}

pub fn get_violation_type(record: u32) -> u32 {
    return ((record >> 20) & 0xF);
}

pub fn get_violation_severity(record: u32) -> u32 {
    return ((record >> 16) & 0xF);
}

pub fn get_violation_timestamp(record: u32) -> u32 {
    return (record & 0xFFFF);
}

pub const VIOLATION_PACKET_FLOOD: u32 = 0;

pub const VIOLATION_AUTH_FAILURE: u32 = 1;

pub const VIOLATION_MALFORMED_PACKET: u32 = 2;

pub const VIOLATION_ANOMALOUS_BEHAVIOR: u32 = 3;

pub const VIOLATION_RESOURCE_ABUSE: u32 = 4;

pub const VIOLATION_TRUST_VIOLATION: u32 = 5;

pub fn record_violation(state: u32, violation_record: u32) -> u32 {
    let;
    node_id;
    let;
    violation_node_id;
    if (node_id != violation_node_id) {
        return state;
    }
    let;
    current_violations;
    let;
    new_violations;
    let;
    node_id_ret;
    let;
    status;
    let;
    start_time;
    return create_quarantine_state(node_id_ret, status, start_time, new_violations);
}

pub fn should_quarantine(state: u32) -> u32 {
    let;
    violations;
    let;
    status;
    if ((status == STATUS_NORMAL) && (violations >= VIOLATION_THRESHOLD)) {
        return 1;
    } else {
        return 0;
    }
}

pub fn calculate_quarantine_severity(state: u32) -> u32 {
    let;
    violations;
    let;
    status;
    if (status == STATUS_BANNED) {
        return 100;
    } else {
        if (status == STATUS_SUSPENDED) {
            return 70;
        } else {
            if (status == STATUS_QUARANTINED) {
                let;
                severity;
                if (severity > 50) {
                    return 50;
                } else {
                    return severity;
                }
            } else {
                return 0;
            }
        }
    }
}

pub fn find_quarantined_node(states: Vec<>, node_id: u32) -> u32 {
    let;
    i;
    while (i < MAX_NODES) {
        let;
        state_node_id;
        if (state_node_id == node_id) {
            return i;
        }
        i = (i + 1);
    }
    return MAX_NODES;
}

pub fn count_quarantined_nodes(states: Vec<>) -> u32 {
    let;
    count;
    let;
    i;
    while (i < MAX_NODES) {
        if (is_quarantined(states[i]) == 1) {
            count = (count + 1);
        }
        i = (i + 1);
    }
    return count;
}

pub fn get_quarantine_reason(violation_type: u32) -> u32 {
    if (violation_type == VIOLATION_PACKET_FLOOD) {
        return 1;
    } else {
        if (violation_type == VIOLATION_AUTH_FAILURE) {
            return 2;
        } else {
            if (violation_type == VIOLATION_MALFORMED_PACKET) {
                return 3;
            } else {
                if (violation_type == VIOLATION_ANOMALOUS_BEHAVIOR) {
                    return 4;
                } else {
                    if (violation_type == VIOLATION_RESOURCE_ABUSE) {
                        return 5;
                    } else {
                        if (violation_type == VIOLATION_TRUST_VIOLATION) {
                            return 6;
                        } else {
                            return 0;
                        }
                    }
                }
            }
        }
    }
}

pub fn is_communication_allowed(state: u32, trust_score: u32) -> u32 {
    let;
    status;
    if (status == STATUS_BANNED) {
        return 0;
    }
    if ((status == STATUS_SUSPENDED) && (trust_score < (TRUST_THRESHOLD + 20))) {
        return 0;
    }
    if ((status == STATUS_QUARANTINED) && (trust_score < TRUST_THRESHOLD)) {
        return 0;
    }
    return 1;
}

pub fn calculate_health_impact(states: Vec<>) -> u32 {
    let;
    quarantined_count;
    let;
    total_nodes;
    if (total_nodes > 0) {
        return ((quarantined_count * 100) / total_nodes);
    } else {
        return 0;
    }
}

pub fn recommend_quarantine_action(state: u32, trust_score: u32) -> u32 {
    let;
    violations;
    let;
    status;
    if (status == STATUS_BANNED) {
        return 4;
    } else {
        if ((trust_score < 10) && (violations > 5)) {
            return 3;
        } else {
            if ((trust_score < TRUST_THRESHOLD) && (violations >= VIOLATION_THRESHOLD)) {
                return 2;
            } else {
                if (violations >= VIOLATION_THRESHOLD) {
                    return 1;
                } else {
                    return 0;
                }
            }
        }
    }
}

pub fn create_notification(node_id: u32, action: u32, reason: u32, duration: u32) -> u32 {
    return (((((node_id & 0xFF) << 24) | ((action & 0xF) << 20)) | ((reason & 0xF) << 16)) | (duration & 0xFFFF));
}

pub fn get_notification_node_id(notification: u32) -> u32 {
    return ((notification >> 24) & 0xFF);
}

pub fn get_notification_action(notification: u32) -> u32 {
    return ((notification >> 20) & 0xF);
}

pub fn get_notification_reason(notification: u32) -> u32 {
    return ((notification >> 16) & 0xF);
}

pub fn get_notification_duration(notification: u32) -> u32 {
    return (notification & 0xFFFF);
}

