// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_ENTRIES: u32 = 16;

pub const MAX_CACHE_SIZE: u32 = 256;

pub const CACHE_HIT_THRESHOLD: u32 = 2;

pub const EVICTION_AGE: u32 = 1000;

pub fn create_cache_entry(data_id: u32, access_count: u32, age: u32, size: u32) -> u32 {
    return (((((data_id & 0xFF) << 24) | ((access_count & 0xFF) << 16)) | ((age & 0xFF) << 8)) | (size & 0xFF));
}

pub fn get_data_id(entry: u32) -> u32 {
    return ((entry >> 24) & 0xFF);
}

pub fn get_access_count(entry: u32) -> u32 {
    return ((entry >> 16) & 0xFF);
}

pub fn get_age(entry: u32) -> u32 {
    return ((entry >> 8) & 0xFF);
}

pub fn get_entry_size(entry: u32) -> u32 {
    return (entry & 0xFF);
}

pub fn update_access_count(entry: u32) -> u32 {
    let data_id: u32 = get_data_id(entry);
    let mut access_count: u32 = get_access_count(entry);
    let age: u32 = get_age(entry);
    let size: u32 = get_entry_size(entry);
    if (access_count < 255) {
        access_count = (access_count + 1);
    }
    return create_cache_entry(data_id, access_count, age, size);
}

pub fn update_age(entry: u32, new_age: u32) -> u32 {
    let data_id: u32 = get_data_id(entry);
    let access_count: u32 = get_access_count(entry);
    let size: u32 = get_entry_size(entry);
    return create_cache_entry(data_id, access_count, new_age, size);
}

pub fn find_entry(cache: [u32; MAX_ENTRIES as usize], data_id: u32) -> u32 {
    let mut i: u32 = 0;
    while (i < MAX_ENTRIES) {
        let entry_data_id: u32 = get_data_id(cache[(i) as usize]);
        if (entry_data_id == data_id) {
            return i;
        }
        i = (i + 1);
    }
    return MAX_ENTRIES;
}

pub fn cache_hit(cache: [u32; MAX_ENTRIES as usize], data_id: u32) -> u32 {
    let entry_index: u32 = find_entry(cache, data_id);
    if (entry_index < MAX_ENTRIES) {
        return 1;
    } else {
        return 0;
    }
}

pub fn get_entry(cache: [u32; MAX_ENTRIES as usize], data_id: u32) -> u32 {
    let entry_index: u32 = find_entry(cache, data_id);
    if (entry_index < MAX_ENTRIES) {
        return cache[(entry_index) as usize];
    } else {
        return 0;
    }
}

pub fn add_entry(cache: [u32; MAX_ENTRIES as usize], current_size: u32, data_id: u32, size: u32) -> u32 {
    let existing_index: u32 = find_entry(cache, data_id);
    if (existing_index < MAX_ENTRIES) {
        return current_size;
    }
    let mut empty_index: u32 = MAX_ENTRIES;
    let mut i: u32 = 0;
    while (i < MAX_ENTRIES) {
        if (get_data_id(cache[(i) as usize]) == 0) {
            empty_index = i;
            break;
        }
        i = (i + 1);
    }
    if (empty_index == MAX_ENTRIES) {
        empty_index = find_eviction_candidate(cache);
        if (empty_index == MAX_ENTRIES) {
            return current_size;
        }
        let evicted_size: u32 = get_entry_size(cache[(empty_index) as usize]);
        current_size = (current_size - evicted_size);
    }
    if ((current_size + size) > MAX_CACHE_SIZE) {
        return current_size;
    }
    cache[(empty_index) as usize] = create_cache_entry(data_id, 1, 0, size);
    return (current_size + size);
}

pub fn find_eviction_candidate(cache: [u32; MAX_ENTRIES as usize]) -> u32 {
    let mut worst_score: u32 = 0xFFFFFFFF;
    let mut candidate: u32 = MAX_ENTRIES;
    let mut i: u32 = 0;
    while (i < MAX_ENTRIES) {
        let entry: u32 = cache[(i) as usize];
        let data_id: u32 = get_data_id(entry);
        if (data_id != 0) {
            let access_count: u32 = get_access_count(entry);
            let age: u32 = get_age(entry);
            let score: u32 = ((access_count << 8) | age);
            if (score < worst_score) {
                worst_score = score;
                candidate = i;
            }
        }
        i = (i + 1);
    }
    return candidate;
}

pub fn remove_entry(cache: [u32; MAX_ENTRIES as usize], current_size: u32, data_id: u32) -> u32 {
    let entry_index: u32 = find_entry(cache, data_id);
    if (entry_index < MAX_ENTRIES) {
        let entry_size: u32 = get_entry_size(cache[(entry_index) as usize]);
        cache[(entry_index) as usize] = 0;
        return (current_size - entry_size);
    } else {
        return current_size;
    }
}

pub fn access_cache(cache: [u32; MAX_ENTRIES as usize], data_id: u32) -> u32 {
    let entry_index: u32 = find_entry(cache, data_id);
    if (entry_index < MAX_ENTRIES) {
        cache[(entry_index) as usize] = update_access_count(cache[(entry_index) as usize]);
        cache[(entry_index) as usize] = update_age(cache[(entry_index) as usize], 0);
        return 1;
    } else {
        return 0;
    }
}

pub fn age_cache(cache: [u32; MAX_ENTRIES as usize]) -> () {
    let mut i: u32 = 0;
    while (i < MAX_ENTRIES) {
        let entry: u32 = cache[(i) as usize];
        let age: u32 = get_age(entry);
        if (age < 255) {
            cache[(i) as usize] = update_age(entry, (age + 1));
        }
        i = (i + 1);
    }
}

pub fn calculate_hit_rate(hits: u32, total_accesses: u32) -> u32 {
    if (total_accesses > 0) {
        return ((hits * 100) / total_accesses);
    } else {
        return 0;
    }
}

pub fn calculate_utilization(current_size: u32) -> u32 {
    return ((current_size * 100) / MAX_CACHE_SIZE);
}

pub fn find_most_popular(cache: [u32; MAX_ENTRIES as usize]) -> u32 {
    let mut max_access: u32 = 0;
    let mut popular_index: u32 = MAX_ENTRIES;
    let mut i: u32 = 0;
    while (i < MAX_ENTRIES) {
        let access_count: u32 = get_access_count(cache[(i) as usize]);
        if (access_count > max_access) {
            max_access = access_count;
            popular_index = i;
        }
        i = (i + 1);
    }
    return popular_index;
}

pub fn find_least_popular(cache: [u32; MAX_ENTRIES as usize]) -> u32 {
    let mut min_access: u32 = 0xFFFFFFFF;
    let mut unpopular_index: u32 = MAX_ENTRIES;
    let mut i: u32 = 0;
    while (i < MAX_ENTRIES) {
        let entry: u32 = cache[(i) as usize];
        let data_id: u32 = get_data_id(entry);
        let access_count: u32 = get_access_count(entry);
        if ((data_id != 0) && (access_count < min_access)) {
            min_access = access_count;
            unpopular_index = i;
        }
        i = (i + 1);
    }
    return unpopular_index;
}

pub fn should_prefetch(cache: [u32; MAX_ENTRIES as usize], data_id: u32) -> u32 {
    let popular_index: u32 = find_most_popular(cache);
    if (popular_index < MAX_ENTRIES) {
        let popular_access: u32 = get_access_count(cache[(popular_index) as usize]);
        let entry_index: u32 = find_entry(cache, data_id);
        if (entry_index < MAX_ENTRIES) {
            let access_count: u32 = get_access_count(cache[(entry_index) as usize]);
            if (access_count >= CACHE_HIT_THRESHOLD) {
                return 1;
            }
        }
    }
    return 0;
}

pub fn calculate_efficiency(hits: u32, total_accesses: u32, current_size: u32) -> u32 {
    let hit_rate: u32 = calculate_hit_rate(hits, total_accesses);
    let utilization: u32 = calculate_utilization(current_size);
    if (utilization > 0) {
        return ((hit_rate * 100) / utilization);
    } else {
        return hit_rate;
    }
}

pub fn create_cache_stats(hits: u32, misses: u32, size: u32, evictions: u32) -> u32 {
    return (((((hits & 0xFF) << 24) | ((misses & 0xFF) << 16)) | ((size & 0xFF) << 8)) | (evictions & 0xFF));
}

pub fn get_hits(stats: u32) -> u32 {
    return ((stats >> 24) & 0xFF);
}

pub fn get_misses(stats: u32) -> u32 {
    return ((stats >> 16) & 0xFF);
}

pub fn get_cache_size(stats: u32) -> u32 {
    return ((stats >> 8) & 0xFF);
}

pub fn get_evictions(stats: u32) -> u32 {
    return (stats & 0xFF);
}

pub fn update_stats(stats: u32, hit: u32, evicted: u32) -> u32 {
    let mut hits: u32 = get_hits(stats);
    let mut misses: u32 = get_misses(stats);
    let size: u32 = get_cache_size(stats);
    let mut evictions: u32 = get_evictions(stats);
    if (hit == 1) {
        hits = (hits + 1);
    } else {
        misses = (misses + 1);
    }
    if (evicted == 1) {
        evictions = (evictions + 1);
    }
    return create_cache_stats(hits, misses, size, evictions);
}

