// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub const MAX_KEYS: u32 = 4;

pub const KEY_SIZE: u32 = 4;

pub const KEY_VALID: u32 = 1;

pub const KEY_INVALID: u32 = 0;

pub const ROTATION_INTERVAL: u32 = 30000;

pub fn create_key_entry(valid: u32, key_id: u32, key_value: u32, timestamp: u32) -> u32 {
    return (((((valid & 0x1) << 31) | ((key_id & 0xFF) << 24)) | ((key_value & 0xFFFF) << 8)) | (timestamp & 0xFF));
}

pub fn get_key_valid(entry: u32) -> u32 {
    return ((entry >> 31) & 0x1);
}

pub fn get_key_id(entry: u32) -> u32 {
    return ((entry >> 24) & 0xFF);
}

pub fn get_key_value(entry: u32) -> u32 {
    return ((entry >> 8) & 0xFFFF);
}

pub fn get_key_timestamp(entry: u32) -> u32 {
    return (entry & 0xFF);
}

pub fn create_key_store(k0: u32, k1: u32, k2: u32, k3: u32) -> u64 {
    return ((((() << 48) | (() << 32)) | (() << 16)) | ());
}

pub fn get_key_entry(store: u64, index: u32) -> u32 {
    if (index == 0) {
        return ();
    }
    if (index == 1) {
        return ();
    }
    if (index == 2) {
        return ();
    }
    return ();
}

pub fn find_key_by_id(store: u64, key_id: u32) -> u32 {
    if ((get_key_id(get_key_entry(store, 0)) == key_id) && (get_key_valid(get_key_entry(store, 0)) == KEY_VALID)) {
        return 0;
    } else {
        if ((get_key_id(get_key_entry(store, 1)) == key_id) && (get_key_valid(get_key_entry(store, 1)) == KEY_VALID)) {
            return 1;
        } else {
            if ((get_key_id(get_key_entry(store, 2)) == key_id) && (get_key_valid(get_key_entry(store, 2)) == KEY_VALID)) {
                return 2;
            } else {
                if ((get_key_id(get_key_entry(store, 3)) == key_id) && (get_key_valid(get_key_entry(store, 3)) == KEY_VALID)) {
                    return 3;
                }
            }
        }
    }
    return 0xFF;
}

pub fn add_key(store: u64, key_id: u32, key_value: u32, timestamp: u32) -> u64 {
    if (get_key_valid(get_key_entry(store, 0)) == KEY_INVALID) {
        return ((store & 0x0000FFFFFFFFFFFF) | (() << 48));
    } else {
        if (get_key_valid(get_key_entry(store, 1)) == KEY_INVALID) {
            return ((store & 0xFFFF0000FFFFFFFF) | (() << 32));
        } else {
            if (get_key_valid(get_key_entry(store, 2)) == KEY_INVALID) {
                return ((store & 0xFFFFFFFF0000FFFF) | (() << 16));
            } else {
                if (get_key_valid(get_key_entry(store, 3)) == KEY_INVALID) {
                    return ((store & 0xFFFFFFFFFFFF0000) | ());
                }
            }
        }
    }
    return store;
}

pub fn invalidate_key(store: u64, key_id: u32) -> u64 {
    let;
    if (index != 0xFF) {
        let;
        entry = get_key_entry(store, index);
        let;
        new_entry = create_key_entry(KEY_INVALID, get_key_id(entry), get_key_value(entry), get_key_timestamp(entry));
        if (index == 0) {
            return ((store & 0x0000FFFFFFFFFFFF) | (() << 48));
        } else {
            if (index == 1) {
                return ((store & 0xFFFF0000FFFFFFFF) | (() << 32));
            } else {
                if (index == 2) {
                    return ((store & 0xFFFFFFFF0000FFFF) | (() << 16));
                } else {
                    return ((store & 0xFFFFFFFFFFFF0000) | ());
                }
            }
        }
    }
    return store;
}

pub fn needs_rotation(entry: u32, current_time: u32) -> bool {
    if (get_key_valid(entry) == KEY_INVALID) {
        return false;
    }
    let;
    age = (current_time - get_key_timestamp(entry));
    return (age >= ROTATION_INTERVAL);
}

pub fn rotate_key(store: u64, key_id: u32, new_value: u32, current_time: u32) -> u64 {
    let;
    if (index != 0xFF) {
        let;
        new_entry = create_key_entry(KEY_VALID, key_id, new_value, current_time);
        if (index == 0) {
            return ((store & 0x0000FFFFFFFFFFFF) | (() << 48));
        } else {
            if (index == 1) {
                return ((store & 0xFFFF0000FFFFFFFF) | (() << 32));
            } else {
                if (index == 2) {
                    return ((store & 0xFFFFFFFF0000FFFF) | (() << 16));
                } else {
                    return ((store & 0xFFFFFFFFFFFF0000) | ());
                }
            }
        }
    }
    return store;
}

pub fn get_active_key(store: u64) -> u32 {
    let;
    let;
    if (get_key_valid(get_key_entry(store, 0)) == KEY_VALID) {
        let;
        ts = get_key_timestamp(get_key_entry(store, 0));
        if (ts >= best_timestamp) {
            best_timestamp = ts;
            best_index = 0;
        }
    }
    if (get_key_valid(get_key_entry(store, 1)) == KEY_VALID) {
        let;
        ts = get_key_timestamp(get_key_entry(store, 1));
        if (ts >= best_timestamp) {
            best_timestamp = ts;
            best_index = 1;
        }
    }
    if (get_key_valid(get_key_entry(store, 2)) == KEY_VALID) {
        let;
        ts = get_key_timestamp(get_key_entry(store, 2));
        if (ts >= best_timestamp) {
            best_timestamp = ts;
            best_index = 2;
        }
    }
    if (get_key_valid(get_key_entry(store, 3)) == KEY_VALID) {
        let;
        ts = get_key_timestamp(get_key_entry(store, 3));
        if (ts >= best_timestamp) {
            best_timestamp = ts;
            best_index = 3;
        }
    }
    if (best_index != 0xFF) {
        return get_key_value(get_key_entry(store, best_index));
    }
    return 0;
}

pub fn count_valid_keys(store: u64) -> u32 {
    let;
    count = 0;
    if (get_key_valid(get_key_entry(store, 0)) == KEY_VALID) {
        count = (count + 1);
    }
    if (get_key_valid(get_key_entry(store, 1)) == KEY_VALID) {
        count = (count + 1);
    }
    if (get_key_valid(get_key_entry(store, 2)) == KEY_VALID) {
        count = (count + 1);
    }
    if (get_key_valid(get_key_entry(store, 3)) == KEY_VALID) {
        count = (count + 1);
    }
    return count;
}

