import Foundation

/// Safety budget for Queen autonomous actions. Once the budget reaches zero
/// or is explicitly halted, no self-improvement actions may run.
struct QueenSafetyBudget: Codable {
    var budget: Double
    var halted: Bool

    var isActive: Bool { !halted && budget > 0 }
}

/// A concrete, reviewable improvement proposal generated by Queen.
/// Proposals are never applied automatically; a human or Verifier Agent must
/// approve each one via `/evolve-apply <id>`.
struct QueenProposal: Identifiable, Codable {
    let id: UUID
    let createdAt: Date
    let trigger: String
    let targetFile: String
    let rationale: String
    let suggestedPatch: String
    let testPlan: String
    var status: Status
    var branchName: String?
    var prURL: String?

    enum Status: String, Codable {
        case pending
        case approved
        case applied
        case rejected
        case failedBuild
    }
}

/// Autonomous self-improvement loop for the Trinity Queen conversation.
/// Actions are gated by a safety budget and logged to durable memory.
/// No code is mutated without a human-approved proposal.
@MainActor
final class QueenSelfImprovementService: ObservableObject {
    @Published var lastAudit: QueenAuditEvent?
    @Published var isRunning: Bool = false
    @Published var proposals: [QueenProposal] = .init()

    private let memoryService: AgentMemoryService
    private let persister: ChatPersisterProtocol
    private let a2aClient: A2ARegistryClient?
    private let budgetURL: URL
    private let proposalsURL: URL
    private let projectRoot: String
    private var timer: Timer?

    /// Default audit interval in seconds (60 minutes).
    nonisolated static let defaultInterval: TimeInterval = 60 * 60

    init(
        memoryService: AgentMemoryService,
        persister: ChatPersisterProtocol,
        a2aClient: A2ARegistryClient?,
        projectRoot: String = ProjectPaths.root
    ) {
        self.memoryService = memoryService
        self.persister = persister
        self.a2aClient = a2aClient
        self.projectRoot = projectRoot
        self.budgetURL = URL(fileURLWithPath: "\(projectRoot)/\(ProjectPaths.variant.dataDirectoryName)/state/safety_budget.json")
        self.proposalsURL = URL(fileURLWithPath: "\(projectRoot)/\(ProjectPaths.variant.dataDirectoryName)/state/queen-proposals.json")
        self.proposals = loadProposalsSync()
    }

    /// Starts the periodic self-improvement timer using the default interval.
    func start() {
        start(interval: Self.defaultInterval)
    }

    /// Starts the periodic self-improvement timer.
    func start(interval: TimeInterval) {
        stop()
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                await self?.runAudit()
            }
        }
    }

    /// Stops the periodic timer.
    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Runs one audit/consolidation cycle if the safety budget allows.
    /// Discovers weak spots and generates concrete improvement proposals.
    func runAudit() async {
        guard let budget = loadBudget(), budget.isActive else {
            await log(event: .skipped(reason: "safety budget inactive"))
            return
        }
        guard !isRunning else { return }
        isRunning = true
        defer { isRunning = false }

        let eventId = UUID()
        var findings: [String] = []

        // 1. Read recent Queen conversation turns.
        let queenMessages = await persister.load(conversationId: ChatConversation.trinityQueenId)
        let recent = Array(queenMessages.suffix(50))
        if recent.isEmpty {
            findings.append("no recent Queen turns")
        } else {
            findings.append("loaded \(recent.count) recent Queen turns")
        }

        // 2. Recall relevant long-term memory.
        let recalled = await memoryService.recall(
            for: "Queen self-improvement and agent activity",
            limit: 5
        )
        findings.append("recalled \(recalled.count) memory entries")

        // 3. Analyze command success/failure patterns and generate proposals.
        let weakSpots = detectWeakSpots(in: recent)
        findings.append("detected \(weakSpots.count) weak spots")

        var newProposals: [QueenProposal] = []
        for spot in weakSpots {
            if let proposal = generateProposal(for: spot, recentMessages: recent) {
                newProposals.append(proposal)
            }
        }
        if !newProposals.isEmpty {
            appendProposals(newProposals)
            findings.append("generated \(newProposals.count) improvement proposals")
        }

        // 4. Build a compact improvement prompt and remember it.
        let summary = recent.map { "\($0.role): \($0.content.prefix(200))" }.joined(separator: "\n")
        let weakSpotText = weakSpots.map { "\($0.kind): \($0.detail)" }.joined(separator: "; ")
        let recordBody = """
        Queen audit at \(Date())
        Findings: \(findings.joined(separator: ", "))
        Weak spots: \(weakSpotText)
        Recent context:
        \(summary)
        """
        let record = AgentMemoryRecord(
            id: eventId,
            conversationId: ChatConversation.trinityQueenId,
            sourceMessageId: eventId,
            body: recordBody,
            createdAt: Date()
        )
        do {
            try await memoryService.saveMemory(record)
            findings.append("consolidated audit into memory")
        } catch {
            findings.append("memory store failed: \(error.localizedDescription)")
        }

        // 5. If A2A is live, ask the network for a lightweight health pulse.
        if let client = a2aClient {
            do {
                let agents = try await client.listAgents()
                findings.append("discovered \(agents.count) online agents")
            } catch {
                findings.append("agent discovery failed: \(error.localizedDescription)")
            }
        }

        let event = QueenAuditEvent(
            id: eventId,
            timestamp: Date(),
            findings: findings,
            budgetAfter: budget.budget,
            proposalCount: proposals.count + newProposals.count,
            weakSpots: weakSpots
        )
        lastAudit = event
        await log(event: .completed(event))
    }

    /// Loads the current safety budget from disk, defaulting to 10.0 / active.
    func loadBudget() -> QueenSafetyBudget? {
        Self.loadBudget(projectRoot: projectRoot)
    }

    /// Loads the budget for any project root without needing an instance.
    static func loadBudget(projectRoot: String = ProjectPaths.root) -> QueenSafetyBudget? {
        let url = URL(fileURLWithPath: "\(projectRoot)/\(ProjectPaths.variant.dataDirectoryName)/state/safety_budget.json")
        guard FileManager.default.fileExists(atPath: url.path),
              let data = try? Data(contentsOf: url),
              let budget = try? JSONDecoder().decode(QueenSafetyBudget.self, from: data) else {
            return QueenSafetyBudget(budget: 10.0, halted: false)
        }
        return budget
    }

    /// Halts all future autonomous actions.
    func halt() {
        var budget = loadBudget() ?? QueenSafetyBudget(budget: 0, halted: true)
        budget.halted = true
        saveBudget(budget)
    }

    /// Decrements the safety budget after a mutating action is approved.
    func consumeBudget(amount: Double) -> Bool {
        Self.consumeBudget(amount: amount) != nil
    }

    /// Spends part of the safety budget, returning what is left, or nil when
    /// there was nothing to spend.
    ///
    /// Static because the check that guards autonomous mutation is static:
    /// QueenProposalApplier reads loadBudget() before touching a file, and had
    /// no way to reach the instance method that decrements it. So the budget
    /// was a gate reading a number nothing ever reduced - it stayed at its
    /// default of ten and stayed active forever, and the only way to stop the
    /// Queen was to halt her by hand. A safety budget that cannot run out is a
    /// switch painted on the wall.
    ///
    /// The instance method above delegates rather than repeating the
    /// arithmetic, because two implementations of one rule is how this
    /// repository has produced most of its defects.
    @discardableResult
    static func consumeBudget(
        amount: Double,
        projectRoot: String = ProjectPaths.root
    ) -> QueenSafetyBudget? {
        guard var budget = loadBudget(projectRoot: projectRoot), budget.isActive else { return nil }
        budget.budget = max(0, budget.budget - amount)
        let url = URL(fileURLWithPath: "\(projectRoot)/\(ProjectPaths.variant.dataDirectoryName)/state/safety_budget.json")
        try? FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true
        )
        guard let data = try? JSONEncoder().encode(budget),
              (try? data.write(to: url, options: [.atomic])) != nil else { return nil }
        return budget
    }

    /// Approves a proposal by ID, returning the updated proposal.
    func approveProposal(id: UUID) -> QueenProposal? {
        guard let index = proposals.firstIndex(where: { $0.id == id }) else { return nil }
        proposals[index].status = .approved
        saveProposals()
        return proposals[index]
    }

    /// Marks a proposal as rejected.
    func rejectProposal(id: UUID) {
        guard let index = proposals.firstIndex(where: { $0.id == id }) else { return }
        proposals[index].status = .rejected
        saveProposals()
    }

    private func saveBudget(_ budget: QueenSafetyBudget) {
        if let data = try? JSONEncoder().encode(budget) {
            try? data.write(to: budgetURL, options: [.atomic])
        }
    }

    private func appendProposals(_ new: [QueenProposal]) {
        proposals.append(contentsOf: new)
        saveProposals()
    }

    private func saveProposals() {
        if let data = try? JSONEncoder().encode(proposals) {
            try? data.write(to: proposalsURL, options: [.atomic])
        }
    }

    private nonisolated func loadProposalsSync() -> [QueenProposal] {
        guard FileManager.default.fileExists(atPath: proposalsURL.path),
              let data = try? Data(contentsOf: proposalsURL),
              let loaded = try? JSONDecoder().decode([QueenProposal].self, from: data) else {
            return []
        }
        return loaded
    }

    private func log(event: QueenAuditLogEntry) async {
        let record = AgentMemoryRecord(
            id: UUID(),
            conversationId: ChatConversation.trinityQueenId,
            sourceMessageId: UUID(),
            body: "[Audit log] \(event.description)",
            createdAt: Date()
        )
        try? await memoryService.saveMemory(record)
    }

    // MARK: - Weak-spot detection

    private func detectWeakSpots(in messages: [ChatMessage]) -> [QueenWeakSpot] {
        var spots: [QueenWeakSpot] = []

        let commandMessages = messages.filter { $0.role == .user && $0.content.hasPrefix("/") }
        let delegateMessages = commandMessages.filter { $0.content.lowercased().hasPrefix("/delegate") }
        let failedDelegateResponses = messages.filter { $0.role == .system && $0.content.contains("Failed to delegate task") }
        let memoryResponses = messages.filter { $0.role == .system && $0.content.contains("Recalled memory") }
        let emptyMemoryResponses = memoryResponses.filter { $0.content.contains("No recent memory entries found") }

        if delegateMessages.count >= 3 && failedDelegateResponses.count > delegateMessages.count / 2 {
            spots.append(QueenWeakSpot(
                kind: .delegateFailure,
                detail: "\(failedDelegateResponses.count)/\(delegateMessages.count) delegate commands failed",
                evidence: failedDelegateResponses.map(\.content).joined(separator: " | ").prefix(300).map(String.init).joined()
            ))
        }

        if memoryResponses.count >= 3 && emptyMemoryResponses.count > memoryResponses.count / 2 {
            spots.append(QueenWeakSpot(
                kind: .memoryRecallGap,
                detail: "\(emptyMemoryResponses.count)/\(memoryResponses.count) memory recalls returned empty",
                evidence: emptyMemoryResponses.map(\.content).joined(separator: " | ").prefix(300).map(String.init).joined()
            ))
        }

        if commandMessages.count >= 5 {
            let unknownMessages = commandMessages.filter { QueenCommandParser.parse($0.content) == .unknown($0.content) }
            if unknownMessages.count > commandMessages.count / 3 {
                spots.append(QueenWeakSpot(
                    kind: .unknownCommand,
                    detail: "\(unknownMessages.count)/\(commandMessages.count) Queen commands were unknown",
                    evidence: unknownMessages.map(\.content).joined(separator: " | ").prefix(300).map(String.init).joined()
                ))
            }
        }

        if messages.count >= 10 {
            let errorMessages = messages.filter { $0.content.contains("error") || $0.content.contains("failed") || $0.content.contains("Failed") }
            if errorMessages.count > messages.count / 4 {
                spots.append(QueenWeakSpot(
                    kind: .highErrorRate,
                    detail: "\(errorMessages.count)/\(messages.count) messages mention errors",
                    evidence: errorMessages.map(\.content).joined(separator: " | ").prefix(300).map(String.init).joined()
            ))
            }
        }

        return spots
    }

    private func generateProposal(for spot: QueenWeakSpot, recentMessages: [ChatMessage]) -> QueenProposal? {
        switch spot.kind {
        case .delegateFailure:
            return QueenProposal(
                id: UUID(),
                createdAt: Date(),
                trigger: spot.detail,
                targetFile: "rings/SR-02/A2ARegistryClient.swift",
                rationale: "Many /delegate commands fail. Adding richer error context and retry/backoff to the A2A registry client will let Queen diagnose whether the target agent is offline or the payload is malformed.",
                suggestedPatch: """
                // Add to A2ARegistryClient after assignTask(_:to:):
                func assignTask(_ task: AgentTask, to agent: AgentId, maxRetries: Int = 1) async throws {
                    var lastError: Error?
                    for attempt in 0..<maxRetries {
                        do {
                            try await assignTask(task, to: agent)
                            return
                        } catch {
                            lastError = error
                            let delay = Double(attempt + 1) * 0.5
                            try? await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
                        }
                    }
                    throw lastError ?? A2AError.sendFailed
                }
                """,
                testPlan: "1. Run ./build.sh. 2. Use /delegate to an offline agent and verify error message includes context. 3. Use /delegate to an online agent and confirm success.",
                status: .pending
            )
        case .memoryRecallGap:
            return QueenProposal(
                id: UUID(),
                createdAt: Date(),
                trigger: spot.detail,
                targetFile: "rings/SR-02/AgentMemoryService.swift",
                rationale: "Memory recalls often return empty. Lowering the minimum relevance score slightly and expanding recall feature vocabulary will improve recall coverage for Queen-specific queries.",
                suggestedPatch: """
                // In AgentMemoryService:
                // private static let minimumRecallScore = 0.30
                // Lower threshold for Queen memory queries to improve recall coverage.
                private static let queenMinimumRecallScore: Double = 0.15

                func recall(for query: String, limit: Int = 3, mode: MemoryRecallMode = .default) async -> [AgentMemoryMatch] {
                    let normalizedQuery = Self.normalizedText(query, maximumLength: 4_096)
                    guard let fingerprintKey else { return [] }
                    let queryFeatures = Self.recallFeatures(in: normalizedQuery, key: fingerprintKey)
                    guard !queryFeatures.isEmpty, limit > 0 else { return [] }
                    let threshold = mode == .queen ? queenMinimumRecallScore : Self.minimumRecallScore
                    // ... existing candidate scoring uses threshold
                }
                """,
                testPlan: "1. Run ./build.sh. 2. Run /memory several times and verify non-empty results when matching memories exist. 3. Check AgentMemoryServiceRedactionTests still pass.",
                status: .pending
            )
        case .unknownCommand:
            return QueenProposal(
                id: UUID(),
                createdAt: Date(),
                trigger: spot.detail,
                targetFile: "rings/SR-02/QueenCommandParser.swift",
                rationale: "Users frequently type unsupported slash commands. Adding an alias map and fuzzy matching will make Queen feel responsive and teach the user valid commands.",
                suggestedPatch: """
                // In QueenCommandParser.parse(_:) default branch:
                // Try alias/fuzzy match before returning unknown.
                let aliases: [String: String] = [
                    "agent": "agents", "list": "chats", "open": "switch",
                    "send": "broadcast", "task": "delegate", "remember": "memory"
                ]
                if let canonical = aliases[name] {
                    // Re-parse with canonical name and same components
                    let aliased = "/\\(canonical) \\(components.joined(separator: \" \"))"
                    return parse(aliased)
                }
                """,
                testPlan: "1. Run ./build.sh. 2. Test /agent, /list, /send aliases in Queen chat. 3. Verify /unknown still returns help.",
                status: .pending
            )
        case .highErrorRate:
            return QueenProposal(
                id: UUID(),
                createdAt: Date(),
                trigger: spot.detail,
                targetFile: "rings/SR-02/QueenSelfImprovementService.swift",
                rationale: "High error rate in Queen chat. Adding automatic error classification in the audit will let Queen propose targeted fixes instead of generic patches.",
                suggestedPatch: """
                // Add to QueenSelfImprovementService.detectWeakSpots:
                func classifyError(_ message: ChatMessage) -> QueenErrorClass {
                    if message.content.contains("A2A") || message.content.contains("delegate") { return .a2a }
                    if message.content.contains("memory") { return .memory }
                    if message.content.contains("build") { return .build }
                    return .general
                }
                """,
                testPlan: "1. Run ./build.sh. 2. Trigger errors in Queen chat. 3. Run /audit and verify error classes appear in findings.",
                status: .pending
            )
        }
    }
}

struct QueenAuditEvent: Identifiable, Codable {
    let id: UUID
    let timestamp: Date
    let findings: [String]
    let budgetAfter: Double
    let proposalCount: Int
    let weakSpots: [QueenWeakSpot]
}

enum QueenAuditLogEntry: CustomStringConvertible {
    case skipped(reason: String)
    case completed(QueenAuditEvent)

    var description: String {
        switch self {
        case .skipped(let reason):
            return "skipped: \(reason)"
        case .completed(let event):
            return "completed \(event.id.uuidString.prefix(8)) with findings: \(event.findings.joined(separator: "; "))"
        }
    }
}

struct QueenWeakSpot: Codable, Equatable {
    enum Kind: String, Codable {
        case delegateFailure
        case memoryRecallGap
        case unknownCommand
        case highErrorRate
    }

    let kind: Kind
    let detail: String
    let evidence: String
}
