// Generated by `t27c gen-js` from simulation.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const SEEDS_PER_RUN = 16;
export const STEPS_PER_RUN = 10000;
export const RUNS_PER_SEED = 2;
export const GATE_BASE_SEED = 1712;
export const FEATURE_TURN_STOP = 1;
export const TURN_STOP_EVERY = 2;
// t27c gen-js: fn seed_features was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn has_feature was not emitted -- this backend lowers declarations, not bodies.
export const STORE_SEEDS_PER_RUN = 2;
export const TAIL_SECONDS = 3600;
export const LOG_TAIL_LINES = 30;
export const MASK32 = 4294967295;
export const STREAM_SEED = 1;
export const STREAM_STEP = 2;
export const STREAM_DELAY = 3;
export const STREAM_TARGET = 4;
export const STREAM_DURATION = 5;
export const STREAM_ATTEMPT = 6;
export const STREAM_LATENCY = 7;
export const STREAM_CLOCK = 8;
export const STREAM_STORE = 9;
// t27c gen-js: fn mix32 was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn sim_roll was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn run_seed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn pick_between was not emitted -- this backend lowers declarations, not bodies.
export const ROLL_SPAN = 10000;
export const E_TICK = 0;
export const E_ARRIVAL = 1;
export const E_JOB = 2;
export const F_NODE_LOSS = 3;
export const F_HUNG_TURN = 4;
export const F_MAILBOX_OVERFLOW = 5;
export const F_UNREADABLE_ROW = 6;
export const F_PROVIDER_429 = 7;
export const F_STALE_LEASE = 8;
export const F_CRASH = 9;
export const EVENT_KINDS = 10;
export const W_ARRIVAL = 250;
export const W_JOB = 1500;
export const W_NODE_LOSS = 6;
export const W_HUNG_TURN = 15;
export const W_MAILBOX_OVERFLOW = 4;
export const W_UNREADABLE_ROW = 25;
export const W_PROVIDER_429 = 10;
export const W_STALE_LEASE = 8;
export const W_CRASH = 40;
// t27c gen-js: fn step_event was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn is_fault was not emitted -- this backend lowers declarations, not bodies.
export const STEP_MAX_MS = 4000;
// t27c gen-js: fn step_ms was not emitted -- this backend lowers declarations, not bodies.
export const NODE_RESTART_MIN_SECONDS = 2;
export const NODE_RESTART_MAX_SECONDS = 180;
export const STALL_SECONDS = 1800;
export const PROVIDER_429_MIN_SECONDS = 30;
export const PROVIDER_429_MAX_SECONDS = 180;
export const REFUSED_REVIEW_MS = 500;
export const STALE_LEASE_MIN_SECONDS = 10;
export const STALE_LEASE_MAX_SECONDS = 120;
export const UNREADABLE_MIN_SECONDS = 600;
export const UNREADABLE_MAX_SECONDS = 7200;
export const WAIT_ANSWER_MS = 100;
export const REVIEW_MIN_SECONDS = 5;
export const REVIEW_MAX_SECONDS = 180;
export const BURST_OVER_CAP = 64;
// t27c gen-js: fn mailbox_burst was not emitted -- this backend lowers declarations, not bodies.
export const DB_MAX_MS = 50;
export const NET_LATENCY_MS = 5;
export const JOB_MAX_MS = 2000;
export const STALE_JOB_EVERY = 4;
export const STALE_PIDS_KEPT = 64;
// t27c gen-js: fn stale_job was not emitted -- this backend lowers declarations, not bodies.
export const REVIEW_KEYS = 6;
export const POOL_WORKERS = 6;
export const POOL_NODES = 2;
export const POOL_MAX_RESTARTS = 10;
export const POOL_PERIOD_SECONDS = 300;
export const W_ANSWER_LOST = 10;
// t27c gen-js: fn answer_lost was not emitted -- this backend lowers declarations, not bodies.
export const GIVE_UP_REARM_SECONDS = 600;
export const CLOCK_TICK_MAX_MICROS = 2000;
export const INV_NONE = 0;
export const INV_PID_REUSED = 1;
export const INV_DELIVERED_AFTER_EXIT = 2;
export const INV_INTENSITY = 3;
export const INV_OVER_CAP = 4;
export const INV_RESTART_WITHOUT_EXIT = 5;
export const INV_HOT_LOOP = 6;
export const INV_RUNS_DIFFER = 7;
export const INV_RARE_STATE_MISSED = 8;
export const INV_TAKEN_NOT_HANDLED = 9;
export const INV_KINDS = 10;
// t27c gen-js: fn fails_gate was not emitted -- this backend lowers declarations, not bodies.
export const SECONDS_PER_MINUTE = 60;
export const HOT_ROW_SLACK = 1;
// t27c gen-js: fn hot_row_bound was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn hot_loop was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn over_cap was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn intensity_kept was not emitted -- this backend lowers declarations, not bodies.
export const RARE_MAILBOX_FULL = 0;
export const RARE_INTENSITY_SPENT = 1;
export const RARE_TURN_KILLED = 2;
export const RARE_MAIL_TO_LOST_NODE = 3;
export const RARE_WAIT_BACKED_OFF = 4;
export const RARE_SLICE_YIELDED = 5;
export const RARE_MOVED_NODE = 6;
export const RARE_REVIEW_STOPPED = 7;
export const RARE_KINDS = 8;
// t27c gen-js: fn must_reach was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["SEEDS_PER_RUN", "STEPS_PER_RUN", "RUNS_PER_SEED", "GATE_BASE_SEED", "FEATURE_TURN_STOP", "TURN_STOP_EVERY", "STORE_SEEDS_PER_RUN", "TAIL_SECONDS", "LOG_TAIL_LINES", "MASK32", "STREAM_SEED", "STREAM_STEP", "STREAM_DELAY", "STREAM_TARGET", "STREAM_DURATION", "STREAM_ATTEMPT", "STREAM_LATENCY", "STREAM_CLOCK", "STREAM_STORE", "ROLL_SPAN", "E_TICK", "E_ARRIVAL", "E_JOB", "F_NODE_LOSS", "F_HUNG_TURN", "F_MAILBOX_OVERFLOW", "F_UNREADABLE_ROW", "F_PROVIDER_429", "F_STALE_LEASE", "F_CRASH", "EVENT_KINDS", "W_ARRIVAL", "W_JOB", "W_NODE_LOSS", "W_HUNG_TURN", "W_MAILBOX_OVERFLOW", "W_UNREADABLE_ROW", "W_PROVIDER_429", "W_STALE_LEASE", "W_CRASH", "STEP_MAX_MS", "NODE_RESTART_MIN_SECONDS", "NODE_RESTART_MAX_SECONDS", "STALL_SECONDS", "PROVIDER_429_MIN_SECONDS", "PROVIDER_429_MAX_SECONDS", "REFUSED_REVIEW_MS", "STALE_LEASE_MIN_SECONDS", "STALE_LEASE_MAX_SECONDS", "UNREADABLE_MIN_SECONDS", "UNREADABLE_MAX_SECONDS", "WAIT_ANSWER_MS", "REVIEW_MIN_SECONDS", "REVIEW_MAX_SECONDS", "BURST_OVER_CAP", "DB_MAX_MS", "NET_LATENCY_MS", "JOB_MAX_MS", "STALE_JOB_EVERY", "STALE_PIDS_KEPT", "REVIEW_KEYS", "POOL_WORKERS", "POOL_NODES", "POOL_MAX_RESTARTS", "POOL_PERIOD_SECONDS", "W_ANSWER_LOST", "GIVE_UP_REARM_SECONDS", "CLOCK_TICK_MAX_MICROS", "INV_NONE", "INV_PID_REUSED", "INV_DELIVERED_AFTER_EXIT", "INV_INTENSITY", "INV_OVER_CAP", "INV_RESTART_WITHOUT_EXIT", "INV_HOT_LOOP", "INV_RUNS_DIFFER", "INV_RARE_STATE_MISSED", "INV_TAKEN_NOT_HANDLED", "INV_KINDS", "SECONDS_PER_MINUTE", "HOT_ROW_SLACK", "RARE_MAILBOX_FULL", "RARE_INTENSITY_SPENT", "RARE_TURN_KILLED", "RARE_MAIL_TO_LOST_NODE", "RARE_WAIT_BACKED_OFF", "RARE_SLICE_YIELDED", "RARE_MOVED_NODE", "RARE_REVIEW_STOPPED", "RARE_KINDS"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
