// Generated by `t27c gen-js` from actors.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const NO_PID = 0;
export const GEN_MASK = 4294967295;
// t27c gen-js: fn pid_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn slot_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn gen_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn next_gen was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn reaches was not emitted -- this backend lowers declarations, not bodies.
export const D_QUEUED = 0;
export const D_DROPPED_DEAD = 1;
export const D_DROPPED_FULL = 2;
export const SEND_BLOCKS = false;
export const SEND_ACKNOWLEDGED = false;
export const MAILBOX_CAP = 256;
// t27c gen-js: fn deliver was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn ordered was not emitted -- this backend lowers declarations, not bodies.
export const MBOX_SLOTS = 8;
export const SLOT_BITS = 8;
export const TAG_MASK = 255;
export const NO_MATCH = 8;
// t27c gen-js: fn mbox_tag was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn mbox_len was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn mbox_push was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn mbox_find was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn mbox_remove was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn receive was not emitted -- this backend lowers declarations, not bodies.
export const RCV_MATCH = 0;
export const RCV_WAIT = 1;
export const RCV_TIMEOUT = 2;
export const AFTER_INFINITY = 4294967295;
// t27c gen-js: fn receive_outcome was not emitted -- this backend lowers declarations, not bodies.
export const LANE_DATA = 0;
export const LANE_CONTROL = 1;
export const LANE_NONE = 2;
export const D_COALESCED = 3;
// t27c gen-js: fn deliver_control was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn is_dead_letter was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn next_lane was not emitted -- this backend lowers declarations, not bodies.
export const CTL_TAGS = 64;
export const CTL_BIT = 1;
// t27c gen-js: fn bit was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn ctl_pending was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn ctl_post was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn ctl_next was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn ctl_take was not emitted -- this backend lowers declarations, not bodies.
export const CALL_PENDING = 0;
export const CALL_REPLY = 1;
export const CALL_DOWN = 2;
export const CALL_TIMEOUT = 3;
// t27c gen-js: fn call_outcome was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn live_alias was not emitted -- this backend lowers declarations, not bodies.
export const CALL_CYCLE = 4;
export const CALL_TOO_DEEP = 5;
export const CHAIN_SLOTS = 64;
export const CALL_MAX_DEPTH = 8;
// t27c gen-js: fn chain_has was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn chain_add was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn call_admit was not emitted -- this backend lowers declarations, not bodies.
export const X_NORMAL = 0;
export const X_SHUTDOWN = 1;
export const X_KILL = 2;
export const X_KILLED = 3;
export const X_CRASH = 4;
export const X_NOPROC = 5;
export const X_NOCONNECTION = 6;
export const X_NONE = 99;
export const ACT_IGNORE = 0;
export const ACT_DIE = 1;
export const ACT_MESSAGE = 2;
// t27c gen-js: fn on_exit_signal was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn death_reason was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn links_after_link was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn attach_answer was not emitted -- this backend lowers declarations, not bodies.
export const MONITOR_KILLS_WATCHER = false;
// t27c gen-js: fn monitors_after_monitor was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn down_left_after_demonitor was not emitted -- this backend lowers declarations, not bodies.
export const RESTART_PERMANENT = 0;
export const RESTART_TRANSIENT = 1;
export const RESTART_TEMPORARY = 2;
// t27c gen-js: fn should_restart was not emitted -- this backend lowers declarations, not bodies.
export const STRAT_ONE_FOR_ONE = 0;
export const STRAT_ONE_FOR_ALL = 1;
export const STRAT_REST_FOR_ONE = 2;
// t27c gen-js: fn affected was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn stopped_by_restart was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn restarted was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn stop_rank was not emitted -- this backend lowers declarations, not bodies.
export const SUP_NOTHING = 0;
export const SUP_RESTART = 1;
export const SUP_GIVE_UP = 2;
export const GIVE_UP_REASON = X_SHUTDOWN;
// t27c gen-js: fn in_period was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn intensity_exceeded was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn on_child_exit was not emitted -- this backend lowers declarations, not bodies.
export const BACKOFF_BASE_SECONDS = 10;
export const BACKOFF_CAP_SECONDS = 300;
export const STABLE_SECONDS = 600;
export const UNSTABLE_GIVE_UP = 6;
// t27c gen-js: fn unstable_streak was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn backoff_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn with_backoff was not emitted -- this backend lowers declarations, not bodies.
export const JITTER_PERCENT = 20;
export const PHI_HASH = 2654435769;
// t27c gen-js: fn seed_hash was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn jittered_seconds was not emitted -- this backend lowers declarations, not bodies.
export const SHUTDOWN_BRUTAL = 0;
export const SHUTDOWN_INFINITY = 4294967295;
// t27c gen-js: fn stop_signal was not emitted -- this backend lowers declarations, not bodies.
export const AUTO_NEVER = 0;
export const AUTO_ANY_SIGNIFICANT = 1;
export const AUTO_ALL_SIGNIFICANT = 2;
export const AUTO_SHUTDOWN_REASON = X_SHUTDOWN;
// t27c gen-js: fn child_spec_valid was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn auto_shutdown_after_exit was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn auto_shutdown_sticks was not emitted -- this backend lowers declarations, not bodies.
export const START_OK = 0;
export const START_MAX_CHILDREN = 1;
// t27c gen-js: fn start_answer was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn children_after_exit was not emitted -- this backend lowers declarations, not bodies.
export const QK_INTAKE = 0;
export const QK_RECONCILER = 1;
export const QK_DOMAIN_SUP = 2;
export const QK_AGENT = 3;
export const QK_NONE = 99;
export const QUEEN_ROOT_STRATEGY = STRAT_ONE_FOR_ONE;
export const QUEEN_DOMAIN_STRATEGY = STRAT_ONE_FOR_ONE;
export const QUEEN_AUTO_SHUTDOWN = AUTO_NEVER;
// t27c gen-js: fn root_children was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn root_child_kind was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn queen_restart_type was not emitted -- this backend lowers declarations, not bodies.
export const DOMAIN_MAX_RESTARTS = 3;
export const DOMAIN_PERIOD_SECONDS = 300;
export const ROOT_MAX_RESTARTS = 2;
export const ROOT_PERIOD_SECONDS = 900;
export const WORKER_SHUTDOWN_MS = 5000;
export const AGENT_SHUTDOWN_MS = 30000;
// t27c gen-js: fn queen_shutdown_ms was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn stops_inside_the_lease was not emitted -- this backend lowers declarations, not bodies.
export const M_TASK_OFFER = 1;
export const M_CANCEL = 2;
export const M_HEARTBEAT_DUE = 3;
// t27c gen-js: fn lane_of was not emitted -- this backend lowers declarations, not bodies.
export const TURN_MAX_SECONDS = 3600;
// t27c gen-js: fn hung_turn_signal was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn turn_signal was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn reclaim_wait_seconds was not emitted -- this backend lowers declarations, not bodies.
export const SLICE_TURNS = 64;
export const SLICE_MICROS = 5000;
// t27c gen-js: fn slice_spent was not emitted -- this backend lowers declarations, not bodies.
export const ISO_LOOP = 0;
export const ISO_THREAD = 1;
export const ISO_PROCESS = 2;
// t27c gen-js: fn turn_isolation was not emitted -- this backend lowers declarations, not bodies.
export const KILL_ABANDONS = 0;
export const KILL_STOPS = 1;
// t27c gen-js: fn kill_effect was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn holds_after_kill was not emitted -- this backend lowers declarations, not bodies.
export const NODE_BITS = 12;
export const LOCAL_SLOT_BITS = 20;
export const LOCAL_SLOT_MASK = 1048575;
export const MAX_NODE = 4095;
// t27c gen-js: fn node_pid was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn node_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn local_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn is_remote was not emitted -- this backend lowers declarations, not bodies.
export const NODE_HEARTBEAT_SECONDS = 5;
export const NODE_TTL_SECONDS = 20;
// t27c gen-js: fn node_up was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn send_remote was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn remote_down was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn place_before was not emitted -- this backend lowers declarations, not bodies.
export const MAILBOX_BOUNDED = true;
export const HOT_CODE_SWAP = false;
export const TRANSPARENT_DISTRIBUTION = true;
export const PREEMPTIVE_REDUCTIONS = false;
export const PREEMPTIVE_SLICES = true;
export const GLOBAL_NAME_REGISTRY = false;
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["NO_PID", "GEN_MASK", "D_QUEUED", "D_DROPPED_DEAD", "D_DROPPED_FULL", "SEND_BLOCKS", "SEND_ACKNOWLEDGED", "MAILBOX_CAP", "MBOX_SLOTS", "SLOT_BITS", "TAG_MASK", "NO_MATCH", "RCV_MATCH", "RCV_WAIT", "RCV_TIMEOUT", "AFTER_INFINITY", "LANE_DATA", "LANE_CONTROL", "LANE_NONE", "D_COALESCED", "CTL_TAGS", "CTL_BIT", "CALL_PENDING", "CALL_REPLY", "CALL_DOWN", "CALL_TIMEOUT", "CALL_CYCLE", "CALL_TOO_DEEP", "CHAIN_SLOTS", "CALL_MAX_DEPTH", "X_NORMAL", "X_SHUTDOWN", "X_KILL", "X_KILLED", "X_CRASH", "X_NOPROC", "X_NOCONNECTION", "X_NONE", "ACT_IGNORE", "ACT_DIE", "ACT_MESSAGE", "MONITOR_KILLS_WATCHER", "RESTART_PERMANENT", "RESTART_TRANSIENT", "RESTART_TEMPORARY", "STRAT_ONE_FOR_ONE", "STRAT_ONE_FOR_ALL", "STRAT_REST_FOR_ONE", "SUP_NOTHING", "SUP_RESTART", "SUP_GIVE_UP", "GIVE_UP_REASON", "BACKOFF_BASE_SECONDS", "BACKOFF_CAP_SECONDS", "STABLE_SECONDS", "UNSTABLE_GIVE_UP", "JITTER_PERCENT", "PHI_HASH", "SHUTDOWN_BRUTAL", "SHUTDOWN_INFINITY", "AUTO_NEVER", "AUTO_ANY_SIGNIFICANT", "AUTO_ALL_SIGNIFICANT", "AUTO_SHUTDOWN_REASON", "START_OK", "START_MAX_CHILDREN", "QK_INTAKE", "QK_RECONCILER", "QK_DOMAIN_SUP", "QK_AGENT", "QK_NONE", "QUEEN_ROOT_STRATEGY", "QUEEN_DOMAIN_STRATEGY", "QUEEN_AUTO_SHUTDOWN", "DOMAIN_MAX_RESTARTS", "DOMAIN_PERIOD_SECONDS", "ROOT_MAX_RESTARTS", "ROOT_PERIOD_SECONDS", "WORKER_SHUTDOWN_MS", "AGENT_SHUTDOWN_MS", "M_TASK_OFFER", "M_CANCEL", "M_HEARTBEAT_DUE", "TURN_MAX_SECONDS", "SLICE_TURNS", "SLICE_MICROS", "ISO_LOOP", "ISO_THREAD", "ISO_PROCESS", "KILL_ABANDONS", "KILL_STOPS", "NODE_BITS", "LOCAL_SLOT_BITS", "LOCAL_SLOT_MASK", "MAX_NODE", "NODE_HEARTBEAT_SECONDS", "NODE_TTL_SECONDS", "MAILBOX_BOUNDED", "HOT_CODE_SWAP", "TRANSPARENT_DISTRIBUTION", "PREEMPTIVE_REDUCTIONS", "PREEMPTIVE_SLICES", "GLOBAL_NAME_REGISTRY"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
