// Generated by `t27c gen-js` from review_valve.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const KIND_UNRECORDED = 0;
export const KIND_NO_CRITERIA = 1;
export const KIND_SEND_BACK_CEILING = 2;
export const KIND_DEAD_LETTER = 3;
export const KIND_REVIEWER_GAVE_UP = 4;
export const KIND_EMPTY_ACCEPT = 5;
export const KIND_BEYOND_THE_PATCH = 6;
export const KIND_BASE_TRUTH_ALONE = 7;
export const STEP_HOLD = 0;
export const STEP_RELEASE = 1;
export const STEP_BACKFILL = 2;
export const STEP_CLOSE = 3;
export const OBSOLETE_STATE = "obsolete";
export const RETRY_FLOOR_MINUTES = 30;
export const CEILING_FLOOR_MINUTES = 60;
export const BACKFILL_WINDOW_MINUTES = 120;
export const MAX_RELEASES = 1;
export const POLICY_HOLD_MINUTES = 2880;
export const REVIEWER_LOGIN = "t27-bees[bot]";
export const QUEEN_BRANCH_PREFIX = "queen-";
export const PR_FIX_ATTEMPTS = 2;
export const PR_FIX_WINDOW_HOURS = 48;
export const PR_NONE = 0;
export const PR_JUDGE = 1;
export const PR_WAIT_FIX = 2;
export const PR_CLOSE = 3;
// t27c gen-js: fn escalation_kind was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn wants_backfill was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn next_step was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn holds_files was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn pr_step was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["KIND_UNRECORDED", "KIND_NO_CRITERIA", "KIND_SEND_BACK_CEILING", "KIND_DEAD_LETTER", "KIND_REVIEWER_GAVE_UP", "KIND_EMPTY_ACCEPT", "KIND_BEYOND_THE_PATCH", "KIND_BASE_TRUTH_ALONE", "STEP_HOLD", "STEP_RELEASE", "STEP_BACKFILL", "STEP_CLOSE", "OBSOLETE_STATE", "RETRY_FLOOR_MINUTES", "CEILING_FLOOR_MINUTES", "BACKFILL_WINDOW_MINUTES", "MAX_RELEASES", "POLICY_HOLD_MINUTES", "REVIEWER_LOGIN", "QUEEN_BRANCH_PREFIX", "PR_FIX_ATTEMPTS", "PR_FIX_WINDOW_HOURS", "PR_NONE", "PR_JUDGE", "PR_WAIT_FIX", "PR_CLOSE"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
