// Generated by `t27c gen-ts` from keyed_guard.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const HOLDER_PROCESS = 0 satisfies number;
// t27c gen-ts: fn claim_lands_for was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn round_renews was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn end_releases was not emitted -- this backend lowers declarations, not bodies.
export const ADMISSION_RESTART = 0 satisfies number;
export const ADMISSION_STRATEGY = 0 satisfies number;
export const ADMISSION_MAX_RESTARTS = 3 satisfies number;
export const ADMISSION_PERIOD_SECONDS = 300 satisfies number;
export const AD_ASK = 0 satisfies number;
export const AD_GRANT = 1 satisfies number;
export const AD_KEEP = 2 satisfies number;
export const AD_WAIT = 3 satisfies number;
export const AD_REFUSED = 4 satisfies number;
export const AD_GIVE_BACK = 5 satisfies number;
// t27c gen-ts: fn admit_answer was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn answer_takes_lane was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn answer_waits was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn grant_lands was not emitted -- this backend lowers declarations, not bodies.
export const IA_START = 0 satisfies number;
export const IA_WAIT = 1 satisfies number;
export const IA_IDLE = 2 satisfies number;
// t27c gen-ts: fn after_admission was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn lane_outlives_holder was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn wake_count was not emitted -- this backend lowers declarations, not bodies.
export const CHAIN_CALLERS = 9 satisfies number;
// t27c gen-ts: fn on_chain was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn call_admit_chain was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const CALL_CYCLE = 4 satisfies number;
export const CALL_DOWN = 2 satisfies number;
export const CALL_MAX_DEPTH = 8 satisfies number;
export const CALL_PENDING = 0 satisfies number;
export const CALL_REPLY = 1 satisfies number;
export const CALL_TIMEOUT = 3 satisfies number;
export const CALL_TOO_DEEP = 5 satisfies number;
export const CHAIN_SLOTS = 64 satisfies number;
export const CTL_BIT = 1 satisfies number;
export const DOMAIN_MAX_RESTARTS = 3 satisfies number;
export const DOMAIN_PERIOD_SECONDS = 300 satisfies number;
export const GEN_MASK = 4294967295 satisfies number;
export const NO_PID = 0 satisfies number;
export const RESTART_PERMANENT = 0 satisfies number;
export const RESTART_TEMPORARY = 2 satisfies number;
export const STRAT_ONE_FOR_ALL = 1 satisfies number;
export const STRAT_ONE_FOR_ONE = 0 satisfies number;
export const STRAT_REST_FOR_ONE = 2 satisfies number;
// t27c gen-ts: fn affected was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn bit was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn call_admit was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn chain_add was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn chain_has was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn pid_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn reaches was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn restarted was not emitted -- this backend lowers declarations, not bodies.
export const KEY_NO_PID = 0 satisfies number;
// t27c gen-ts: fn claim_is_mine was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn lane_free was not emitted -- this backend lowers declarations, not bodies.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["HOLDER_PROCESS", "ADMISSION_RESTART", "ADMISSION_STRATEGY", "ADMISSION_MAX_RESTARTS", "ADMISSION_PERIOD_SECONDS", "AD_ASK", "AD_GRANT", "AD_KEEP", "AD_WAIT", "AD_REFUSED", "AD_GIVE_BACK", "IA_START", "IA_WAIT", "IA_IDLE", "CHAIN_CALLERS", "CALL_CYCLE", "CALL_DOWN", "CALL_MAX_DEPTH", "CALL_PENDING", "CALL_REPLY", "CALL_TIMEOUT", "CALL_TOO_DEEP", "CHAIN_SLOTS", "CTL_BIT", "DOMAIN_MAX_RESTARTS", "DOMAIN_PERIOD_SECONDS", "GEN_MASK", "NO_PID", "RESTART_PERMANENT", "RESTART_TEMPORARY", "STRAT_ONE_FOR_ALL", "STRAT_ONE_FOR_ONE", "STRAT_REST_FOR_ONE", "KEY_NO_PID"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
