// Generated by `t27c gen-ts` from waits.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const W_WAITING = 0 satisfies number;
export const W_RESOLVED = 1 satisfies number;
export const W_EXPIRED = 2 satisfies number;
export const W_CANCELLED = 3 satisfies number;
export const WAIT_STATES = 4 satisfies number;
export const EV_RESOLVE = 0 satisfies number;
export const EV_EXPIRE = 1 satisfies number;
export const EV_CANCEL = 2 satisfies number;
export const EV_RECHECK = 3 satisfies number;
export const NEVER = 4294967295 satisfies number;
// t27c gen-ts: fn is_terminal was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn state_after was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn transition_allowed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn valid_wait was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn wakes_owner was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn delivers_wake was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn resolution_lands was not emitted -- this backend lowers declarations, not bodies.
export const WA_NONE = 0 satisfies number;
export const WA_RESOLVE = 1 satisfies number;
export const WA_EXPIRE = 2 satisfies number;
export const WA_CHECK = 3 satisfies number;
// t27c gen-ts: fn wake_action was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn due_in_seconds was not emitted -- this backend lowers declarations, not bodies.
export const WAIT_MAX_SECONDS = 86400 satisfies number;
export const JOB_WAIT_LIMIT_SECONDS = 86400 satisfies number;
// t27c gen-ts: fn expiry_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn job_wait_seconds was not emitted -- this backend lowers declarations, not bodies.
export const CHECK_BASE_SECONDS = 30 satisfies number;
export const CHECK_CAP_SECONDS = 240 satisfies number;
export const CHECK_TIMEOUT_SECONDS = 20 satisfies number;
// t27c gen-ts: fn check_after_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn recheck_in_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn check_event was not emitted -- this backend lowers declarations, not bodies.
export const CLAIM_TTL_SECONDS = 60 satisfies number;
export const CLAIM_BATCH = 32 satisfies number;
// t27c gen-ts: fn epoch_after_claim was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn write_lands was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn more_now was not emitted -- this backend lowers declarations, not bodies.
export const WAIT_POLL_SECONDS = 15 satisfies number;
export const NOTIFY_IS_A_HINT = true satisfies boolean;
// t27c gen-ts: fn poll_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn beat_after_seconds was not emitted -- this backend lowers declarations, not bodies.
export const PH_NOW = 0 satisfies number;
export const PH_QUEUE = 1 satisfies number;
export const PH_DROP = 2 satisfies number;
// t27c gen-ts: fn pass_on_hint was not emitted -- this backend lowers declarations, not bodies.
export const DEPLOY_WRITES_WAITS = false satisfies boolean;
export const DEPLOY_DRAIN_SECONDS = 1800 satisfies number;
// t27c gen-ts: fn pickup_after_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn round_visits_job was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn step_parks was not emitted -- this backend lowers declarations, not bodies.
export const JOB_O_PASS = 0 satisfies number;
export const JOB_O_NOT_YET = 1 satisfies number;
export const JOB_O_FAIL = 2 satisfies number;
// t27c gen-ts: fn step_outcome was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["W_WAITING", "W_RESOLVED", "W_EXPIRED", "W_CANCELLED", "WAIT_STATES", "EV_RESOLVE", "EV_EXPIRE", "EV_CANCEL", "EV_RECHECK", "NEVER", "WA_NONE", "WA_RESOLVE", "WA_EXPIRE", "WA_CHECK", "WAIT_MAX_SECONDS", "JOB_WAIT_LIMIT_SECONDS", "CHECK_BASE_SECONDS", "CHECK_CAP_SECONDS", "CHECK_TIMEOUT_SECONDS", "CLAIM_TTL_SECONDS", "CLAIM_BATCH", "WAIT_POLL_SECONDS", "NOTIFY_IS_A_HINT", "PH_NOW", "PH_QUEUE", "PH_DROP", "DEPLOY_WRITES_WAITS", "DEPLOY_DRAIN_SECONDS", "JOB_O_PASS", "JOB_O_NOT_YET", "JOB_O_FAIL"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
