// Generated by `t27c gen-ts` from audit.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const AUDIT_STREAM = "vault" satisfies string;
export const EV_LEASE = 0 satisfies number;
export const EV_RENEW = 1 satisfies number;
export const EV_REVOKE = 2 satisfies number;
export const EV_EXPIRE = 3 satisfies number;
export const EV_DENY = 4 satisfies number;
export const EV_PUT = 5 satisfies number;
export const EV_ROTATE = 6 satisfies number;
export const EV_IMPORT = 7 satisfies number;
export const EV_EXPORT = 8 satisfies number;
export const EV_GRANT = 9 satisfies number;
export const EV_BREAK_GLASS = 10 satisfies number;
export const EV_ROTATION_DUE = 11 satisfies number;
export const EV_DEDUP = 12 satisfies number;
export const EV_MERGE = 13 satisfies number;
export const EV_AUDIT_READ = 14 satisfies number;
export const EV_CLASS = 15 satisfies number;
export const EV_BIND = 16 satisfies number;
export const KINDS = 17 satisfies number;
export const EVENT_NAMES = ["vault.lease", "vault.renew", "vault.revoke", "vault.expire", "vault.deny", "vault.put", "vault.rotate", "vault.import", "vault.export", "vault.grant", "vault.break_glass", "vault.rotation_due", "vault.dedup", "vault.merge", "vault.audit_read", "vault.class", "vault.bind"] as const satisfies readonly [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string];
export const F_OP = 0 satisfies number;
export const F_KEY = 1 satisfies number;
export const F_TIER = 2 satisfies number;
export const F_SCOPE = 3 satisfies number;
export const F_IDS = 4 satisfies number;
export const F_COUNT = 5 satisfies number;
export const F_LEASE = 6 satisfies number;
export const F_EXPIRES = 7 satisfies number;
export const F_RENEWALS = 8 satisfies number;
export const F_CODE = 9 satisfies number;
export const F_CLASS = 10 satisfies number;
export const F_INPUT = 11 satisfies number;
export const F_CT = 12 satisfies number;
export const F_REQ = 13 satisfies number;
export const F_REASON_SHA = 14 satisfies number;
export const F_REASON_LEN = 15 satisfies number;
export const F_SOURCE = 16 satisfies number;
export const F_FORMAT = 17 satisfies number;
export const F_SKIPPED = 18 satisfies number;
export const F_GROUPS = 19 satisfies number;
export const F_CONFLICTS = 20 satisfies number;
export const F_CANONICAL = 21 satisfies number;
export const F_ALIASES = 22 satisfies number;
export const F_AGE_DAYS = 23 satisfies number;
export const F_DISCARDED = 24 satisfies number;
export const F_SUBJECT = 25 satisfies number;
export const F_ENV = 26 satisfies number;
export const F_MODE = 27 satisfies number;
export const FIELDS = 28 satisfies number;
export const AUDIT_FIELDS = ["op", "key", "tier", "scope", "ids", "count", "lease", "expires", "renewals", "code", "class", "input", "ct", "req", "reason_sha", "reason_len", "source", "format", "skipped", "groups", "conflicts", "canonical", "aliases", "age_days", "discarded", "subject", "env", "mode"] as const satisfies readonly [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string];
export const KIND_FIELDS = [8446, 458, 74, 330, 8799, 7194, 7194, 461882, 4146, 33554446, 49394, 8389648, 1572898, 23073810, 34, 1042, 201326618] as const satisfies readonly [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
export const KIND_REQUIRED = [90, 66, 64, 64, 513, 5138, 5138, 196642, 4130, 33554438, 16466, 1040, 1572866, 6291458, 2, 1042, 201326602] as const satisfies readonly [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
// t27c gen-ts: fn field_allowed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn field_required was not emitted -- this backend lowers declarations, not bodies.
export const EVC_OK = 0 satisfies number;
export const EVC_UNKNOWN_KIND = 1 satisfies number;
export const EVC_FOREIGN_FIELD = 2 satisfies number;
export const EVC_MISSING_FIELD = 3 satisfies number;
export const EVC_BAD_CODE = 4 satisfies number;
// t27c gen-ts: fn event_code was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: "usize" is not declared in this module, so it is emitted as unknown rather than guessed at
export const TEXT_MAX = 192;
// t27c gen-ts: "usize" is not declared in this module, so it is emitted as unknown rather than guessed at
export const HASH_HEX_LEN = 16;
// t27c gen-ts: fn text_ok was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn hash_ok was not emitted -- this backend lowers declarations, not bodies.
export const AUDIT_PAGE_DEFAULT = 100 satisfies number;
export const AUDIT_PAGE_MAX = 500 satisfies number;
// t27c gen-ts: fn audit_page was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const BIND_MODE_NAMES = ["add", "replace", "remove"] as const satisfies readonly [string, string, string];
export const CLASS_OTHER = 5 satisfies number;
export const CODES = 34 satisfies number;
export const CODE_OK = 0 satisfies number;
export const DENY_NO_AUDIT = 17 satisfies number;
// t27c gen-ts: "usize" is not declared in this module, so it is emitted as unknown rather than guessed at
export const ID_MAX = 192;
export const INPUT_NAMES = ["tty", "stdin"] as const satisfies readonly [string, string];
export const OP_AUDIT = 9 satisfies number;
export const OP_NAMES_TEXT = ["lease", "renew", "revoke", "names", "put", "rotate", "import", "export", "grant", "audit", "break-glass", "dedup", "merge", "class", "bind"] as const satisfies readonly [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string];
export const ROTATE_AFTER_DAYS = [90, 180, 180, 365, 90, 180] as const satisfies readonly [number, number, number, number, number, number];
export const SECRET_CLASSES = 6 satisfies number;
// t27c gen-ts: fn class_or_other was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn deliver_code was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn deny_recorded was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn rotation_due was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn token_char was not emitted -- this backend lowers declarations, not bodies.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["AUDIT_STREAM", "EV_LEASE", "EV_RENEW", "EV_REVOKE", "EV_EXPIRE", "EV_DENY", "EV_PUT", "EV_ROTATE", "EV_IMPORT", "EV_EXPORT", "EV_GRANT", "EV_BREAK_GLASS", "EV_ROTATION_DUE", "EV_DEDUP", "EV_MERGE", "EV_AUDIT_READ", "EV_CLASS", "EV_BIND", "KINDS", "EVENT_NAMES", "F_OP", "F_KEY", "F_TIER", "F_SCOPE", "F_IDS", "F_COUNT", "F_LEASE", "F_EXPIRES", "F_RENEWALS", "F_CODE", "F_CLASS", "F_INPUT", "F_CT", "F_REQ", "F_REASON_SHA", "F_REASON_LEN", "F_SOURCE", "F_FORMAT", "F_SKIPPED", "F_GROUPS", "F_CONFLICTS", "F_CANONICAL", "F_ALIASES", "F_AGE_DAYS", "F_DISCARDED", "F_SUBJECT", "F_ENV", "F_MODE", "FIELDS", "AUDIT_FIELDS", "KIND_FIELDS", "KIND_REQUIRED", "EVC_OK", "EVC_UNKNOWN_KIND", "EVC_FOREIGN_FIELD", "EVC_MISSING_FIELD", "EVC_BAD_CODE", "TEXT_MAX", "HASH_HEX_LEN", "AUDIT_PAGE_DEFAULT", "AUDIT_PAGE_MAX", "BIND_MODE_NAMES", "CLASS_OTHER", "CODES", "CODE_OK", "DENY_NO_AUDIT", "ID_MAX", "INPUT_NAMES", "OP_AUDIT", "OP_NAMES_TEXT", "ROTATE_AFTER_DAYS", "SECRET_CLASSES"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
