// Generated by `t27c gen-ts` from turn_stop.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const TURN_STOP_GRACE_MS = 3000 satisfies number;
export const LANE_FREE_MS = 5000 satisfies number;
export const KILL_LANDS_MS = 2000 satisfies number;
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const STEP_CUT = 0 satisfies number;
export const STEP_RUN = 1 satisfies number;
// t27c gen-ts: fn step_on_abort was not emitted -- this backend lowers declarations, not bodies.
export const ESC_NOTHING = 0 satisfies number;
export const ESC_KILL_GROUP = 1 satisfies number;
export const ESC_ABANDON = 2 satisfies number;
// t27c gen-ts: fn escalation was not emitted -- this backend lowers declarations, not bodies.
export const U32_MAX = 4294967295 satisfies number;
// t27c gen-ts: fn in_flight was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["TURN_STOP_GRACE_MS", "LANE_FREE_MS", "KILL_LANDS_MS", "STEP_CUT", "STEP_RUN", "ESC_NOTHING", "ESC_KILL_GROUP", "ESC_ABANDON", "U32_MAX"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
