// Generated by `t27c gen-js` from dashboard.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const DASH_KINDS = 10;
// t27c gen-js: fn free_lanes was not emitted -- this backend lowers declarations, not bodies.
export const IV_FULL = 0;
export const IV_PACING = 1;
export const IV_FILES = 2;
export const IV_SHAPE = 3;
export const IV_CLAIMED = 4;
export const IV_EMPTY = 5;
export const IV_UNKNOWN = 6;
export const VERDICT_NAMES = ["full", "pacing", "files", "shape", "claimed", "empty", "unknown"];
// t27c gen-js: fn idle_verdict was not emitted -- this backend lowers declarations, not bodies.
export const TONE_NONE = 0;
export const TONE_OK = 1;
export const TONE_WARN = 2;
export const TONE_ACT = 3;
export const VERDICT_TONE = [1, 1, 2, 3, 2, 3, 0];
// t27c gen-js: fn verdict_tone was not emitted -- this backend lowers declarations, not bodies.
export const TIMELINE_MAX = 50;
export const IN_TIMELINE = [1, 1, 0, 1, 1, 1, 1, 1, 0, 0];
// t27c gen-js: fn timeline_shows was not emitted -- this backend lowers declarations, not bodies.
export const LS_NONE = 0;
export const LS_LIVE = 1;
export const LS_EXPIRED = 2;
// t27c gen-js: fn lease_state was not emitted -- this backend lowers declarations, not bodies.
export const LANE_NONE = 0;
export const LANE_REPO = 1;
export const LANE_KIND = 2;
export const LANE_NAMES = ["none", "repo", "kind"];
export const LANES_MAX = 8;
// t27c gen-js: fn lane_shown was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["DASH_KINDS", "IV_FULL", "IV_PACING", "IV_FILES", "IV_SHAPE", "IV_CLAIMED", "IV_EMPTY", "IV_UNKNOWN", "VERDICT_NAMES", "TONE_NONE", "TONE_OK", "TONE_WARN", "TONE_ACT", "VERDICT_TONE", "TIMELINE_MAX", "IN_TIMELINE", "LS_NONE", "LS_LIVE", "LS_EXPIRED", "LANE_NONE", "LANE_REPO", "LANE_KIND", "LANE_NAMES", "LANES_MAX"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
