// Generated by `t27c gen-ts` from host.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const TIER_OWNER = 0 satisfies number;
export const TIER_TRUSTED = 1 satisfies number;
export const TIER_PUBLIC = 2 satisfies number;
export const TIERS = 3 satisfies number;
export const ALLOW_NONE = 255 satisfies number;
// t27c gen-ts: fn tier_of was not emitted -- this backend lowers declarations, not bodies.
export const WC_SHARD = 0 satisfies number;
export const WC_SERVICE = 1 satisfies number;
export const WC_STATEFUL = 2 satisfies number;
export const CLASSES = 3 satisfies number;
// t27c gen-ts: fn eligible was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn checked_by_agreement was not emitted -- this backend lowers declarations, not bodies.
export const SLOTS_MAX_OWNER = 16 satisfies number;
export const SLOTS_MAX_TRUSTED = 4 satisfies number;
export const SLOTS_MAX_PUBLIC = 2 satisfies number;
// t27c gen-ts: fn slots_admitted was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn has_room was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn host_up was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn host_write_admitted was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn must_register_again was not emitted -- this backend lowers declarations, not bodies.
export const REQUEST_SKEW_SECONDS = 30 satisfies number;
// t27c gen-ts: fn request_fresh was not emitted -- this backend lowers declarations, not bodies.
export const STRIKES_MAX = 3 satisfies number;
// t27c gen-ts: fn suspended was not emitted -- this backend lowers declarations, not bodies.
export const TA_DOWNLOAD = 0 satisfies number;
export const TA_USE_LOCAL = 1 satisfies number;
export const TA_REFUSE = 2 satisfies number;
// t27c gen-ts: fn toolchain_action was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn download_kept was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const MAX_INCARNATION = 4095 satisfies number;
export const NODE_HEARTBEAT_SECONDS = 5 satisfies number;
export const NODE_TTL_SECONDS = 20 satisfies number;
export const NO_INCARNATION = 0 satisfies number;
export const SELF_FENCE_SECONDS = 15 satisfies number;
// t27c gen-ts: fn lease_up was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn must_fence was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn next_incarnation was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn write_admitted was not emitted -- this backend lowers declarations, not bodies.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["TIER_OWNER", "TIER_TRUSTED", "TIER_PUBLIC", "TIERS", "ALLOW_NONE", "WC_SHARD", "WC_SERVICE", "WC_STATEFUL", "CLASSES", "SLOTS_MAX_OWNER", "SLOTS_MAX_TRUSTED", "SLOTS_MAX_PUBLIC", "REQUEST_SKEW_SECONDS", "STRIKES_MAX", "TA_DOWNLOAD", "TA_USE_LOCAL", "TA_REFUSE", "MAX_INCARNATION", "NODE_HEARTBEAT_SECONDS", "NODE_TTL_SECONDS", "NO_INCARNATION", "SELF_FENCE_SECONDS"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
