// Generated by `t27c gen-ts` from placement.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

// t27c gen-ts: fn may_take was not emitted -- this backend lowers declarations, not bodies.
export const ORIGIN_V4_PREFIX_BITS = 24 satisfies number;
export const ORIGIN_V6_PREFIX_BITS = 48 satisfies number;
// t27c gen-ts: fn origin_blocks was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn spread_ok was not emitted -- this backend lowers declarations, not bodies.
export const LEASES_MAX_PER_JOB = 6 satisfies number;
// t27c gen-ts: fn open_replicas was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn exhausted was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn places was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn job_first was not emitted -- this backend lowers declarations, not bodies.
export const JOB_RUN_BOUND_SECONDS = 300 satisfies number;
export const RECEIPT_GRACE_SECONDS = 30 satisfies number;
// t27c gen-ts: fn replica_lapsed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn half_fits was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn may_take_half was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const CLASSES = 3 satisfies number;
export const ISO_JOBDIR = 2 satisfies number;
export const ISO_LEVELS = 4 satisfies number;
export const ISO_NONE = 0 satisfies number;
export const STRIKES_MAX = 3 satisfies number;
export const TIERS = 3 satisfies number;
export const TIER_OWNER = 0 satisfies number;
export const TIER_PUBLIC = 2 satisfies number;
export const TIER_TRUSTED = 1 satisfies number;
export const WC_SERVICE = 1 satisfies number;
export const WC_SHARD = 0 satisfies number;
export const WC_STATEFUL = 2 satisfies number;
// t27c gen-ts: fn eligible was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn has_room was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn host_up was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn isolation_meets was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn isolation_required was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn suspended was not emitted -- this backend lowers declarations, not bodies.
export const RC_LATE = 6 satisfies number;
export const REPLICAS_K = 2 satisfies number;
export const REPLICAS_MAX = 3 satisfies number;
export const HALF_REFERENCE = 0 satisfies number;
export const HALF_T27B = 1 satisfies number;
export const ARCH_ARM64 = 0 satisfies number;
export const ARCH_X64 = 1 satisfies number;
export const NODE_TTL_SECONDS = 20 satisfies number;
// t27c gen-ts: fn lease_up was not emitted -- this backend lowers declarations, not bodies.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["ORIGIN_V4_PREFIX_BITS", "ORIGIN_V6_PREFIX_BITS", "LEASES_MAX_PER_JOB", "JOB_RUN_BOUND_SECONDS", "RECEIPT_GRACE_SECONDS", "CLASSES", "ISO_JOBDIR", "ISO_LEVELS", "ISO_NONE", "STRIKES_MAX", "TIERS", "TIER_OWNER", "TIER_PUBLIC", "TIER_TRUSTED", "WC_SERVICE", "WC_SHARD", "WC_STATEFUL", "RC_LATE", "REPLICAS_K", "REPLICAS_MAX", "HALF_REFERENCE", "HALF_T27B", "ARCH_ARM64", "ARCH_X64", "NODE_TTL_SECONDS"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
