// Generated by `t27c gen-ts` from claim.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const CL_RUNNING = 0 satisfies number;
export const CL_ACCEPTED = 1 satisfies number;
export const CL_REJECTED = 2 satisfies number;
export const CL_AWAITING_REVIEW = 3 satisfies number;
export const CL_FAILED = 4 satisfies number;
export const CL_CANCELLED = 5 satisfies number;
export const CLAIM_STATES = 6 satisfies number;
export const V_NONE = 0 satisfies number;
export const V_ACCEPT = 1 satisfies number;
export const V_SEND_BACK = 2 satisfies number;
export const V_ESCALATE = 3 satisfies number;
export const V_WAIT = 4 satisfies number;
export const V_FAILED = 5 satisfies number;
export const V_CANCELLED = 6 satisfies number;
export const V_EMPTY = 7 satisfies number;
export const V_STALE_CONTRACT = 8 satisfies number;
export const V_OBSOLETE = 9 satisfies number;
export const V_OTHER = 10 satisfies number;
export const VERDICT_CODES = 11 satisfies number;
export const SEND_BACK_FLOOR_MINUTES = 60 satisfies number;
export const WAIT_FROZEN_FLOOR_MINUTES = 360 satisfies number;
export const DEFAULT_SEND_BACK_CEILING = 2 satisfies number;
export const FREE_ATTEMPT_CEILING = 3 satisfies number;
export const REVIEWER_MISS_CEILING = 3 satisfies number;
export const UNREAD_CRITERIA = 1 satisfies number;
// t27c gen-ts: fn claim_of_step was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn criteria_read_as was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn escalation_kind_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn claim_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const BACKFILL_WINDOW_MINUTES = 120 satisfies number;
export const CEILING_FLOOR_MINUTES = 60 satisfies number;
export const KIND_BASE_TRUTH_ALONE = 7 satisfies number;
export const KIND_BEYOND_THE_PATCH = 6 satisfies number;
export const KIND_DEAD_LETTER = 3 satisfies number;
export const KIND_NO_CRITERIA = 1 satisfies number;
export const KIND_REVIEWER_GAVE_UP = 4 satisfies number;
export const KIND_SEND_BACK_CEILING = 2 satisfies number;
export const KIND_UNRECORDED = 0 satisfies number;
export const MAX_RELEASES = 1 satisfies number;
export const RETRY_FLOOR_MINUTES = 30 satisfies number;
export const STEP_BACKFILL = 2 satisfies number;
export const STEP_CLOSE = 3 satisfies number;
export const STEP_HOLD = 0 satisfies number;
export const STEP_RELEASE = 1 satisfies number;
// t27c gen-ts: fn escalation_kind was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn next_step was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn wants_backfill was not emitted -- this backend lowers declarations, not bodies.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["CL_RUNNING", "CL_ACCEPTED", "CL_REJECTED", "CL_AWAITING_REVIEW", "CL_FAILED", "CL_CANCELLED", "CLAIM_STATES", "V_NONE", "V_ACCEPT", "V_SEND_BACK", "V_ESCALATE", "V_WAIT", "V_FAILED", "V_CANCELLED", "V_EMPTY", "V_STALE_CONTRACT", "V_OBSOLETE", "V_OTHER", "VERDICT_CODES", "SEND_BACK_FLOOR_MINUTES", "WAIT_FROZEN_FLOOR_MINUTES", "DEFAULT_SEND_BACK_CEILING", "FREE_ATTEMPT_CEILING", "REVIEWER_MISS_CEILING", "UNREAD_CRITERIA", "BACKFILL_WINDOW_MINUTES", "CEILING_FLOOR_MINUTES", "KIND_BASE_TRUTH_ALONE", "KIND_BEYOND_THE_PATCH", "KIND_DEAD_LETTER", "KIND_NO_CRITERIA", "KIND_REVIEWER_GAVE_UP", "KIND_SEND_BACK_CEILING", "KIND_UNRECORDED", "MAX_RELEASES", "RETRY_FLOOR_MINUTES", "STEP_BACKFILL", "STEP_CLOSE", "STEP_HOLD", "STEP_RELEASE"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
