// Generated by `t27c gen-ts` from jobs.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const SK_CHECK = 0 satisfies number;
export const SK_WAIT = 1 satisfies number;
export const SK_EFFECT = 2 satisfies number;
export const STEP_KINDS = 3 satisfies number;
export const J_RUNNING = 0 satisfies number;
export const J_DONE = 1 satisfies number;
export const J_FAILED = 2 satisfies number;
export const J_CANCELLED = 3 satisfies number;
export const O_PASS = 0 satisfies number;
export const O_NOT_YET = 1 satisfies number;
export const O_FAIL = 2 satisfies number;
export const O_BLOCKED = 3 satisfies number;
export const A_ADVANCE = 0 satisfies number;
export const A_STAY = 1 satisfies number;
export const A_RETRY = 2 satisfies number;
export const A_FAIL = 3 satisfies number;
export const STEP_RUN_LIMIT = 3 satisfies number;
export const WAIT_LIMIT_MINUTES = 1440 satisfies number;
// t27c gen-ts: fn step_action was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn job_state_after was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn step_after was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn cancel_allowed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn is_terminal was not emitted -- this backend lowers declarations, not bodies.
export const E_RUN = 0 satisfies number;
export const E_REHEARSE = 1 satisfies number;
export const E_REFUSE = 2 satisfies number;
// t27c gen-ts: fn effect_may_run was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn job_may_start was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn job_holds_a_lane was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["SK_CHECK", "SK_WAIT", "SK_EFFECT", "STEP_KINDS", "J_RUNNING", "J_DONE", "J_FAILED", "J_CANCELLED", "O_PASS", "O_NOT_YET", "O_FAIL", "O_BLOCKED", "A_ADVANCE", "A_STAY", "A_RETRY", "A_FAIL", "STEP_RUN_LIMIT", "WAIT_LIMIT_MINUTES", "E_RUN", "E_REHEARSE", "E_REFUSE"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
