// Generated by `t27c gen-js` from events.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const BUS_KINDS = 10;
// t27c gen-js: fn next_seq was not emitted -- this backend lowers declarations, not bodies.
export const NEVER = 4294967295;
export const LOG_EVERY_SECONDS = [0, 0, 0, 0, 60, 0, 0, 0, 4294967295, 0];
// t27c gen-js: fn log_due was not emitted -- this backend lowers declarations, not bodies.
export const PUBLIC_KEYS = ["issue", "outcome", "verdict", "repo", "slots"];
export const TOKEN_MAX = 128;
// t27c gen-js: fn token_char was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn token_ok was not emitted -- this backend lowers declarations, not bodies.
export const CR_EMPTY = 0;
export const CR_PAGE = 1;
export const CR_RESYNC = 2;
// t27c gen-js: fn cursor_read was not emitted -- this backend lowers declarations, not bodies.
export const DA_SKIP = 0;
export const DA_APPLY = 1;
export const DA_RESYNC = 2;
// t27c gen-js: fn delta_action was not emitted -- this backend lowers declarations, not bodies.
export const EVENTS_PAGE_DEFAULT = 200;
export const EVENTS_PAGE_MAX = 1000;
// t27c gen-js: fn page_size was not emitted -- this backend lowers declarations, not bodies.
export const WAIT_MAX_SECONDS = 25;
// t27c gen-js: fn wait_seconds was not emitted -- this backend lowers declarations, not bodies.
export const REFRESH_TASKS_MAX = 100;
export const RF_NOTHING = 0;
export const RF_TASKS = 1;
export const RF_SNAPSHOT = 2;
// t27c gen-js: fn refresh_action was not emitted -- this backend lowers declarations, not bodies.
export const EA_NOTHING = 0;
export const EA_REFRESH = 1;
export const EA_TOUCH = 2;
export const BOARD_ACTION = [1, 1, 0, 1, 2, 1, 1, 1, 0, 0];
// t27c gen-js: fn board_action was not emitted -- this backend lowers declarations, not bodies.
export const READ_PAUSE_MS = 2000;
export const SNAPSHOT_EVERY_SECONDS = 300;
export const FOLLOW_MS = 1000;
export const PUBLISHER_REACTS = [1, 1, 0, 1, 0, 0, 0, 0, 0, 1];
// t27c gen-js: fn wakes_here was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn runner_claims_now was not emitted -- this backend lowers declarations, not bodies.
export const KEEP_SECONDS = 259200;
export const KEEP_AT_LEAST = 5000;
// t27c gen-js: fn prune_through was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["BUS_KINDS", "NEVER", "LOG_EVERY_SECONDS", "PUBLIC_KEYS", "TOKEN_MAX", "CR_EMPTY", "CR_PAGE", "CR_RESYNC", "DA_SKIP", "DA_APPLY", "DA_RESYNC", "EVENTS_PAGE_DEFAULT", "EVENTS_PAGE_MAX", "WAIT_MAX_SECONDS", "REFRESH_TASKS_MAX", "RF_NOTHING", "RF_TASKS", "RF_SNAPSHOT", "EA_NOTHING", "EA_REFRESH", "EA_TOUCH", "BOARD_ACTION", "READ_PAUSE_MS", "SNAPSHOT_EVERY_SECONDS", "FOLLOW_MS", "PUBLISHER_REACTS", "KEEP_SECONDS", "KEEP_AT_LEAST"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
