// Generated by `t27c gen-js` from issue_shape.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const LIST_END = 36;
export const LIST_SEP = 44;
export const C_BOUNDARY = 1;
export const C_SCENARIOS = 2;
export const C_REQUIREMENTS = 4;
export const C_CRITERIA = 8;
export const C_ALL = 15;
export const SCENARIO_HEADS = "## user scenarios,## scenarios,$";
export const GIVEN_WORDS = "**given**,given ,$";
export const THEN_WORDS = "**then**,then ,$";
export const REQUIREMENT_HEADS = "## requirements,$";
export const OBLIGATION_WORDS = " must ,$";
export const CRITERIA_HEADS = "## success criteria,## acceptance criteria,## acceptance,## done when,$";
export const UNITS = "ms,s,mb,gb,%,files,file,lines,line,tests,test,attempts,attempt,$";
export const SOURCE_EXTS = "swift,ts,rs,md,json,zig,v,$";
export const TOOLS = "make ,swift ,bun ,cargo ,git ,$";
export const BOUNDARY_HEAD = "## Boundary$";
export const MSG_BOUNDARY = "missing: ## Boundary -- list every file this task may touch, one per line (`- specs/x.t27`); without it the Queen reserves nothing and no bee can take the issue$";
export const MSG_SCENARIOS = "missing: ## User Scenarios -- at least one Given/When/Then scenario$";
export const MSG_REQUIREMENTS = "missing: ## Requirements -- numbered obligations, `FR-001: ... MUST ...`$";
export const MSG_CRITERIA = "missing: ## Success Criteria -- an outcome a machine can settle: a number with a unit, a backticked file, `exit 0`, or a backticked command$";
// t27c gen-js: fn lower was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn is_digit was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn is_word was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn word_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn is_space was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn entry_len was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn entry_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn match_any_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn contains_any was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn has_fr was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn path_token was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn lead_strip was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn tail_strip was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn line_has_path was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn heading_is_boundary was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn has_boundary was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn number_with_unit_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn exit_code_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn backtick_outcome was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn has_outcome was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn judge was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn put was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn put_line was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn check_issue was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["LIST_END", "LIST_SEP", "C_BOUNDARY", "C_SCENARIOS", "C_REQUIREMENTS", "C_CRITERIA", "C_ALL", "SCENARIO_HEADS", "GIVEN_WORDS", "THEN_WORDS", "REQUIREMENT_HEADS", "OBLIGATION_WORDS", "CRITERIA_HEADS", "UNITS", "SOURCE_EXTS", "TOOLS", "BOUNDARY_HEAD", "MSG_BOUNDARY", "MSG_SCENARIOS", "MSG_REQUIREMENTS", "MSG_CRITERIA"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
