// Generated by `t27c gen-js` from holds.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const HS_WORKING = 0;
export const HS_SEND_BACK = 1;
export const HS_AWAITING = 2;
export const HS_ESCALATED = 3;
export const HS_DONE = 4;
export const HOLD_STAGES = 5;
export const AWAITING_HOLD_MINUTES = 30;
export const SEND_BACK_HOLD_MINUTES = 120;
// t27c gen-js: fn holds_files was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["HS_WORKING", "HS_SEND_BACK", "HS_AWAITING", "HS_ESCALATED", "HS_DONE", "HOLD_STAGES", "AWAITING_HOLD_MINUTES", "SEND_BACK_HOLD_MINUTES"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
