// Generated by `t27c gen-js` from telemetry.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const MT_SENT = "queen.actor.sent";
export const MT_DEAD_LETTERS = "queen.actor.dead_letters";
export const MT_DROPPED_FULL = "queen.actor.dropped_full";
export const MT_CONTROL = "queen.actor.control";
export const MT_TURNS = "queen.actor.turns";
export const MT_CRASHES = "queen.actor.crashes";
export const MT_KILLS = "queen.actor.kills";
export const MT_KILLS_STOPPED = "queen.actor.kills_stopped";
export const MT_RESTARTS = "queen.actor.restarts";
export const MT_GIVE_UPS = "queen.actor.give_ups";
export const MT_LIVE = "queen.actor.live";
export const MT_MAILBOX_DEPTH = "queen.actor.mailbox_depth";
export const MT_BUSY = "queen.actor.busy_permille";
export const MT_TURN_TIME = "queen.actor.turn_time_ms";
export const MT_MAILBOX_TIME = "queen.actor.mailbox_time_ms";
export const MT_YIELDS = "queen.actor.yields";
export const NO_KIND = "-";
export const EV_NONE = 0;
export const EV_DEPTH_HIGH = 1;
export const EV_DEPTH_OK = 2;
export const EV_TURN_LONG = 3;
export const EV_WAIT_LONG = 4;
export const EV_STORM = 5;
export const EV_STORM_OVER = 6;
export const EVENT_KINDS = 7;
export const TEL_EVENT_NAMES = ["none", "queen.actor.mailbox_depth_limit", "queen.actor.mailbox_depth_ok", "queen.actor.turn_time_limit", "queen.actor.mailbox_time_limit", "queen.actor.restart_storm", "queen.actor.restart_storm_over"];
export const DEPTH_ON_PERCENT = 75;
export const DEPTH_OFF_PERCENT = 25;
// t27c gen-js: fn percent_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn depth_on_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn depth_off_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn depth_alarm was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn depth_event was not emitted -- this backend lowers declarations, not bodies.
export const LONG_PERCENT = 50;
// t27c gen-js: fn long_at_ms was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn turn_event was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn wait_event was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn storm_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn storm_alarm was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn storm_event was not emitted -- this backend lowers declarations, not bodies.
export const HIST_BUCKETS = 24;
// t27c gen-js: fn bucket_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn bucket_floor_ms was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn rank_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn busy_permille was not emitted -- this backend lowers declarations, not bodies.
export const SAMPLE_WINDOW_MS = 1000;
export const MSG_SAMPLES_PER_WINDOW = 8;
export const DLOG_PER_FN_PER_WINDOW = 16;
// t27c gen-js: fn window_over was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn kept was not emitted -- this backend lowers declarations, not bodies.
export const END_OK = 0;
export const END_CRASH = 1;
export const END_KILL = 2;
export const MSG_RING = 256;
export const MSG_FIELDS = ["kind", "wait_ms", "turn_ms", "end", "at"];
export const EVENT_RING = 128;
export const EVENT_FIELDS = ["event", "kind", "value", "at"];
export const TOP_N = 10;
// t27c gen-js: fn ranked was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn deeper_first was not emitted -- this backend lowers declarations, not bodies.
export const DLOG_RING = 4096;
export const DLOG_FIELDS = ["card", "fn", "args", "result", "kind", "at", "n"];
export const RV_PASS = 0;
export const RV_EMPTY = 1;
export const RV_UNKNOWN_FN = 2;
export const RV_MISMATCH = 3;
export const RV_UNSAMPLED = 4;
// t27c gen-js: fn replay_verdict was not emitted -- this backend lowers declarations, not bodies.
export const SUMMARY_EVERY_SECONDS = 300;
// t27c gen-js: fn summary_due was not emitted -- this backend lowers declarations, not bodies.
export const TELEMETRY_SCHEDULES = false;
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["MT_SENT", "MT_DEAD_LETTERS", "MT_DROPPED_FULL", "MT_CONTROL", "MT_TURNS", "MT_CRASHES", "MT_KILLS", "MT_KILLS_STOPPED", "MT_RESTARTS", "MT_GIVE_UPS", "MT_LIVE", "MT_MAILBOX_DEPTH", "MT_BUSY", "MT_TURN_TIME", "MT_MAILBOX_TIME", "MT_YIELDS", "NO_KIND", "EV_NONE", "EV_DEPTH_HIGH", "EV_DEPTH_OK", "EV_TURN_LONG", "EV_WAIT_LONG", "EV_STORM", "EV_STORM_OVER", "EVENT_KINDS", "TEL_EVENT_NAMES", "DEPTH_ON_PERCENT", "DEPTH_OFF_PERCENT", "LONG_PERCENT", "HIST_BUCKETS", "SAMPLE_WINDOW_MS", "MSG_SAMPLES_PER_WINDOW", "DLOG_PER_FN_PER_WINDOW", "END_OK", "END_CRASH", "END_KILL", "MSG_RING", "MSG_FIELDS", "EVENT_RING", "EVENT_FIELDS", "TOP_N", "DLOG_RING", "DLOG_FIELDS", "RV_PASS", "RV_EMPTY", "RV_UNKNOWN_FN", "RV_MISMATCH", "RV_UNSAMPLED", "SUMMARY_EVERY_SECONDS", "TELEMETRY_SCHEDULES"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
