// Generated by `t27c gen-js` from app.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const GE_INSTALLED = 0;
export const GE_UNINSTALLED = 1;
export const GE_REPOS_ADDED = 2;
export const GE_REPOS_REMOVED = 3;
export const GE_PR_OPENED = 4;
export const GE_PR_PUSHED = 5;
export const GE_PR_READY = 6;
export const GE_PR_CLOSED = 7;
export const GE_COMMENT = 8;
export const GE_OTHER = 9;
export const APP_EVENTS = 10;
export const EVENT_PAIRS = "installation.created,installation.unsuspend,installation.deleted,installation.suspend,installation_repositories.added,installation_repositories.removed,pull_request.opened,pull_request.reopened,pull_request.synchronize,pull_request.ready_for_review,pull_request.closed,issue_comment.created,$";
export const EVENT_CODES = [0, 0, 1, 1, 2, 3, 4, 4, 5, 6, 7, 8];
export const AR_IGNORE = 0;
export const AR_REGISTER = 1;
export const AR_UNREGISTER = 2;
export const AR_REVIEW = 3;
export const AR_FORGET = 4;
export const AR_COMMAND = 5;
export const AR_QUOTA = 6;
// t27c gen-js: fn app_reaction was not emitted -- this backend lowers declarations, not bodies.
export const FREE_REVIEWS_PUBLIC = 200;
export const FREE_REVIEWS_PRIVATE = 30;
// t27c gen-js: fn free_reviews_left was not emitted -- this backend lowers declarations, not bodies.
export const MAX_REVIEW_LINES = 4000;
export const DEPTH_FULL = 0;
export const DEPTH_SUMMARY = 1;
// t27c gen-js: fn review_depth was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn review_wanted was not emitted -- this backend lowers declarations, not bodies.
export const C_NONE = 0;
export const C_REVIEW = 1;
export const C_SUMMARY = 2;
export const C_HELP = 3;
export const C_PAUSE = 4;
export const C_RESUME = 5;
export const MENTION = "@t27-bees$";
export const COMMAND_WORDS = "review,summary,help,pause,resume,$";
export const LIST_END = 36;
export const LIST_SEP = 44;
// t27c gen-js: fn mentions_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn mention_len was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn word_after was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn command_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn app_event_of was not emitted -- this backend lowers declarations, not bodies.
export const APP_RECONCILE_SECONDS = 600;
export const APP_POLL_SECONDS = 180;
export const APP_REVIEWS_PER_ROUND = 2;
export const REVIEW_MARKER = "t27-bees:review:";
export const COMMAND_HELP = ["review -- review this pull request's head again, even if it was reviewed", "summary -- write only the summary", "help -- list these commands", "pause -- stop reviewing this pull request", "resume -- review it again from the next push"];
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["GE_INSTALLED", "GE_UNINSTALLED", "GE_REPOS_ADDED", "GE_REPOS_REMOVED", "GE_PR_OPENED", "GE_PR_PUSHED", "GE_PR_READY", "GE_PR_CLOSED", "GE_COMMENT", "GE_OTHER", "APP_EVENTS", "EVENT_PAIRS", "EVENT_CODES", "AR_IGNORE", "AR_REGISTER", "AR_UNREGISTER", "AR_REVIEW", "AR_FORGET", "AR_COMMAND", "AR_QUOTA", "FREE_REVIEWS_PUBLIC", "FREE_REVIEWS_PRIVATE", "MAX_REVIEW_LINES", "DEPTH_FULL", "DEPTH_SUMMARY", "C_NONE", "C_REVIEW", "C_SUMMARY", "C_HELP", "C_PAUSE", "C_RESUME", "MENTION", "COMMAND_WORDS", "LIST_END", "LIST_SEP", "APP_RECONCILE_SECONDS", "APP_POLL_SECONDS", "APP_REVIEWS_PER_ROUND", "REVIEW_MARKER", "COMMAND_HELP"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
