// Generated by `t27c gen-js` from waits.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const W_WAITING = 0;
export const W_RESOLVED = 1;
export const W_EXPIRED = 2;
export const W_CANCELLED = 3;
export const WAIT_STATES = 4;
export const EV_RESOLVE = 0;
export const EV_EXPIRE = 1;
export const EV_CANCEL = 2;
export const EV_RECHECK = 3;
export const NEVER = 4294967295;
// t27c gen-js: fn is_terminal was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn state_after was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn transition_allowed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn valid_wait was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn wakes_owner was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn delivers_wake was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn resolution_lands was not emitted -- this backend lowers declarations, not bodies.
export const WA_NONE = 0;
export const WA_RESOLVE = 1;
export const WA_EXPIRE = 2;
export const WA_CHECK = 3;
// t27c gen-js: fn wake_action was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn due_in_seconds was not emitted -- this backend lowers declarations, not bodies.
export const WAIT_MAX_SECONDS = 86400;
export const JOB_WAIT_LIMIT_SECONDS = 86400;
// t27c gen-js: fn expiry_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn job_wait_seconds was not emitted -- this backend lowers declarations, not bodies.
export const CHECK_BASE_SECONDS = 30;
export const CHECK_CAP_SECONDS = 240;
export const CHECK_TIMEOUT_SECONDS = 20;
// t27c gen-js: fn check_after_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn recheck_in_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn check_event was not emitted -- this backend lowers declarations, not bodies.
export const CLAIM_TTL_SECONDS = 60;
export const CLAIM_BATCH = 32;
// t27c gen-js: fn epoch_after_claim was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn write_lands was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn more_now was not emitted -- this backend lowers declarations, not bodies.
export const WAIT_POLL_SECONDS = 15;
export const NOTIFY_IS_A_HINT = true;
// t27c gen-js: fn poll_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn beat_after_seconds was not emitted -- this backend lowers declarations, not bodies.
export const PH_NOW = 0;
export const PH_QUEUE = 1;
export const PH_DROP = 2;
// t27c gen-js: fn pass_on_hint was not emitted -- this backend lowers declarations, not bodies.
export const DEPLOY_WRITES_WAITS = false;
export const DEPLOY_DRAIN_SECONDS = 1800;
// t27c gen-js: fn pickup_after_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn round_visits_job was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn step_parks was not emitted -- this backend lowers declarations, not bodies.
export const JOB_O_PASS = 0;
export const JOB_O_NOT_YET = 1;
export const JOB_O_FAIL = 2;
// t27c gen-js: fn step_outcome was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["W_WAITING", "W_RESOLVED", "W_EXPIRED", "W_CANCELLED", "WAIT_STATES", "EV_RESOLVE", "EV_EXPIRE", "EV_CANCEL", "EV_RECHECK", "NEVER", "WA_NONE", "WA_RESOLVE", "WA_EXPIRE", "WA_CHECK", "WAIT_MAX_SECONDS", "JOB_WAIT_LIMIT_SECONDS", "CHECK_BASE_SECONDS", "CHECK_CAP_SECONDS", "CHECK_TIMEOUT_SECONDS", "CLAIM_TTL_SECONDS", "CLAIM_BATCH", "WAIT_POLL_SECONDS", "NOTIFY_IS_A_HINT", "PH_NOW", "PH_QUEUE", "PH_DROP", "DEPLOY_WRITES_WAITS", "DEPLOY_DRAIN_SECONDS", "JOB_O_PASS", "JOB_O_NOT_YET", "JOB_O_FAIL"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
