// Generated by `t27c gen-ts` from reviewer_sizing.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const ZAI_REQUESTS_PER_KEY = 2 satisfies number;
export const U32_MAX = 4294967295 satisfies number;
// t27c gen-ts: fn key_free_lanes was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn pool_lanes was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn pool_demand was not emitted -- this backend lowers declarations, not bodies.
export const REVIEW_MB_UNTIL_MEASURED = 512 satisfies number;
// t27c gen-ts: fn review_mb was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn pool_target was not emitted -- this backend lowers declarations, not bodies.
export const POOL_IDLE_STOP_SECONDS = 120 satisfies number;
// t27c gen-ts: fn worker_retires was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const REVIEWER_CEILING = 16 satisfies number;
export const REVIEWER_CONCURRENCY = 4 satisfies number;
export const REVIEW_ROW_SECONDS = 300 satisfies number;
export const SECONDS_PER_HOUR = 3600 satisfies number;
// t27c gen-ts: fn keeps_up was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn reviewer_concurrency was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn slots_needed was not emitted -- this backend lowers declarations, not bodies.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["ZAI_REQUESTS_PER_KEY", "U32_MAX", "REVIEW_MB_UNTIL_MEASURED", "POOL_IDLE_STOP_SECONDS", "REVIEWER_CEILING", "REVIEWER_CONCURRENCY", "REVIEW_ROW_SECONDS", "SECONDS_PER_HOUR"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
