// Generated by `t27c gen-ts` from tasks.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const TK_ISSUE = 0 satisfies number;
export const TK_REVIEW = 1 satisfies number;
export const TK_JOB = 2 satisfies number;
export const TASK_KINDS = 3 satisfies number;
export const KIND_NAMES = ["issue", "review", "job"] as const satisfies readonly [string, string, string];
export const TS_BACKLOG = 0 satisfies number;
export const TS_BLOCKED = 1 satisfies number;
export const TS_RUNNING = 2 satisfies number;
export const TS_REVIEW = 3 satisfies number;
export const TS_DONE = 4 satisfies number;
export const TS_DROPPED = 5 satisfies number;
export const TS_FAILED = 6 satisfies number;
export const TASK_STATES = 7 satisfies number;
export const STATE_NAMES = ["backlog", "blocked", "running", "review", "done", "dropped", "failed"] as const satisfies readonly [string, string, string, string, string, string, string];
// t27c gen-ts: fn job_state was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn review_state was not emitted -- this backend lowers declarations, not bodies.
export const A2A_SUBMITTED = 1 satisfies number;
export const A2A_WORKING = 2 satisfies number;
export const A2A_INPUT_REQUIRED = 3 satisfies number;
export const A2A_COMPLETED = 4 satisfies number;
export const A2A_CANCELED = 5 satisfies number;
export const A2A_FAILED = 6 satisfies number;
// t27c gen-ts: fn a2a_state was not emitted -- this backend lowers declarations, not bodies.
export const BS_QUEUED = 0 satisfies number;
export const BS_WORKING = 1 satisfies number;
export const BS_QUIET = 2 satisfies number;
export const BEE_QUIET_SECONDS = 180 satisfies number;
export const BEE_STATE_NAMES = ["queued", "working", "quiet"] as const satisfies readonly [string, string, string];
// t27c gen-ts: fn bee_state was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn task_matches was not emitted -- this backend lowers declarations, not bodies.
export const TASK_PAGE_MAX = 2000 satisfies number;
export const TASK_PAGE_DEFAULT = 500 satisfies number;
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["TK_ISSUE", "TK_REVIEW", "TK_JOB", "TASK_KINDS", "KIND_NAMES", "TS_BACKLOG", "TS_BLOCKED", "TS_RUNNING", "TS_REVIEW", "TS_DONE", "TS_DROPPED", "TS_FAILED", "TASK_STATES", "STATE_NAMES", "A2A_SUBMITTED", "A2A_WORKING", "A2A_INPUT_REQUIRED", "A2A_COMPLETED", "A2A_CANCELED", "A2A_FAILED", "BS_QUEUED", "BS_WORKING", "BS_QUIET", "BEE_QUIET_SECONDS", "BEE_STATE_NAMES", "TASK_PAGE_MAX", "TASK_PAGE_DEFAULT"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
