// Generated by `t27c gen-ts` from proof.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const SHARD_DOMAIN = "t27-hosting-shard-v1" satisfies string;
export const SHARD_COUNT_KEYS = ["tests", "fail", "invariants", "asserts", "vacuous"] as const satisfies readonly [string, string, string, string, string];
export const SHARD_SPEC_KEY = "spec" satisfies string;
export const SHARD_VERDICT_KEY = "verdict" satisfies string;
export const SHARD_TEST_KEY = "test" satisfies string;
export const VERDICT_WORDS = ["pass", "fail", "blocked", "timeout", "host_error"] as const satisfies readonly [string, string, string, string, string];
export const VW_PASS = 0 satisfies number;
export const VW_FAIL = 1 satisfies number;
export const VW_BLOCKED = 2 satisfies number;
export const VW_TIMEOUT = 3 satisfies number;
export const VW_HOST_ERROR = 4 satisfies number;
export const VERDICTS = 5 satisfies number;
// t27c gen-ts: fn report_verdict was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn run_verdict was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn verdict_votes was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn lists_tests was not emitted -- this backend lowers declarations, not bodies.
export const RECEIPT_DOMAIN = "t27-hosting-receipt-v1" satisfies string;
export const RECEIPT_SIGNED_FIELDS = ["job", "lease", "host", "incarnation", "commit", "spec", "model_hash", "zig", "input_hash", "output_hash", "ops", "verdict", "nonce", "utc_unix"] as const satisfies readonly [string, string, string, string, string, string, string, string, string, string, string, string, string, string];
export const RECEIPT_SIGNED_FIELD_COUNT = 14 satisfies number;
export const LEASE_NONCE_BYTES = 16 satisfies number;
export const REQUEST_DOMAIN = "t27-hosting-request-v1" satisfies string;
export const REQUEST_SIGNED_FIELDS = ["method", "path", "host", "incarnation", "utc_unix", "body_sha256"] as const satisfies readonly [string, string, string, string, string, string];
export const REGISTER_DOMAIN = "t27-hosting-register-v1" satisfies string;
export const REGISTER_SIGNED_FIELDS = ["public_key", "tier_claim", "slots", "platform", "utc_unix"] as const satisfies readonly [string, string, string, string, string];
export const RC_OK = 0 satisfies number;
export const RC_UNKNOWN_HOST = 1 satisfies number;
export const RC_BAD_SIGNATURE = 2 satisfies number;
export const RC_NOT_LEASED = 3 satisfies number;
export const RC_DUPLICATE = 4 satisfies number;
export const RC_EQUIVOCATION = 5 satisfies number;
export const RC_LATE = 6 satisfies number;
export const RC_INPUT_MISMATCH = 7 satisfies number;
export const RC_MODEL_MISMATCH = 8 satisfies number;
export const RC_OUTPUT_MISMATCH = 9 satisfies number;
// t27c gen-ts: fn receipt_code was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn tampered was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn attributable was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn is_vote was not emitted -- this backend lowers declarations, not bodies.
export const REPLICAS_K = 2 satisfies number;
export const REPLICAS_MAX = 3 satisfies number;
export const JV_PENDING = 0 satisfies number;
export const JV_AGREED = 1 satisfies number;
export const JV_TIEBREAK = 2 satisfies number;
export const JV_UNRESOLVED = 3 satisfies number;
export const FAULTS_ASSUMED = 0 satisfies number;
// t27c gen-ts: fn quorum_needed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn job_verdict was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn wanted_after was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn job_closed was not emitted -- this backend lowers declarations, not bodies.
export const SIDE_AGREED = 0 satisfies number;
export const SIDE_DISSENT = 1 satisfies number;
export const SIDE_NONE = 2 satisfies number;
export const TOP_GROUP = 0 satisfies number;
// t27c gen-ts: fn side_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const KEY_ID_HEX_LEN = 16 satisfies number;
export const NONCE_MIN_BYTES = 16 satisfies number;
export const FAIL = 1 satisfies number;

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["SHARD_DOMAIN", "SHARD_COUNT_KEYS", "SHARD_SPEC_KEY", "SHARD_VERDICT_KEY", "SHARD_TEST_KEY", "VERDICT_WORDS", "VW_PASS", "VW_FAIL", "VW_BLOCKED", "VW_TIMEOUT", "VW_HOST_ERROR", "VERDICTS", "RECEIPT_DOMAIN", "RECEIPT_SIGNED_FIELDS", "RECEIPT_SIGNED_FIELD_COUNT", "LEASE_NONCE_BYTES", "REQUEST_DOMAIN", "REQUEST_SIGNED_FIELDS", "REGISTER_DOMAIN", "REGISTER_SIGNED_FIELDS", "RC_OK", "RC_UNKNOWN_HOST", "RC_BAD_SIGNATURE", "RC_NOT_LEASED", "RC_DUPLICATE", "RC_EQUIVOCATION", "RC_LATE", "RC_INPUT_MISMATCH", "RC_MODEL_MISMATCH", "RC_OUTPUT_MISMATCH", "REPLICAS_K", "REPLICAS_MAX", "JV_PENDING", "JV_AGREED", "JV_TIEBREAK", "JV_UNRESOLVED", "FAULTS_ASSUMED", "SIDE_AGREED", "SIDE_DISSENT", "SIDE_NONE", "TOP_GROUP", "KEY_ID_HEX_LEN", "NONCE_MIN_BYTES", "FAIL"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
