// Generated by `t27c gen-ts` from dispatch_exit.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const DX_NORMAL = 0 satisfies number;
export const DX_SHUTDOWN = 1 satisfies number;
export const DX_KILLED = 3 satisfies number;
export const DX_NOCONNECTION = 6 satisfies number;
export const DX_TIMEOUT = 7 satisfies number;
export const DX_PROVIDER_ERROR = 8 satisfies number;
export const DX_UNKNOWN = 9 satisfies number;
export const ACTORS_X_CRASH = 4 satisfies number;
export const EF_NONE = 0 satisfies number;
export const EF_CANCEL = 1 satisfies number;
export const EF_KILL = 2 satisfies number;
export const EF_PROVIDER = 3 satisfies number;
export const HC_NONE = 0 satisfies number;
export const HC_2XX = 2 satisfies number;
export const HC_4XX = 4 satisfies number;
export const HC_5XX = 5 satisfies number;
export const HC_429 = 9 satisfies number;
// t27c gen-ts: fn http_class was not emitted -- this backend lowers declarations, not bodies.
export const HB_NEVER = 4294967295 satisfies number;
export const LEASE_TTL_SECONDS = 180 satisfies number;
// t27c gen-ts: fn provider_failed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn runtime_alive was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn past_timeout was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn exit_reason was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn actors_reason was not emitted -- this backend lowers declarations, not bodies.
export const RD_NONE = 0 satisfies number;
export const RD_NOW = 1 satisfies number;
export const RD_LATER = 2 satisfies number;
export const RD_GIVE_UP = 3 satisfies number;
export const RUN_LIMIT = 3 satisfies number;
export const STREAK_LIMIT = 6 satisfies number;
export const BACKOFF_BASE = 10 satisfies number;
export const BACKOFF_CAP = 300 satisfies number;
// t27c gen-ts: fn counts_against_issue was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn restart_decision was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn restart_wait_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["DX_NORMAL", "DX_SHUTDOWN", "DX_KILLED", "DX_NOCONNECTION", "DX_TIMEOUT", "DX_PROVIDER_ERROR", "DX_UNKNOWN", "ACTORS_X_CRASH", "EF_NONE", "EF_CANCEL", "EF_KILL", "EF_PROVIDER", "HC_NONE", "HC_2XX", "HC_4XX", "HC_5XX", "HC_429", "HB_NEVER", "LEASE_TTL_SECONDS", "RD_NONE", "RD_NOW", "RD_LATER", "RD_GIVE_UP", "RUN_LIMIT", "STREAK_LIMIT", "BACKOFF_BASE", "BACKOFF_CAP"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
