// Generated by `t27c gen-js` from domains.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const DOMAIN_T27C = 0;
export const DOMAIN_T27B = 1;
export const DOMAIN_SPECS = 2;
export const DOMAIN_QUEEN_OPS = 3;
export const PREFIXES_T27C = "gen/c/,specs/isa/,specs/asm/,bootstrap/src/codegen_c,$";
export const PREFIXES_T27B = "cli/t27b/,specs/tri/t27b/,bootstrap/,$";
export const PREFIXES_QUEEN_OPS = "specs/queen/,tools/queen/,tools/bees/,trios/,docs/coordination/,$";
export const LIST_END = 36;
export const LIST_SEP = 44;
// t27c gen-js: fn starts_with_one_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn domain_of_path was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["DOMAIN_T27C", "DOMAIN_T27B", "DOMAIN_SPECS", "DOMAIN_QUEEN_OPS", "PREFIXES_T27C", "PREFIXES_T27B", "PREFIXES_QUEEN_OPS", "LIST_END", "LIST_SEP"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
