// Generated by `t27c gen-ts` from toolchain.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const PLATFORMS = ["darwin-arm64", "linux-x64", "linux-arm64"] as const satisfies readonly [string, string, string];
export const PLATFORM_COUNT = 3 satisfies number;
export const ARCH_ARM64 = 0 satisfies number;
export const ARCH_X64 = 1 satisfies number;
export const ARCHS = 2 satisfies number;
export const PLATFORM_ARCH = [0, 1, 0] as const satisfies readonly [number, number, number];
export const ZIG_VERSION = "0.16.0" satisfies string;
export const ZIG_URLS = ["https://ziglang.org/download/0.16.0/zig-aarch64-macos-0.16.0.tar.xz", "https://ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz", "https://ziglang.org/download/0.16.0/zig-aarch64-linux-0.16.0.tar.xz"] as const satisfies readonly [string, string, string];
export const ZIG_SHA256 = ["b23d70deaa879b5c2d486ed3316f7eaa53e84acf6fc9cc747de152450d401489", "70e49664a74374b48b51e6f3fdfbf437f6395d42509050588bd49abe52ba3d00", "ea4b09bfb22ec6f6c6ceac57ab63efb6b46e17ab08d21f69f3a48b38e1534f17"] as const satisfies readonly [string, string, string];
export const ZIG_BYTES = [52238004, 55478392, 51211944] as const satisfies readonly [number, number, number];
export const ZIG_DIRS = ["zig-aarch64-macos-0.16.0", "zig-x86_64-linux-0.16.0", "zig-aarch64-linux-0.16.0"] as const satisfies readonly [string, string, string];
export const RELEASE_REPO = "gHashTag/trios" satisfies string;
export const RELEASE_TAG = "trios-host-v0.1.0" satisfies string;
export const RELEASE_BASE = "https://github.com/gHashTag/trios/releases/download/trios-host-v0.1.0/" satisfies string;
export const T27_COMMIT = "cf42584c9beaf48f9b615331c2837bfdaafb02a4" satisfies string;
export const T27C_URLS = ["https://github.com/gHashTag/trios/releases/download/trios-host-v0.1.0/t27c-darwin-arm64", "https://github.com/gHashTag/trios/releases/download/trios-host-v0.1.0/t27c-linux-x64", "https://github.com/gHashTag/trios/releases/download/trios-host-v0.1.0/t27c-linux-arm64"] as const satisfies readonly [string, string, string];
export const T27C_SHA256 = ["f01f60e56af8c13bb4e51eaf5d073687e225b6dcb59c2a4ccaa27c599e6f89b9", "50345009b98c123229c9175125b4cf56ea852732d85761ef465655949f2e131a", "dd55e8902190ce32664c6bdbaf36ba2125bc64f88a3ed9c15d278224c5f4abe7"] as const satisfies readonly [string, string, string];
export const T27C_BYTES = [9773360, 11892096, 11004200] as const satisfies readonly [number, number, number];
export const T27B_URLS = ["https://github.com/gHashTag/trios/releases/download/trios-host-v0.1.0/t27b-darwin-arm64", "", "https://github.com/gHashTag/trios/releases/download/trios-host-v0.1.0/t27b-linux-arm64"] as const satisfies readonly [string, string, string];
export const T27B_SHA256 = ["38d66e75856d8d87787d3e6e012ba334c5b54c101f0ee9fd67556ee3e2b02e46", "", "8da449a6b51f24008fde1f32078392f2c7a8b412eba110483934ac0b337550c8"] as const satisfies readonly [string, string, string];
export const T27B_BYTES = [2472000, 0, 2794840] as const satisfies readonly [number, number, number];
export const TRIOS_HOST_URLS = ["https://github.com/gHashTag/trios/releases/download/trios-host-v0.1.0/trios-host-darwin-arm64", "https://github.com/gHashTag/trios/releases/download/trios-host-v0.1.0/trios-host-linux-x64", "https://github.com/gHashTag/trios/releases/download/trios-host-v0.1.0/trios-host-linux-arm64"] as const satisfies readonly [string, string, string];
export const TRIOS_HOST_SHA256 = ["b1f072f4589eef53a3235c7be5fa6a4b3aa26832794d7762809acb2c83224164", "d415acec061626600a8fbf88fd9de4a3b0088e47f2220c27b1dd6635d2b8b8fc", "9f4300cfd8e7fe37ea50ccc33d04e26788336278885530e25f9a71c2a2c067a1"] as const satisfies readonly [string, string, string];
export const TRIOS_HOST_BYTES = [61118752, 99347796, 98788850] as const satisfies readonly [number, number, number];
export const SPEC_SOURCE_BASE = "https://raw.githubusercontent.com/gHashTag/t27/" satisfies string;
export const AGENT_DIR = ".trios-host" satisfies string;
export const KEY_FILE = "key" satisfies string;
export const TOOLS_DIR = "tools" satisfies string;
export const WORK_DIR = "work" satisfies string;
export const CACHE_DIR = "cache" satisfies string;
export const AGENT_DIR_MODE = 448 satisfies number;
export const KEY_FILE_MODE = 384 satisfies number;
export const GROUP_OTHER_BITS = 63 satisfies number;
export const SANDBOX_EXEC_PROFILE = ["(version 1)", "(deny default)", "(import \"system.sb\")", "(allow process-fork)", "(allow signal (target same-sandbox))", "(allow sysctl-read)", "(allow file-read-metadata)", "(allow process-exec file-read* (literal (param \"T27C\")) (literal (param \"T27B\")) (subpath (param \"ZIG\")) (subpath (param \"JOB\")) (subpath (param \"CACHE\")))", "(allow file-write* (subpath (param \"JOB\")) (subpath (param \"CACHE\")))", "(deny network*)"] as const satisfies readonly [string, string, string, string, string, string, string, string, string, string];
export const SANDBOX_EXEC_PARAMS = ["T27C", "T27B", "ZIG", "JOB", "CACHE"] as const satisfies readonly [string, string, string, string, string];
export const BWRAP_ARGS = ["--unshare-all", "--die-with-parent", "--new-session", "--ro-bind", "/usr", "/usr", "--ro-bind-try", "/lib", "/lib", "--ro-bind-try", "/lib64", "/lib64", "--ro-bind-try", "/etc/ld.so.cache", "/etc/ld.so.cache", "--proc", "/proc", "--dev", "/dev", "--tmpfs", "/tmp", "--ro-bind", "{ZIG}", "{ZIG}", "--chdir", "{JOB}"] as const satisfies readonly [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string];
export const BWRAP_BINDS = ["--ro-bind", "{T27C}", "{T27C}", "--ro-bind", "{T27B}", "{T27B}", "--bind", "{JOB}", "{JOB}", "--bind", "{CACHE}", "{CACHE}"] as const satisfies readonly [string, string, string, string, string, string, string, string, string, string, string, string];
export const UNSHARE_ARGS = ["--user", "--map-root-user", "--net"] as const satisfies readonly [string, string, string];
export const SHA256_HEX_LEN = 64 satisfies number;
// t27c gen-ts: fn pin_well_formed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn pin_complete was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn url_allowed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn ends_with was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn starts_with was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn names_asset was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["PLATFORMS", "PLATFORM_COUNT", "ARCH_ARM64", "ARCH_X64", "ARCHS", "PLATFORM_ARCH", "ZIG_VERSION", "ZIG_URLS", "ZIG_SHA256", "ZIG_BYTES", "ZIG_DIRS", "RELEASE_REPO", "RELEASE_TAG", "RELEASE_BASE", "T27_COMMIT", "T27C_URLS", "T27C_SHA256", "T27C_BYTES", "T27B_URLS", "T27B_SHA256", "T27B_BYTES", "TRIOS_HOST_URLS", "TRIOS_HOST_SHA256", "TRIOS_HOST_BYTES", "SPEC_SOURCE_BASE", "AGENT_DIR", "KEY_FILE", "TOOLS_DIR", "WORK_DIR", "CACHE_DIR", "AGENT_DIR_MODE", "KEY_FILE_MODE", "GROUP_OTHER_BITS", "SANDBOX_EXEC_PROFILE", "SANDBOX_EXEC_PARAMS", "BWRAP_ARGS", "BWRAP_BINDS", "UNSHARE_ARGS", "SHA256_HEX_LEN"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
