// Generated by `t27c gen-ts` from toolchain.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const PLATFORMS = ["darwin-arm64", "linux-x64"] as const satisfies readonly [string, string];
export const PLATFORM_COUNT = 2 satisfies number;
export const ZIG_VERSION = "0.16.0" satisfies string;
export const ZIG_URLS = ["https://ziglang.org/download/0.16.0/zig-aarch64-macos-0.16.0.tar.xz", "https://ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz"] as const satisfies readonly [string, string];
export const ZIG_SHA256 = ["b23d70deaa879b5c2d486ed3316f7eaa53e84acf6fc9cc747de152450d401489", "70e49664a74374b48b51e6f3fdfbf437f6395d42509050588bd49abe52ba3d00"] as const satisfies readonly [string, string];
export const ZIG_BYTES = [52238004, 55478392] as const satisfies readonly [number, number];
export const ZIG_DIRS = ["zig-aarch64-macos-0.16.0", "zig-x86_64-linux-0.16.0"] as const satisfies readonly [string, string];
export const T27C_URLS = ["", ""] as const satisfies readonly [string, string];
export const T27C_SHA256 = ["", ""] as const satisfies readonly [string, string];
export const T27C_BYTES = [0, 0] as const satisfies readonly [number, number];
export const SPEC_SOURCE_BASE = "https://raw.githubusercontent.com/gHashTag/t27/" satisfies string;
export const AGENT_DIR = ".trios-host" satisfies string;
export const KEY_FILE = "key" satisfies string;
export const AGENT_DIR_MODE = 448 satisfies number;
export const KEY_FILE_MODE = 384 satisfies number;
export const GROUP_OTHER_BITS = 63 satisfies number;
export const SHA256_HEX_LEN = 64 satisfies number;
// t27c gen-ts: fn pin_well_formed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn pin_complete was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn url_allowed was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["PLATFORMS", "PLATFORM_COUNT", "ZIG_VERSION", "ZIG_URLS", "ZIG_SHA256", "ZIG_BYTES", "ZIG_DIRS", "T27C_URLS", "T27C_SHA256", "T27C_BYTES", "SPEC_SOURCE_BASE", "AGENT_DIR", "KEY_FILE", "AGENT_DIR_MODE", "KEY_FILE_MODE", "GROUP_OTHER_BITS", "SHA256_HEX_LEN"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
