// Generated by `t27c gen-js` from keyed.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const KA_DELIVER = 0;
export const KA_SPAWN = 1;
export const KA_HOLD = 2;
export const KA_EVICT = 3;
export const KA_REFUSE = 4;
export const LANES_MEASURED = 70;
export const KEYED_ACTIVE_CAP = 512;
// t27c gen-js: fn key_action was not emitted -- this backend lowers declarations, not bodies.
export const PASSIVATE_IDLE_SECONDS = 120;
export const PASSIVATE_REASON = 0;
// t27c gen-js: fn evictable was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn passivate_due was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn evict_before was not emitted -- this backend lowers declarations, not bodies.
export const KEY_NO_PID = 0;
// t27c gen-js: fn entry_after_exit was not emitted -- this backend lowers declarations, not bodies.
export const KEY_HOLD_CAP = 256;
// t27c gen-js: fn hold_admits was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn restart_after_exit was not emitted -- this backend lowers declarations, not bodies.
export const CL_START = 0;
export const CL_NO_LANE = 1;
export const CL_STAND_DOWN = 2;
// t27c gen-js: fn lane_free was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn claim_step was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn keeps_lane was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn claim_is_mine was not emitted -- this backend lowers declarations, not bodies.
export const KEY_RD_NOW = 1;
// t27c gen-js: fn keeps_lane_after_end was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn retry_after_lost_seconds was not emitted -- this backend lowers declarations, not bodies.
export const BK_IDLE = 0;
export const BK_ADMITTING = 1;
export const BK_RUNNING = 2;
export const BK_RETRY = 3;
export const BK_DONE = 4;
export const BK_GAVE_UP = 5;
export const BE_READY = 0;
export const BE_STARTED = 1;
export const BE_REFUSED = 2;
export const BE_ENDED = 3;
export const BE_RESTART_NOW = 4;
export const BE_RESTART_LATER = 5;
export const BE_GIVE_UP = 6;
export const BE_RETRY_DUE = 7;
export const BE_SENT_BACK = 8;
// t27c gen-js: fn bee_key_next was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn bee_key_acts was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn key_holds_work was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn starts_in was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["KA_DELIVER", "KA_SPAWN", "KA_HOLD", "KA_EVICT", "KA_REFUSE", "LANES_MEASURED", "KEYED_ACTIVE_CAP", "PASSIVATE_IDLE_SECONDS", "PASSIVATE_REASON", "KEY_NO_PID", "KEY_HOLD_CAP", "CL_START", "CL_NO_LANE", "CL_STAND_DOWN", "KEY_RD_NOW", "BK_IDLE", "BK_ADMITTING", "BK_RUNNING", "BK_RETRY", "BK_DONE", "BK_GAVE_UP", "BE_READY", "BE_STARTED", "BE_REFUSED", "BE_ENDED", "BE_RESTART_NOW", "BE_RESTART_LATER", "BE_GIVE_UP", "BE_RETRY_DUE", "BE_SENT_BACK"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
