// Generated by `t27c gen-ts` from review_lanes.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const LANE_GO = 0 satisfies number;
export const LANE_WAIT_ROW = 1 satisfies number;
export const LANE_STOPPED = 2 satisfies number;
export const LANE_ASKED = 0 satisfies number;
export const LANE_RELEASED = 1 satisfies number;
export const LANE_BEAT = 2 satisfies number;
export const LANE_LEFT = 3 satisfies number;
// t27c gen-ts: fn queue_admits was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn grant_before was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn head_tries was not emitted -- this backend lowers declarations, not bodies.
export const MODEL_CALL_SECONDS = 120 satisfies number;
// t27c gen-ts: fn wait_left_seconds was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn lane_answer was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn gives_row_back was not emitted -- this backend lowers declarations, not bodies.
export const HOLD_PERCENT_UNTIL_MEASURED = 100 satisfies number;
export const HOLD_MEASURED_AFTER_SECONDS = 900 satisfies number;
export const HOLD_PERCENT_FLOOR = 25 satisfies number;
export const HOLD_WINDOW_SECONDS = 3600 satisfies number;
export const SAMPLE_MAX = 21474836 satisfies number;
// t27c gen-ts: fn hold_percent was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn samples_halve was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn queue_lanes was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn pool_target_queued was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const REVIEWER_CEILING = 16 satisfies number;
export const REVIEW_ROW_SECONDS = 300 satisfies number;
export const WAIT_REVISIT_BASE_SECONDS = 30 satisfies number;
export const WAIT_REVISIT_CAP_SECONDS = 900 satisfies number;
// t27c gen-ts: fn due_again was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn reviewer_concurrency was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn revisit_after_seconds was not emitted -- this backend lowers declarations, not bodies.
export const REVIEW_MB_UNTIL_MEASURED = 512 satisfies number;
export const U32_MAX = 4294967295 satisfies number;
// t27c gen-ts: fn pool_demand was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn pool_target was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn review_mb was not emitted -- this backend lowers declarations, not bodies.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["LANE_GO", "LANE_WAIT_ROW", "LANE_STOPPED", "LANE_ASKED", "LANE_RELEASED", "LANE_BEAT", "LANE_LEFT", "MODEL_CALL_SECONDS", "HOLD_PERCENT_UNTIL_MEASURED", "HOLD_MEASURED_AFTER_SECONDS", "HOLD_PERCENT_FLOOR", "HOLD_WINDOW_SECONDS", "SAMPLE_MAX", "REVIEWER_CEILING", "REVIEW_ROW_SECONDS", "WAIT_REVISIT_BASE_SECONDS", "WAIT_REVISIT_CAP_SECONDS", "REVIEW_MB_UNTIL_MEASURED", "U32_MAX"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
