// Generated by `t27c gen-ts` from statement.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

// t27c gen-ts: fn shard_kind was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn work_kind was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn leaf_kind_known was not emitted -- this backend lowers declarations, not bodies.
export const KIND_WORDS = ["", "bounty", "executor_fee", "provider_fee", "verifier_fee", "author_royalty", "", "", "", "slash"] as const satisfies readonly [string, string, string, string, string, string, string, string, string, string];
// t27c gen-ts: fn balance_after_entry was not emitted -- this backend lowers declarations, not bodies.
export const EPOCH_SECONDS = 86400 satisfies number;
export const EPOCH_ORIGIN_UNIX = 1791590400 satisfies number;
export const CLOSES_PER_CALL_MAX = 64 satisfies number;
// t27c gen-ts: fn epoch_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn epoch_from was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn epoch_to was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn next_to_close was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn epoch_closes was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn row_epoch_open was not emitted -- this backend lowers declarations, not bodies.
export const LEAF_DOMAIN = "t27-hosting-epoch-leaf-v1" satisfies string;
export const LEAF_FIELDS = ["epoch", "host", "kind", "mtri", "receipts"] as const satisfies readonly [string, string, string, string, string];
export const LEAF_FIELD_COUNT = 5 satisfies number;
export const STATEMENT_DOMAIN = "t27-hosting-epoch-v1" satisfies string;
export const STATEMENT_FIELDS = ["epoch", "from_unix", "to_unix", "leaves", "root", "prev", "credit_mtri", "slash_mtri", "chain", "settlement", "transferable"] as const satisfies readonly [string, string, string, string, string, string, string, string, string, string, string];
export const STATEMENT_FIELD_COUNT = 11 satisfies number;
export const GENESIS_PREV = "0000000000000000000000000000000000000000000000000000000000000000" satisfies string;
export const CHAIN_WORD = "ton" satisfies string;
export const SETTLEMENT_SHUT_WORD = "shut" satisfies string;
// t27c gen-ts: fn leaf_before was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn audit_path_len was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn sibling_left was not emitted -- this backend lowers declarations, not bodies.
export const VF_OK = 0 satisfies number;
export const VF_BAD_SIGNATURE = 1 satisfies number;
export const VF_NOT_MY_LEAF = 2 satisfies number;
export const VF_BAD_SHAPE = 3 satisfies number;
export const VF_ROOT_MISMATCH = 4 satisfies number;
// t27c gen-ts: fn proof_shape_ok was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn verify_code was not emitted -- this backend lowers declarations, not bodies.
export const VALUE_GATE_OPEN = false satisfies boolean;
// t27c gen-ts: fn settlement_gate_open was not emitted -- this backend lowers declarations, not bodies.
export const LEDGER_KEY_VARIABLE = "TRIOS_HOSTING_LEDGER_KEY" satisfies string;
export const LEDGER_KEY_HEX_LEN = 64 satisfies number;
export const LK_OK = 0 satisfies number;
export const LK_MISSING = 1 satisfies number;
export const LK_MALFORMED = 2 satisfies number;
// t27c gen-ts: fn ledger_key_state was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn epochs_close was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.
export const SETTLEMENT_ENABLED = false satisfies boolean;
export const TOKEN_VALUE_CLAIMED = false satisfies boolean;
// t27c gen-ts: fn credit_mtri was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn vote_attestation was not emitted -- this backend lowers declarations, not bodies.
export const WC_SERVICE = 1 satisfies number;
export const WC_SHARD = 0 satisfies number;
export const SIDE_AGREED = 0 satisfies number;
export const ENTRY_SLASH = 9 satisfies number;
export const LANE_BITS = 16 satisfies number;
export const LANE_MASK = 65535 satisfies number;
export const ROLE_EXECUTOR = 0 satisfies number;
export const ROLE_VERIFIER = 1 satisfies number;
export const SIGNER_EXECUTOR = 0 satisfies number;
// t27c gen-ts: fn fee_kind_of was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn has was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn lane was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn role_of was not emitted -- this backend lowers declarations, not bodies.
export const CTL_BIT = 1 satisfies number;
// t27c gen-ts: fn bit was not emitted -- this backend lowers declarations, not bodies.
export const REWARD_PER_JOB_MTRI = 1 satisfies number;
export const CHAIN_OF_RECORD = 1 satisfies number;
export const CHAIN_TON = 1 satisfies number;
export const LEAF_PREFIX = 0 satisfies number;
export const NODE_PREFIX = 1 satisfies number;
// t27c gen-ts: fn split_point was not emitted -- this backend lowers declarations, not bodies.
export const EVIDENCE_OTHER_RUN = 5 satisfies number;
export const EVIDENCE_UNBOUND = 4 satisfies number;
export const LINKED = 0 satisfies number;
export const NO_CHANGE = 1 satisfies number;
export const NO_LOGS = 8 satisfies number;
export const NO_OUTPUTS = 6 satisfies number;
export const NO_TESTS = 7 satisfies number;
export const RUN_OTHER_CHANGE = 3 satisfies number;
export const RUN_UNBOUND = 2 satisfies number;
export const SEAL_MATCH = 1 satisfies number;
export const SEAL_NOT_VERIFIED = 9 satisfies number;
// t27c gen-ts: fn chain was not emitted -- this backend lowers declarations, not bodies.
export const ATT_DEVICE_BOUND = 3 satisfies number;
export const ATT_NONE = 0 satisfies number;
export const ATT_REPRODUCED = 2 satisfies number;
export const ATT_SOFTWARE_SIGNED = 1 satisfies number;
export const AUTHOR_ROYALTY = 5 satisfies number;
export const BOUNTY = 1 satisfies number;
export const CREDIT_TRANSFERABLE = false satisfies boolean;
export const EXECUTOR_FEE = 2 satisfies number;
export const OUT_CREDITED = 0 satisfies number;
export const OUT_REJECTED_AND_SLASHED = 1 satisfies number;
export const PAYMENT_KINDS = 5 satisfies number;
export const PAY_NONE = 0 satisfies number;
export const PAY_NORMAL = 1 satisfies number;
export const PAY_SLASH_ONLY = 2 satisfies number;
export const PROVIDER_FEE = 3 satisfies number;
export const VERIFIER_FEE = 4 satisfies number;
// t27c gen-ts: fn attestation_level was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn payment_kind_known was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn payout was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn testnet_credit_allowed was not emitted -- this backend lowers declarations, not bodies.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["KIND_WORDS", "EPOCH_SECONDS", "EPOCH_ORIGIN_UNIX", "CLOSES_PER_CALL_MAX", "LEAF_DOMAIN", "LEAF_FIELDS", "LEAF_FIELD_COUNT", "STATEMENT_DOMAIN", "STATEMENT_FIELDS", "STATEMENT_FIELD_COUNT", "GENESIS_PREV", "CHAIN_WORD", "SETTLEMENT_SHUT_WORD", "VF_OK", "VF_BAD_SIGNATURE", "VF_NOT_MY_LEAF", "VF_BAD_SHAPE", "VF_ROOT_MISMATCH", "VALUE_GATE_OPEN", "LEDGER_KEY_VARIABLE", "LEDGER_KEY_HEX_LEN", "LK_OK", "LK_MISSING", "LK_MALFORMED", "SETTLEMENT_ENABLED", "TOKEN_VALUE_CLAIMED", "WC_SERVICE", "WC_SHARD", "SIDE_AGREED", "ENTRY_SLASH", "LANE_BITS", "LANE_MASK", "ROLE_EXECUTOR", "ROLE_VERIFIER", "SIGNER_EXECUTOR", "CTL_BIT", "REWARD_PER_JOB_MTRI", "CHAIN_OF_RECORD", "CHAIN_TON", "LEAF_PREFIX", "NODE_PREFIX", "EVIDENCE_OTHER_RUN", "EVIDENCE_UNBOUND", "LINKED", "NO_CHANGE", "NO_LOGS", "NO_OUTPUTS", "NO_TESTS", "RUN_OTHER_CHANGE", "RUN_UNBOUND", "SEAL_MATCH", "SEAL_NOT_VERIFIED", "ATT_DEVICE_BOUND", "ATT_NONE", "ATT_REPRODUCED", "ATT_SOFTWARE_SIGNED", "AUTHOR_ROYALTY", "BOUNTY", "CREDIT_TRANSFERABLE", "EXECUTOR_FEE", "OUT_CREDITED", "OUT_REJECTED_AND_SLASHED", "PAYMENT_KINDS", "PAY_NONE", "PAY_NORMAL", "PAY_SLASH_ONLY", "PROVIDER_FEE", "VERIFIER_FEE"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
