// Generated by `t27c gen-ts` from issue_shape.t27. Do not edit.
//
// Every name, value and type here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const LIST_END = 36 satisfies number;
export const LIST_SEP = 44 satisfies number;
export const C_BOUNDARY = 1 satisfies number;
export const C_SCENARIOS = 2 satisfies number;
export const C_REQUIREMENTS = 4 satisfies number;
export const C_CRITERIA = 8 satisfies number;
export const C_ALL = 15 satisfies number;
export const SCENARIO_HEADS = "## user scenarios,## scenarios,$" satisfies string;
export const GIVEN_WORDS = "**given**,given ,$" satisfies string;
export const THEN_WORDS = "**then**,then ,$" satisfies string;
export const REQUIREMENT_HEADS = "## requirements,$" satisfies string;
export const OBLIGATION_WORDS = " must ,$" satisfies string;
export const CRITERIA_HEADS = "## success criteria,## acceptance criteria,## acceptance,## done when,$" satisfies string;
export const UNITS = "ms,s,mb,gb,%,files,file,lines,line,tests,test,attempts,attempt,$" satisfies string;
export const SOURCE_EXTS = "swift,ts,rs,md,json,zig,v,$" satisfies string;
export const TOOLS = "make ,swift ,bun ,cargo ,git ,$" satisfies string;
export const BOUNDARY_HEAD = "## Boundary$" satisfies string;
export const MSG_BOUNDARY = "missing: ## Boundary -- list every file this task may touch, one per line (`- specs/x.t27`); without it the Queen reserves nothing and no bee can take the issue$" satisfies string;
export const MSG_SCENARIOS = "missing: ## User Scenarios -- at least one Given/When/Then scenario$" satisfies string;
export const MSG_REQUIREMENTS = "missing: ## Requirements -- numbered obligations, `FR-001: ... MUST ...`$" satisfies string;
export const MSG_CRITERIA = "missing: ## Success Criteria -- an outcome a machine can settle: a number with a unit, a backticked file, `exit 0`, or a backticked command$" satisfies string;
// t27c gen-ts: fn lower was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn is_digit was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn is_word was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn word_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn is_space was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn entry_len was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn entry_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn match_any_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn contains_any was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn has_fr was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn path_token was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn lead_strip was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn tail_strip was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn line_has_path was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn heading_is_boundary was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn has_boundary was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn number_with_unit_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn exit_code_at was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn backtick_outcome was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn has_outcome was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn judge was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn put was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn put_line was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: fn check_issue was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-ts: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [] as const;
export const __DECL_ORDER__ = ["LIST_END", "LIST_SEP", "C_BOUNDARY", "C_SCENARIOS", "C_REQUIREMENTS", "C_CRITERIA", "C_ALL", "SCENARIO_HEADS", "GIVEN_WORDS", "THEN_WORDS", "REQUIREMENT_HEADS", "OBLIGATION_WORDS", "CRITERIA_HEADS", "UNITS", "SOURCE_EXTS", "TOOLS", "BOUNDARY_HEAD", "MSG_BOUNDARY", "MSG_SCENARIOS", "MSG_REQUIREMENTS", "MSG_CRITERIA"] as const;

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([] as const);
