/**
 * @license
 * Copyright 2025 BrowserOS
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * The Queen's dashboard, served by the deployment she runs in.
 *
 * There was a dashboard already - `.trinity/dashboard/index.html`, generated by
 * `tools/dashboard.py` from files on the operator's Mac. It cannot show any of
 * this: the lease, the tick's last decision, which bees are in flight in the
 * container. The Queen moved and her only window stayed behind.
 *
 * WHY THE SHELL IS NOT GUARDED AND THE DATA IS.
 *
 * A page you can only fetch with `curl -H Authorization` is not a page anybody
 * opens. The obvious fix - put the token in the URL - is the one thing that must
 * not happen: query strings end up in logs, in proxies, in browser history and
 * in shared links.
 *
 * So this route serves an empty shell: markup, styling, and the script that
 * knows how to ask. It contains no state, no token, and nothing worth reading.
 * Every byte of actual state still comes from `/queen/lease`, which is guarded
 * exactly as it was. The operator pastes the token into the page once, the
 * browser keeps it in sessionStorage, and it travels in an Authorization
 * header like every other caller's.
 *
 * The styling is t27.ai's own: black, #00FF88, #FFD700, and a type and spacing
 * scale built on phi - which is the project's L5 identity law rather than a
 * decoration, so the dashboard and the constitution agree for once.
 */

import { Hono } from 'hono'

const PAGE = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Queen — trios swarm</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
  :root{
    --phi:1.618;
    --bg:#000000; --panel:#0a0a0f; --border:rgba(255,255,255,.08);
    --accent:#00FF88; --accent-dark:#00CC66; --golden:#FFD700;
    --text:#ffffff; --muted:#888888;
    --font:"Outfit",system-ui,-apple-system,sans-serif;
    --mono:ui-monospace,SFMono-Regular,"SF Mono",Menlo,monospace;
    --f-3:.75rem; --f-2:.8125rem; --f-1:.875rem; --f0:1rem;
    --f1:1.272rem; --f2:1.618rem; --f3:2.058rem; --f4:2.618rem;
    --sp-1:.382rem; --sp0:.618rem; --sp1:1rem; --sp2:1.618rem; --sp3:2.618rem;
    --max-w:1200px;
  }
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--text);font-family:var(--font);
       font-weight:300;line-height:var(--phi);-webkit-font-smoothing:antialiased}
  .wrap{max-width:var(--max-w);margin:0 auto;padding:var(--sp3) var(--sp2)}
  header{display:flex;align-items:baseline;gap:var(--sp1);flex-wrap:wrap;
         margin-bottom:var(--sp3)}
  h1{font-size:var(--f3);font-weight:500;margin:0;letter-spacing:-.02em}
  h1 span{color:var(--accent)}
  .sub{color:var(--muted);font-size:var(--f-1)}
  .grid{display:grid;gap:var(--sp1);
        grid-template-columns:repeat(auto-fit,minmax(232px,1fr));margin-bottom:var(--sp2)}
  .card{background:var(--panel);border:1px solid var(--border);
        border-radius:calc(var(--sp0) * var(--phi));padding:var(--sp2)}
  .k{font-size:var(--f-3);letter-spacing:.14em;text-transform:uppercase;color:var(--muted)}
  .v{font-size:var(--f2);font-weight:500;margin-top:var(--sp-1);word-break:break-word}
  .v.small{font-size:var(--f0);font-family:var(--mono);font-weight:400}
  .ok{color:var(--accent)} .warn{color:var(--golden)} .off{color:var(--muted)}
  h2{font-size:var(--f-2);letter-spacing:.14em;text-transform:uppercase;
     color:var(--muted);font-weight:500;margin:var(--sp3) 0 var(--sp1)}
  table{width:100%;border-collapse:collapse;font-size:var(--f-1)}
  th{text-align:left;font-weight:500;color:var(--muted);font-size:var(--f-3);
     letter-spacing:.1em;text-transform:uppercase;padding:var(--sp0) var(--sp1);
     border-bottom:1px solid var(--border)}
  td{padding:var(--sp0) var(--sp1);border-bottom:1px solid var(--border);vertical-align:top}
  tr:last-child td{border-bottom:none}
  .mono{font-family:var(--mono);font-size:var(--f-2)}
  .dot{display:inline-block;width:.5rem;height:.5rem;border-radius:50%;
       margin-right:var(--sp-1);vertical-align:middle}
  .dot.live{background:var(--accent);box-shadow:0 0 calc(var(--sp0)*2) var(--accent)}
  .dot.done{background:var(--muted)} .dot.stop{background:var(--golden)}
  .gate{display:flex;justify-content:space-between;gap:var(--sp1);
        padding:var(--sp0) 0;border-bottom:1px solid var(--border);font-size:var(--f-1)}
  .gate:last-child{border-bottom:none}
  .gate b{font-weight:500}
  input,button{font-family:var(--font);font-size:var(--f-1);border-radius:var(--sp0);
        border:1px solid var(--border);background:var(--panel);color:var(--text);
        padding:var(--sp0) var(--sp1)}
  button{cursor:pointer;border-color:var(--accent-dark);color:var(--accent)}
  button:hover{background:rgba(0,255,136,.08)}
  .auth{display:flex;gap:var(--sp0);align-items:center;flex-wrap:wrap;
        margin-bottom:var(--sp2)}
  .err{color:var(--golden);font-size:var(--f-1)}
  footer{margin-top:var(--sp3);padding-top:var(--sp1);border-top:1px solid var(--border);
         color:var(--muted);font-size:var(--f-3);display:flex;
         justify-content:space-between;gap:var(--sp1);flex-wrap:wrap}
  .phi{color:var(--golden)}
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>trios <span>&#8226;</span> queen</h1>
    <div class="sub" id="where">the supervisor, where she actually runs</div>
  </header>

  <div class="auth" id="auth">
    <input type="password" id="token" placeholder="deployment token" size="34" autocomplete="off" />
    <button id="go">connect</button>
    <span class="sub">stays in this tab only — never in the URL</span>
  </div>
  <div class="err" id="err"></div>

  <div id="app" hidden>
    <div class="grid">
      <div class="card"><div class="k">lease</div><div class="v small" id="lease">—</div></div>
      <div class="card"><div class="k">last round</div><div class="v small" id="tick">—</div></div>
      <div class="card"><div class="k">decision</div><div class="v small" id="decision">—</div></div>
      <div class="card"><div class="k">bees in flight</div><div class="v" id="inflight">—</div></div>
    </div>

    <h2>dispatches</h2>
    <table>
      <thead><tr><th>issue</th><th>branch</th><th>state</th><th>detail</th></tr></thead>
      <tbody id="rows"><tr><td colspan="4" class="off">—</td></tr></tbody>
    </table>

    <h2>what binds the swarm</h2>
    <div id="bounds"></div>
  </div>

  <footer>
    <span>&#966;<sup>2</sup> + 1/&#966;<sup>2</sup> = 3 &nbsp; <span class="phi">TRINITY</span></span>
    <span id="stamp">—</span>
  </footer>
</div>

<script>
(function () {
  var $ = function (id) { return document.getElementById(id) }
  var KEY = 'trios.queen.token'
  var token = sessionStorage.getItem(KEY) || ''

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]
    })
  }
  function ago(iso) {
    if (!iso) return '—'
    var s = Math.round((Date.now() - new Date(iso).getTime()) / 1000)
    if (s < 0) return 'in ' + (-s) + 's'
    if (s < 90) return s + 's ago'
    if (s < 5400) return Math.round(s / 60) + 'm ago'
    return Math.round(s / 3600) + 'h ago'
  }

  function paint(d) {
    var lease = d.lease
    // A lease already past its expiry is FREE, not held. Printing the last
    // holder's name without checking the clock is how a dashboard reports a
    // supervisor that stopped hours ago as the one on duty.
    var free = !lease || new Date(lease.expiresAt).getTime() < Date.now()
    $('lease').innerHTML = free
      ? '<span class="dot done"></span><span class="off">free between rounds</span>'
      : '<span class="dot live"></span>' + esc(lease.holder.slice(0, 22)) +
        '<br><span class="off">term ' + esc(lease.fence) + '</span>'

    var t = d.lastTick
    $('tick').innerHTML = t
      ? esc(ago(t.decidedAt)) + '<br><span class="off">' + esc(String(t.decidedAt).slice(11, 19)) + '</span>'
      : '<span class="off">never</span>'

    var dec = t && t.decision ? t.decision : null
    $('decision').innerHTML = !dec
      ? '<span class="off">—</span>'
      : dec.chosen
        ? '<span class="ok">#' + esc(dec.chosen) + '</span>'
        : '<span class="off">' + esc(dec.refusal || 'nothing') + '</span>'

    var ds = d.dispatches || []
    var live = ds.filter(function (x) { return x.started && !x.finishedAt })
    $('inflight').innerHTML = '<span class="' + (live.length ? 'ok' : 'off') + '">' +
      live.length + '</span><span class="off"> / 4</span>'

    $('rows').innerHTML = ds.length === 0
      ? '<tr><td colspan="4" class="off">nothing dispatched yet</td></tr>'
      : ds.map(function (x) {
          var cls = !x.started ? 'stop' : (x.finishedAt ? 'done' : 'live')
          var st = !x.started ? 'refused' : (x.finishedAt ? 'finished ' + ago(x.finishedAt) : 'running')
          return '<tr><td class="mono">#' + esc(x.issue) + '</td>' +
            '<td class="mono off">' + esc(x.branch) + '</td>' +
            '<td><span class="dot ' + cls + '"></span>' + esc(st) + '</td>' +
            '<td class="off">' + esc((x.outcome || x.detail || '').slice(0, 120)) + '</td></tr>'
        }).join('')

    // The skipped reasons are the most useful thing the tick produces and the
    // hardest to find: they say, per candidate, why the swarm is not bigger.
    var skipped = (dec && dec.skipped) || []
    $('bounds').innerHTML = skipped.length === 0
      ? '<div class="gate off">the last round skipped nothing</div>'
      : skipped.slice(0, 12).map(function (s) {
          var i = s.indexOf(':')
          return '<div class="gate"><b class="mono">' + esc(s.slice(0, i)) + '</b>' +
                 '<span class="off">' + esc(s.slice(i + 1).trim()) + '</span></div>'
        }).join('')

    $('stamp').textContent = 'refreshed ' + new Date().toTimeString().slice(0, 8)
  }

  function load() {
    fetch('/queen/lease', { headers: { Authorization: 'Bearer ' + token } })
      .then(function (r) {
        if (r.status === 403) throw new Error('the deployment refused that token')
        if (!r.ok) throw new Error('server answered ' + r.status)
        return r.json()
      })
      .then(function (d) {
        $('err').textContent = ''
        $('auth').hidden = true
        $('app').hidden = false
        paint(d)
      })
      .catch(function (e) {
        $('err').textContent = e.message
        $('auth').hidden = false
      })
  }

  $('go').addEventListener('click', function () {
    token = $('token').value.trim()
    if (!token) return
    sessionStorage.setItem(KEY, token)
    load()
  })
  $('token').addEventListener('keydown', function (e) {
    if (e.key === 'Enter') $('go').click()
  })

  $('where').textContent = location.host
  if (token) load()
  setInterval(function () { if (token && !$('app').hidden) load() }, 15000)
})()
</script>
</body>
</html>`

export function createQueenDashboardRoute() {
  return new Hono().get('/', (c) =>
    c.html(PAGE, 200, {
      // No caching: a supervisor dashboard served from cache is a dashboard
      // showing a swarm that has moved on.
      'Cache-Control': 'no-store',
      // The shell carries no state, but it does fetch one and hold a token in
      // memory, so it should not be framed by anything else.
      'X-Frame-Options': 'DENY',
    }),
  )
}
