#!/usr/bin/env node
// Does the generated ring agree with the hand-written twin that is in production?
//
// WHY THIS IS THE FIRST THING RING-00 NEEDED. L0 says every rule below the
// interface is written once in `.t27` and generated to its target, because "a
// rule transcribed into Swift, Rust, Zig and Verilog is four rules that agree
// until someone edits one." The t27-backend skill then records where that stands
// and it is blunt: T27-00 "generates but does not run anywhere, so strictly the
// plan is blocked at its first ring."
//
// The block is real but it is not the whole story, and the missing piece is
// this one. `can_start_another` is in the tree THREE times today - the spec at
// `rings/T27-00/queen_core.t27:198`, and two Swift copies at
// `rings/SR-00/QueenDelegation.swift:472` and
// `agent-server/queen-core/Sources/QueenPolicy/QueenDelegation.swift:472`. They
// agree right now. Nothing anywhere would notice if they stopped.
//
// That is exactly the defect this repository found in a different rule the day
// before: the boundary parser had three implementations, two knew both headings
// and the third did not, and seven bees carried a false accusation for weeks
// because nobody had put the three side by side. Writing the rule in one place
// is the cure; until the transcriptions are gone, COMPARING them is the guard.
//
// WHAT IS COMPARED, AND WHY THESE TWO SIDES:
//
//   the ring   `rings/T27-00/generated/queen_core.rs`, generated by t27c from
//              the spec and compiled by bare `rustc`, driven through
//              `rings/T27-00/parity/probe.rs`.
//   the twin   `queend`, the Swift decision binary the CONTAINER runs. Not a
//              re-implementation written for this harness - the actual artifact
//              production asks, taking a JSON question on stdin.
//
// EXHAUSTIVE, NOT SAMPLED. Ring 00 is integers and booleans with small ranges,
// so the whole meaningful input space fits in a few hundred cases. A sampled
// parity check has a coverage number that has to be defended; an exhaustive one
// over a bounded space does not. Where a range is deliberately capped, the cap
// is stated in the grid below and printed with the result.
//
// A MISSING SIDE IS NOT AGREEMENT. If `queend` is not built, or the ring will
// not compile, this reports that and exits non-zero. The one answer this tool
// must never give is a green tick for a comparison it did not make.
//
// Usage:
//   node t27-parity.mjs           # compare, print disagreements
//   node t27-parity.mjs --build   # regenerate the artifact and rebuild first

import fs from 'node:fs'
import path from 'node:path'
import { execSync, execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const DIR = path.dirname(fileURLToPath(import.meta.url))
const isMain = process.argv[1] && process.argv[1].endsWith('/t27-parity.mjs')

const ROOT = process.env.TRIOS_ROOT || '/Users/playra/BrowserOS'
const TRIOS = path.join(ROOT, 'trios')
const SPEC = path.join(TRIOS, 'rings/T27-00/queen_core.t27')
const ARTIFACT = path.join(TRIOS, 'rings/T27-00/generated/queen_core.rs')
const PROBE_SRC = path.join(TRIOS, 'rings/T27-00/parity/probe.rs')
const BUILD = path.join(TRIOS, '.trinity/t27c-build')
const T27C = path.join(BUILD, 'release/t27c')
const PROBE = path.join(BUILD, 'parity/probe')
const QUEEND = path.join(TRIOS, 'agent-server/queen-core/.build/arm64-apple-macosx/release/queend')

const tryShell = (c) => { try { return execSync(c, { cwd: TRIOS, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 32 * 1024 * 1024 }) } catch (e) { return { error: String(e.stderr || e.message).slice(0, 400) } } }

/**
 * A constant of the ring, read from the generated artifact rather than typed.
 *
 * `MAX_CONCURRENT_WORKERS = 4` is in this tree FIVE times: the spec, two Swift
 * copies, and - found while writing this file - twice more in the loop's own
 * tooling, as prose inside the dashboard label `bees running (of 4)` and the
 * snapshot's copy of it. Four of the five are transcriptions, and two of them
 * are mine. A loop that reports on a swarm's discipline while holding its own
 * copy of the swarm's constant has no standing to.
 *
 * This does not re-implement anything: it reads one line out of the artifact
 * that `t27c` wrote. If the artifact is absent the answer is null and the
 * caller must print a dash - the number 4 must never be invented here, because
 * an invented constant that happens to be right is the same defect wearing a
 * correct answer.
 */
export function ringConst(name, file = ARTIFACT) {
  let src
  try { src = fs.readFileSync(file, 'utf8') } catch { return null }
  const m = src.match(new RegExp(`^pub const ${name}: \\w+ = (-?\\d+);`, 'm'))
  return m ? Number(m[1]) : null
}

/** The three failure kinds, in the coding the ring uses and the words the twin uses. */
export const FAILURE_KINDS = [
  { code: 0, word: 'interrupted' },
  { code: 1, word: 'producedNothing' },
  { code: 2, word: 'workedButFailed' },
]

/**
 * Every sequence of prior attempts up to `depth`, as both sides spell it.
 *
 * Depth 3 rather than 2 on purpose: the rule turns at 2, and a grid that stops
 * where the rule turns cannot show a side that keeps counting past the turn.
 */
export function retryGrid(depth = 3) {
  const rows = [[]]
  for (let d = 0; d < depth; d++) {
    const next = []
    for (const r of rows.filter((x) => x.length === d)) {
      for (const k of FAILURE_KINDS) next.push([...r, k])
    }
    rows.push(...next)
  }
  return rows.map((seq) => ({
    words: seq.map((k) => k.word),
    codes: seq.map((k) => k.code),
    // The ring is asked with the FILTERED count, because its own comment says
    // the filter belongs to the law rather than to whoever remembers it. The
    // filter used here is the ring's `counts_against_issue`, not a copy of it.
    real: seq.filter((k) => k.code === 1 || k.code === 2).length,
  }))
}

/**
 * The review space, bounded and stated.
 *
 * `total` to 4 and `prior` to 3 because both rules turn at or below those
 * numbers (MAX_SEND_BACKS is 2) and nothing above them can behave differently
 * without a new branch appearing in the spec - which this grid would then miss,
 * and which the case count printed with the result is there to make visible.
 */
export function reviewGrid(maxTotal = 4, maxPrior = 3, maxFiles = 2) {
  const rows = []
  for (let total = 0; total <= maxTotal; total++) {
    for (let judged = 0; judged <= total; judged++) {
      for (let unmet = 0; unmet <= judged; unmet++) {
        for (let files = 0; files <= maxFiles; files++) {
          for (let prior = 0; prior <= maxPrior; prior++) rows.push({ total, judged, unmet, files, prior })
        }
      }
    }
  }
  return rows
}

/** Ask the ring every question in one pass. */
export function askRing(questions, probe = PROBE) {
  const answers = execFileSync(probe, { input: questions.join('\n') + '\n', encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 })
  return answers.split('\n').filter((l) => l.length)
}

/** Ask the twin one question. One decision per invocation is its own protocol. */
export function askTwin(question, queend = QUEEND) {
  try {
    const out = execFileSync(queend, { input: JSON.stringify(question), encoding: 'utf8', timeout: 20000 })
    return JSON.parse(out)
  } catch (e) {
    return { error: String(e.stderr || e.message).slice(0, 200) }
  }
}

/**
 * Compare, and say what disagreed rather than how many.
 *
 * A count is enough to fail a gate and useless to fix anything: the input that
 * separates two implementations IS the bug report.
 */
export function compare(cases) {
  const disagreements = []
  const errors = []
  for (const c of cases) {
    if (c.twin === null) { errors.push(c); continue }
    if (c.ring !== c.twin) disagreements.push(c)
  }
  return { n: cases.length, disagreements, errors }
}

if (isMain) {
  const rebuild = process.argv.includes('--build')
  const out = []

  if (rebuild) {
    if (!fs.existsSync(T27C)) {
      console.log(`the compiler is not built at ${path.relative(ROOT, T27C)}`)
      console.log('build it WITHOUT writing into the sibling checkout (L0b - another agent owns that tree):')
      console.log(`  CARGO_TARGET_DIR=${path.relative(ROOT, BUILD)} cargo build --release --manifest-path ~/t27/bootstrap/Cargo.toml`)
      process.exit(1)
    }
    const gen = tryShell(`${T27C} gen-rust ${SPEC}`)
    if (gen.error) { console.log(`t27c could not generate the ring: ${gen.error}`); process.exit(1) }
    fs.mkdirSync(path.dirname(ARTIFACT), { recursive: true })
    fs.writeFileSync(ARTIFACT, gen)
    console.log(`regenerated ${path.relative(ROOT, ARTIFACT)} (${gen.split('\n').length} lines)`)
  }

  // A MISSING SIDE IS NOT AGREEMENT.
  for (const [what, file, how] of [
    ['the generated ring', ARTIFACT, 'run with --build, or `tri t27-gen`'],
    ['the probe source', PROBE_SRC, 'it is checked in beside the ring'],
    ['the twin `queend`', QUEEND, 'swift build -c release --package-path agent-server/queen-core'],
  ]) {
    if (!fs.existsSync(file)) {
      console.log(`${what} is missing at ${path.relative(ROOT, file)}`)
      console.log(`  ${how}`)
      console.log('\nNothing was compared. A parity report with a side missing is the one answer this must never give.')
      process.exit(3)
    }
  }

  fs.mkdirSync(path.dirname(PROBE), { recursive: true })
  const built = tryShell(`rustc --edition 2021 -O ${PROBE_SRC} -o ${PROBE} 2>&1`)
  if (!fs.existsSync(PROBE)) {
    console.log(`the ring would not compile:\n${built.error || built}`)
    process.exit(1)
  }

  // ---- retry ---------------------------------------------------------------
  const retry = retryGrid(3)
  const ringRetry = askRing(retry.map((r) => `retry ${r.real}`))
  const retryCases = retry.map((r, i) => {
    const a = askTwin({ kind: 'retry', priorAttempts: r.words })
    return {
      what: `retry priorAttempts=[${r.words.join(',')}] real=${r.real}`,
      ring: ringRetry[i],
      twin: a.error ? null : (a.allowed ? 'attempt' : 'escalate'),
      note: a.error || '',
    }
  })

  // ---- review --------------------------------------------------------------
  const review = reviewGrid()
  const ringReview = askRing(review.map((r) => `review ${r.total} ${r.judged} ${r.unmet} ${r.files} ${r.prior}`))
  const reviewCases = review.map((r, i) => {
    // The twin takes a verdict per criterion; the ring takes counts. Building
    // the twin's shape FROM the counts is the translation under test.
    const verdicts = []
    for (let k = 0; k < r.judged; k++) verdicts.push({ criterion: `c${k}`, met: k >= r.unmet })
    const a = askTwin({ kind: 'review', verdicts, totalCriteria: r.total, committedFiles: r.files, priorSendBacks: r.prior })
    return {
      what: `review total=${r.total} judged=${r.judged} unmet=${r.unmet} files=${r.files} prior=${r.prior}`,
      ring: ringReview[i],
      twin: a.error ? null : a.verdict,
      note: a.error || '',
    }
  })

  const all = [...retryCases, ...reviewCases]
  const r = compare(all)

  console.log(`ring T27-00 against the twin that runs in production`)
  console.log(`  spec      ${path.relative(ROOT, SPEC)}`)
  console.log(`  artifact  ${path.relative(ROOT, ARTIFACT)}  (generated, never edited)`)
  console.log(`  twin      ${path.relative(ROOT, QUEEND)}`)
  console.log(`\n  ${retryCases.length} retry case(s) - every attempt sequence up to depth 3, exhaustive`)
  console.log(`  ${reviewCases.length} review case(s) - total<=4, judged<=total, unmet<=judged, files<=2, prior<=3, exhaustive`)
  console.log(`  ${r.n} compared, ${r.disagreements.length} disagreement(s), ${r.errors.length} the twin could not answer`)

  for (const e of r.errors.slice(0, 5)) console.log(`  ?  ${e.what}\n     the twin said: ${e.note}`)
  for (const d of r.disagreements.slice(0, 20)) {
    console.log(`  !! ${d.what}`)
    console.log(`     ring says ${d.ring}, twin says ${d.twin}`)
  }
  if (r.disagreements.length > 20) console.log(`  ... and ${r.disagreements.length - 20} more`)

  if (!r.disagreements.length && !r.errors.length) {
    console.log('\nThe generated ring and the Swift binary answer identically on every input in the grid.')
    console.log('That is a measurement, not a licence: it says they agree TODAY. The law exists')
    console.log('because two sources are the state from which they start to disagree, and this')
    console.log('check is what makes the next divergence loud instead of silent.')
  }
  // LAST LINE IS THE VERDICT, because the chain that runs this quotes the last
  // line as its summary - and it was quoting a sentence of prose about why the
  // check exists, which says nothing about whether it passed.
  console.log(`\n${r.n} case(s) compared, ${r.disagreements.length} disagreement(s), ${r.errors.length} unanswered`)
  process.exit(r.disagreements.length || r.errors.length ? 2 : 0)
}
