//! SeaORM Entity definitions for the chat persistence layer.
//!
//! One module per table. Generated by hand to keep this ring tiny and
//! to avoid pulling in `sea-orm-codegen`.

pub mod chat_envelope;
