-- DDL migration 005 — figure registry v1.2 (multi-figure per chapter)
-- v5.4 expansion: each chapter now has 4 figures (1 v5.3 engraved + 1 legacy + 2 cross-ref)
-- Refs: trios#380, trios#265, trios#619, PR #627
-- Anchor: phi^2 + phi^-2 = 3 · DOI 10.5281/zenodo.19227877

BEGIN;

CREATE TABLE IF NOT EXISTS ssot.chapter_figures_v2 (
  chapter_slug TEXT NOT NULL,
  figure_index SMALLINT NOT NULL,
  figure_filename TEXT NOT NULL,
  figure_role TEXT NOT NULL CHECK (figure_role IN ('chapter','legacy','cross-ref')),
  figure_source_url TEXT NOT NULL,
  alt_text TEXT NOT NULL,
  license TEXT DEFAULT 'CC-BY-4.0',
  inserted_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (chapter_slug, figure_index)
);

TRUNCATE ssot.chapter_figures_v2;

INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('00-monad', 0, '00-monad.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/00-monad.png', 'Engraved scientific triptych on white #FFFFFF for 00-monad; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('00-monad', 1, 'ch01-introduction.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch01-introduction.png', 'Legacy v1.0 figure ch01-introduction.png restored as additional plate for 00-monad', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('00-monad', 2, '27-trinity-identity.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/27-trinity-identity.png', 'Cross-reference figure 27-trinity-identity.png for subsection of 00-monad', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('00-monad', 3, 'app-a-cover-abstract.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/app-a-cover-abstract.png', 'Cross-reference figure app-a-cover-abstract.png for subsection of 00-monad', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('01-golden-egg', 0, '01-golden-egg.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/01-golden-egg.png', 'Engraved scientific triptych on white #FFFFFF for 01-golden-egg; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('01-golden-egg', 1, 'ch04-sacred-formula.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch04-sacred-formula.png', 'Legacy v1.0 figure ch04-sacred-formula.png restored as additional plate for 01-golden-egg', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('01-golden-egg', 2, '11-vesica-piscis.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/11-vesica-piscis.png', 'Cross-reference figure 11-vesica-piscis.png for subsection of 01-golden-egg', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('01-golden-egg', 3, 'app-b-golden-ledger.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/app-b-golden-ledger.png', 'Cross-reference figure app-b-golden-ledger.png for subsection of 01-golden-egg', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('02-golden-cut', 0, '02-golden-cut.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/02-golden-cut.png', 'Engraved scientific triptych on white #FFFFFF for 02-golden-cut; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('02-golden-cut', 1, 'ch02-background.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch02-background.png', 'Legacy v1.0 figure ch02-background.png restored as additional plate for 02-golden-cut', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('02-golden-cut', 2, '16-sacred-ratios.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/16-sacred-ratios.png', 'Cross-reference figure 16-sacred-ratios.png for subsection of 02-golden-cut', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('02-golden-cut', 3, '17-golden-spiral.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/17-golden-spiral.png', 'Cross-reference figure 17-golden-spiral.png for subsection of 02-golden-cut', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('03-golden-harvest', 0, '03-golden-harvest.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/03-golden-harvest.png', 'Engraved scientific triptych on white #FFFFFF for 03-golden-harvest; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('03-golden-harvest', 1, 'ch03-trinity-identity.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch03-trinity-identity.png', 'Legacy v1.0 figure ch03-trinity-identity.png restored as additional plate for 03-golden-harvest', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('03-golden-harvest', 2, '07-golden-sprout.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/07-golden-sprout.png', 'Cross-reference figure 07-golden-sprout.png for subsection of 03-golden-harvest', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('03-golden-harvest', 3, '19-fibonacci-tesselation.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/19-fibonacci-tesselation.png', 'Cross-reference figure 19-fibonacci-tesselation.png for subsection of 03-golden-harvest', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('04-golden-scales', 0, '04-golden-scales.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/04-golden-scales.png', 'Engraved scientific triptych on white #FFFFFF for 04-golden-scales; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('04-golden-scales', 1, 'ch04-sacred-formula.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch04-sacred-formula.png', 'Legacy v1.0 figure ch04-sacred-formula.png restored as additional plate for 04-golden-scales', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('04-golden-scales', 2, '27-trinity-identity.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/27-trinity-identity.png', 'Cross-reference figure 27-trinity-identity.png for subsection of 04-golden-scales', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('04-golden-scales', 3, '10-golden-bloom.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/10-golden-bloom.png', 'Cross-reference figure 10-golden-bloom.png for subsection of 04-golden-scales', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('05-golden-bridge', 0, '05-golden-bridge.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/05-golden-bridge.png', 'Engraved scientific triptych on white #FFFFFF for 05-golden-bridge; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('05-golden-bridge', 1, 'ch12-hardware-bridge.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch12-hardware-bridge.png', 'Legacy v1.0 figure ch12-hardware-bridge.png restored as additional plate for 05-golden-bridge', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('05-golden-bridge', 2, '06-golden-mantissa.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/06-golden-mantissa.png', 'Cross-reference figure 06-golden-mantissa.png for subsection of 05-golden-bridge', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('05-golden-bridge', 3, '29-lucas-closure.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/29-lucas-closure.png', 'Cross-reference figure 29-lucas-closure.png for subsection of 05-golden-bridge', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('06-golden-mantissa', 0, '06-golden-mantissa.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/06-golden-mantissa.png', 'Engraved scientific triptych on white #FFFFFF for 06-golden-mantissa; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('06-golden-mantissa', 1, 'ch06-goldenfloat-family.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch06-goldenfloat-family.png', 'Legacy v1.0 figure ch06-goldenfloat-family.png restored as additional plate for 06-golden-mantissa', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('06-golden-mantissa', 2, '08-golden-crystal.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/08-golden-crystal.png', 'Cross-reference figure 08-golden-crystal.png for subsection of 06-golden-mantissa', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('06-golden-mantissa', 3, '09-golden-seal.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/09-golden-seal.png', 'Cross-reference figure 09-golden-seal.png for subsection of 06-golden-mantissa', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('07-golden-sprout', 0, '07-golden-sprout.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/07-golden-sprout.png', 'Engraved scientific triptych on white #FFFFFF for 07-golden-sprout; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('07-golden-sprout', 1, 'ch07-vogel-phyllotaxis.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch07-vogel-phyllotaxis.png', 'Legacy v1.0 figure ch07-vogel-phyllotaxis.png restored as additional plate for 07-golden-sprout', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('07-golden-sprout', 2, '12-flower-of-life.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/12-flower-of-life.png', 'Cross-reference figure 12-flower-of-life.png for subsection of 07-golden-sprout', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('07-golden-sprout', 3, '19-fibonacci-tesselation.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/19-fibonacci-tesselation.png', 'Cross-reference figure 19-fibonacci-tesselation.png for subsection of 07-golden-sprout', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('08-golden-crystal', 0, '08-golden-crystal.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/08-golden-crystal.png', 'Engraved scientific triptych on white #FFFFFF for 08-golden-crystal; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('08-golden-crystal', 1, 'ch08-tf3-tf9-ternary-matmul.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch08-tf3-tf9-ternary-matmul.png', 'Legacy v1.0 figure ch08-tf3-tf9-ternary-matmul.png restored as additional plate for 08-golden-crystal', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('08-golden-crystal', 2, '23-gf16-algebra.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/23-gf16-algebra.png', 'Cross-reference figure 23-gf16-algebra.png for subsection of 08-golden-crystal', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('08-golden-crystal', 3, '14-platonic-solids.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/14-platonic-solids.png', 'Cross-reference figure 14-platonic-solids.png for subsection of 08-golden-crystal', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('09-golden-seal', 0, '09-golden-seal.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/09-golden-seal.png', 'Engraved scientific triptych on white #FFFFFF for 09-golden-seal; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('09-golden-seal', 1, 'ch09-gf-vs-mxfp4-ablation.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch09-gf-vs-mxfp4-ablation.png', 'Legacy v1.0 figure ch09-gf-vs-mxfp4-ablation.png restored as additional plate for 09-golden-seal', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('09-golden-seal', 2, '17-golden-spiral.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/17-golden-spiral.png', 'Cross-reference figure 17-golden-spiral.png for subsection of 09-golden-seal', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('09-golden-seal', 3, '25-benchmarks.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/25-benchmarks.png', 'Cross-reference figure 25-benchmarks.png for subsection of 09-golden-seal', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('10-golden-bloom', 0, '10-golden-bloom.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/10-golden-bloom.png', 'Engraved scientific triptych on white #FFFFFF for 10-golden-bloom; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('10-golden-bloom', 1, 'ch10-coq-l1-pareto.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch10-coq-l1-pareto.png', 'Legacy v1.0 figure ch10-coq-l1-pareto.png restored as additional plate for 10-golden-bloom', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('10-golden-bloom', 2, '29-lucas-closure.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/29-lucas-closure.png', 'Cross-reference figure 29-lucas-closure.png for subsection of 10-golden-bloom', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('10-golden-bloom', 3, '27-trinity-identity.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/27-trinity-identity.png', 'Cross-reference figure 27-trinity-identity.png for subsection of 10-golden-bloom', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('11-vesica-piscis', 0, '11-vesica-piscis.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/11-vesica-piscis.png', 'Engraved scientific triptych on white #FFFFFF for 11-vesica-piscis; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('11-vesica-piscis', 1, 'ch11-pre-registration.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch11-pre-registration.png', 'Legacy v1.0 figure ch11-pre-registration.png restored as additional plate for 11-vesica-piscis', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('11-vesica-piscis', 2, '12-flower-of-life.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/12-flower-of-life.png', 'Cross-reference figure 12-flower-of-life.png for subsection of 11-vesica-piscis', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('11-vesica-piscis', 3, '13-metatron-cube.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/13-metatron-cube.png', 'Cross-reference figure 13-metatron-cube.png for subsection of 11-vesica-piscis', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('12-flower-of-life', 0, '12-flower-of-life.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/12-flower-of-life.png', 'Engraved scientific triptych on white #FFFFFF for 12-flower-of-life; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('12-flower-of-life', 1, 'ch12-hardware-bridge.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch12-hardware-bridge.png', 'Legacy v1.0 figure ch12-hardware-bridge.png restored as additional plate for 12-flower-of-life', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('12-flower-of-life', 2, '13-metatron-cube.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/13-metatron-cube.png', 'Cross-reference figure 13-metatron-cube.png for subsection of 12-flower-of-life', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('12-flower-of-life', 3, '14-platonic-solids.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/14-platonic-solids.png', 'Cross-reference figure 14-platonic-solids.png for subsection of 12-flower-of-life', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('13-metatron-cube', 0, '13-metatron-cube.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/13-metatron-cube.png', 'Engraved scientific triptych on white #FFFFFF for 13-metatron-cube; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('13-metatron-cube', 1, 'ch16-360-lane-grid.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch16-360-lane-grid.png', 'Legacy v1.0 figure ch16-360-lane-grid.png restored as additional plate for 13-metatron-cube', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('13-metatron-cube', 2, '14-platonic-solids.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/14-platonic-solids.png', 'Cross-reference figure 14-platonic-solids.png for subsection of 13-metatron-cube', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('13-metatron-cube', 3, '15-kepler-solids.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/15-kepler-solids.png', 'Cross-reference figure 15-kepler-solids.png for subsection of 13-metatron-cube', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('14-platonic-solids', 0, '14-platonic-solids.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/14-platonic-solids.png', 'Engraved scientific triptych on white #FFFFFF for 14-platonic-solids; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('14-platonic-solids', 1, 'ch14-eval-semantics.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch14-eval-semantics.png', 'Legacy v1.0 figure ch14-eval-semantics.png restored as additional plate for 14-platonic-solids', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('14-platonic-solids', 2, '15-kepler-solids.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/15-kepler-solids.png', 'Cross-reference figure 15-kepler-solids.png for subsection of 14-platonic-solids', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('14-platonic-solids', 3, '13-metatron-cube.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/13-metatron-cube.png', 'Cross-reference figure 13-metatron-cube.png for subsection of 14-platonic-solids', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('15-kepler-solids', 0, '15-kepler-solids.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/15-kepler-solids.png', 'Engraved scientific triptych on white #FFFFFF for 15-kepler-solids; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('15-kepler-solids', 1, 'ch15-bpb-benchmark.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch15-bpb-benchmark.png', 'Legacy v1.0 figure ch15-bpb-benchmark.png restored as additional plate for 15-kepler-solids', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('15-kepler-solids', 2, '14-platonic-solids.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/14-platonic-solids.png', 'Cross-reference figure 14-platonic-solids.png for subsection of 15-kepler-solids', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('15-kepler-solids', 3, '22-e8-symmetry.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/22-e8-symmetry.png', 'Cross-reference figure 22-e8-symmetry.png for subsection of 15-kepler-solids', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('16-sacred-ratios', 0, '16-sacred-ratios.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/16-sacred-ratios.png', 'Engraved scientific triptych on white #FFFFFF for 16-sacred-ratios; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('16-sacred-ratios', 1, 'ch16-360-lane-grid.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch16-360-lane-grid.png', 'Legacy v1.0 figure ch16-360-lane-grid.png restored as additional plate for 16-sacred-ratios', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('16-sacred-ratios', 2, '17-golden-spiral.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/17-golden-spiral.png', 'Cross-reference figure 17-golden-spiral.png for subsection of 16-sacred-ratios', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('16-sacred-ratios', 3, '27-trinity-identity.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/27-trinity-identity.png', 'Cross-reference figure 27-trinity-identity.png for subsection of 16-sacred-ratios', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('17-golden-spiral', 0, '17-golden-spiral.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/17-golden-spiral.png', 'Engraved scientific triptych on white #FFFFFF for 17-golden-spiral; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('17-golden-spiral', 1, 'ch17-ablation-matrix.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch17-ablation-matrix.png', 'Legacy v1.0 figure ch17-ablation-matrix.png restored as additional plate for 17-golden-spiral', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('17-golden-spiral', 2, '07-golden-sprout.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/07-golden-sprout.png', 'Cross-reference figure 07-golden-sprout.png for subsection of 17-golden-spiral', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('17-golden-spiral', 3, '19-fibonacci-tesselation.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/19-fibonacci-tesselation.png', 'Cross-reference figure 19-fibonacci-tesselation.png for subsection of 17-golden-spiral', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('18-torus-geometry', 0, '18-torus-geometry.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/18-torus-geometry.png', 'Engraved scientific triptych on white #FFFFFF for 18-torus-geometry; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('18-torus-geometry', 1, 'ch18-limitations.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch18-limitations.png', 'Legacy v1.0 figure ch18-limitations.png restored as additional plate for 18-torus-geometry', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('18-torus-geometry', 2, '12-flower-of-life.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/12-flower-of-life.png', 'Cross-reference figure 12-flower-of-life.png for subsection of 18-torus-geometry', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('18-torus-geometry', 3, '13-metatron-cube.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/13-metatron-cube.png', 'Cross-reference figure 13-metatron-cube.png for subsection of 18-torus-geometry', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('19-fibonacci-tesselation', 0, '19-fibonacci-tesselation.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/19-fibonacci-tesselation.png', 'Engraved scientific triptych on white #FFFFFF for 19-fibonacci-tesselation; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('19-fibonacci-tesselation', 1, 'ch19-statistical-analysis.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch19-statistical-analysis.png', 'Legacy v1.0 figure ch19-statistical-analysis.png restored as additional plate for 19-fibonacci-tesselation', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('19-fibonacci-tesselation', 2, '17-golden-spiral.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/17-golden-spiral.png', 'Cross-reference figure 17-golden-spiral.png for subsection of 19-fibonacci-tesselation', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('19-fibonacci-tesselation', 3, '26-data-analysis.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/26-data-analysis.png', 'Cross-reference figure 26-data-analysis.png for subsection of 19-fibonacci-tesselation', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('20-standard-model', 0, '20-standard-model.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/20-standard-model.png', 'Engraved scientific triptych on white #FFFFFF for 20-standard-model; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('20-standard-model', 1, 'ch29-sacred-formula-v.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch29-sacred-formula-v.png', 'Legacy v1.0 figure ch29-sacred-formula-v.png restored as additional plate for 20-standard-model', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('20-standard-model', 2, '21-quantum-field.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/21-quantum-field.png', 'Cross-reference figure 21-quantum-field.png for subsection of 20-standard-model', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('20-standard-model', 3, '22-e8-symmetry.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/22-e8-symmetry.png', 'Cross-reference figure 22-e8-symmetry.png for subsection of 20-standard-model', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('21-quantum-field', 0, '21-quantum-field.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/21-quantum-field.png', 'Engraved scientific triptych on white #FFFFFF for 21-quantum-field; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('21-quantum-field', 1, 'ch29-sacred-formula-v.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch29-sacred-formula-v.png', 'Legacy v1.0 figure ch29-sacred-formula-v.png restored as additional plate for 21-quantum-field', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('21-quantum-field', 2, '20-standard-model.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/20-standard-model.png', 'Cross-reference figure 20-standard-model.png for subsection of 21-quantum-field', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('21-quantum-field', 3, '22-e8-symmetry.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/22-e8-symmetry.png', 'Cross-reference figure 22-e8-symmetry.png for subsection of 21-quantum-field', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('22-e8-symmetry', 0, '22-e8-symmetry.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/22-e8-symmetry.png', 'Engraved scientific triptych on white #FFFFFF for 22-e8-symmetry; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('22-e8-symmetry', 1, 'ch22-railway-orchestration.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch22-railway-orchestration.png', 'Legacy v1.0 figure ch22-railway-orchestration.png restored as additional plate for 22-e8-symmetry', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('22-e8-symmetry', 2, '13-metatron-cube.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/13-metatron-cube.png', 'Cross-reference figure 13-metatron-cube.png for subsection of 22-e8-symmetry', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('22-e8-symmetry', 3, '23-gf16-algebra.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/23-gf16-algebra.png', 'Cross-reference figure 23-gf16-algebra.png for subsection of 22-e8-symmetry', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('23-gf16-algebra', 0, '23-gf16-algebra.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/23-gf16-algebra.png', 'Engraved scientific triptych on white #FFFFFF for 23-gf16-algebra; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('23-gf16-algebra', 1, 'ch23-mcp-integration.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch23-mcp-integration.png', 'Legacy v1.0 figure ch23-mcp-integration.png restored as additional plate for 23-gf16-algebra', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('23-gf16-algebra', 2, '08-golden-crystal.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/08-golden-crystal.png', 'Cross-reference figure 08-golden-crystal.png for subsection of 23-gf16-algebra', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('23-gf16-algebra', 3, '06-golden-mantissa.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/06-golden-mantissa.png', 'Cross-reference figure 06-golden-mantissa.png for subsection of 23-gf16-algebra', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('24-igla-architecture', 0, '24-igla-architecture.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/24-igla-architecture.png', 'Engraved scientific triptych on white #FFFFFF for 24-igla-architecture; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('24-igla-architecture', 1, 'ch24-period-locked-monitor.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch24-period-locked-monitor.png', 'Legacy v1.0 figure ch24-period-locked-monitor.png restored as additional plate for 24-igla-architecture', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('24-igla-architecture', 2, '25-benchmarks.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/25-benchmarks.png', 'Cross-reference figure 25-benchmarks.png for subsection of 24-igla-architecture', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('24-igla-architecture', 3, '26-data-analysis.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/26-data-analysis.png', 'Cross-reference figure 26-data-analysis.png for subsection of 24-igla-architecture', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('25-benchmarks', 0, '25-benchmarks.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/25-benchmarks.png', 'Engraved scientific triptych on white #FFFFFF for 25-benchmarks; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('25-benchmarks', 1, 'ch25-phi-period-cycles.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch25-phi-period-cycles.png', 'Legacy v1.0 figure ch25-phi-period-cycles.png restored as additional plate for 25-benchmarks', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('25-benchmarks', 2, '09-golden-seal.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/09-golden-seal.png', 'Cross-reference figure 09-golden-seal.png for subsection of 25-benchmarks', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('25-benchmarks', 3, '26-data-analysis.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/26-data-analysis.png', 'Cross-reference figure 26-data-analysis.png for subsection of 25-benchmarks', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('26-data-analysis', 0, '26-data-analysis.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/26-data-analysis.png', 'Engraved scientific triptych on white #FFFFFF for 26-data-analysis; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('26-data-analysis', 1, 'ch26-koschei-coprocessor-isa.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch26-koschei-coprocessor-isa.png', 'Legacy v1.0 figure ch26-koschei-coprocessor-isa.png restored as additional plate for 26-data-analysis', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('26-data-analysis', 2, '19-fibonacci-tesselation.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/19-fibonacci-tesselation.png', 'Cross-reference figure 19-fibonacci-tesselation.png for subsection of 26-data-analysis', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('26-data-analysis', 3, '25-benchmarks.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/25-benchmarks.png', 'Cross-reference figure 25-benchmarks.png for subsection of 26-data-analysis', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('27-trinity-identity', 0, '27-trinity-identity.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/27-trinity-identity.png', 'Engraved scientific triptych on white #FFFFFF for 27-trinity-identity; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('27-trinity-identity', 1, 'ch27-tri27-dsl.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch27-tri27-dsl.png', 'Legacy v1.0 figure ch27-tri27-dsl.png restored as additional plate for 27-trinity-identity', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('27-trinity-identity', 2, '10-golden-bloom.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/10-golden-bloom.png', 'Cross-reference figure 10-golden-bloom.png for subsection of 27-trinity-identity', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('27-trinity-identity', 3, '29-lucas-closure.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/29-lucas-closure.png', 'Cross-reference figure 29-lucas-closure.png for subsection of 27-trinity-identity', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('28-momentum-algebra', 0, '28-momentum-algebra.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/28-momentum-algebra.png', 'Engraved scientific triptych on white #FFFFFF for 28-momentum-algebra; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('28-momentum-algebra', 1, 'ch28-qmtech-xc7a100t-fpga.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch28-qmtech-xc7a100t-fpga.png', 'Legacy v1.0 figure ch28-qmtech-xc7a100t-fpga.png restored as additional plate for 28-momentum-algebra', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('28-momentum-algebra', 2, '22-e8-symmetry.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/22-e8-symmetry.png', 'Cross-reference figure 22-e8-symmetry.png for subsection of 28-momentum-algebra', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('28-momentum-algebra', 3, '23-gf16-algebra.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/23-gf16-algebra.png', 'Cross-reference figure 23-gf16-algebra.png for subsection of 28-momentum-algebra', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('29-lucas-closure', 0, '29-lucas-closure.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/29-lucas-closure.png', 'Engraved scientific triptych on white #FFFFFF for 29-lucas-closure; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('29-lucas-closure', 1, 'ch10-coq-l1-pareto.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch10-coq-l1-pareto.png', 'Legacy v1.0 figure ch10-coq-l1-pareto.png restored as additional plate for 29-lucas-closure', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('29-lucas-closure', 2, '27-trinity-identity.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/27-trinity-identity.png', 'Cross-reference figure 27-trinity-identity.png for subsection of 29-lucas-closure', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('29-lucas-closure', 3, '10-golden-bloom.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/10-golden-bloom.png', 'Cross-reference figure 10-golden-bloom.png for subsection of 29-lucas-closure', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('30-golden-imagery', 0, '30-golden-imagery.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/30-golden-imagery.png', 'Engraved scientific triptych on white #FFFFFF for 30-golden-imagery; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('30-golden-imagery', 1, 'ch30-trinity-sai.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch30-trinity-sai.png', 'Legacy v1.0 figure ch30-trinity-sai.png restored as additional plate for 30-golden-imagery', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('30-golden-imagery', 2, '16-sacred-ratios.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/16-sacred-ratios.png', 'Cross-reference figure 16-sacred-ratios.png for subsection of 30-golden-imagery', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('30-golden-imagery', 3, '27-trinity-identity.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/27-trinity-identity.png', 'Cross-reference figure 27-trinity-identity.png for subsection of 30-golden-imagery', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('31-philosophy', 0, '31-philosophy.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/31-philosophy.png', 'Engraved scientific triptych on white #FFFFFF for 31-philosophy; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('31-philosophy', 1, 'ch01-introduction.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch01-introduction.png', 'Legacy v1.0 figure ch01-introduction.png restored as additional plate for 31-philosophy', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('31-philosophy', 2, '00-monad.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/00-monad.png', 'Cross-reference figure 00-monad.png for subsection of 31-philosophy', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('31-philosophy', 3, '27-trinity-identity.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/27-trinity-identity.png', 'Cross-reference figure 27-trinity-identity.png for subsection of 31-philosophy', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('32-conclusion', 0, '32-conclusion.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/32-conclusion.png', 'Engraved scientific triptych on white #FFFFFF for 32-conclusion; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('32-conclusion', 1, 'ch34-energy-3000x-darpa.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch34-energy-3000x-darpa.png', 'Legacy v1.0 figure ch34-energy-3000x-darpa.png restored as additional plate for 32-conclusion', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('32-conclusion', 2, '27-trinity-identity.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/27-trinity-identity.png', 'Cross-reference figure 27-trinity-identity.png for subsection of 32-conclusion', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('32-conclusion', 3, '33-epilogue.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/33-epilogue.png', 'Cross-reference figure 33-epilogue.png for subsection of 32-conclusion', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('33-epilogue', 0, '33-epilogue.png', 'chapter', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/33-epilogue.png', 'Engraved scientific triptych on white #FFFFFF for 33-epilogue; Trinity S3AI v5.3', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('33-epilogue', 1, 'ch33-jtag-macos-blk001.png', 'legacy', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/ch33-jtag-macos-blk001.png', 'Legacy v1.0 figure ch33-jtag-macos-blk001.png restored as additional plate for 33-epilogue', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('33-epilogue', 2, '29-lucas-closure.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/29-lucas-closure.png', 'Cross-reference figure 29-lucas-closure.png for subsection of 33-epilogue', 'CC-BY-4.0');
INSERT INTO ssot.chapter_figures_v2 (chapter_slug, figure_index, figure_filename, figure_role, figure_source_url, alt_text, license) VALUES ('33-epilogue', 3, '00-monad.png', 'cross-ref', 'https://raw.githubusercontent.com/gHashTag/trios/feat/phd-v5.3-engraved-figures/assets/illustrations/00-monad.png', 'Cross-reference figure 00-monad.png for subsection of 33-epilogue', 'CC-BY-4.0');

-- Verification:
-- SELECT chapter_slug, COUNT(*) FROM ssot.chapter_figures_v2 GROUP BY chapter_slug ORDER BY chapter_slug;
-- Expected: 34 rows, each with count=4

COMMIT;
